In [2]:

import pandas as pd

In [3]:
d1 = pd.read_excel('作业-餐饮表.xlsx').head(20)
d1

    城市   类型               店名      点评     人均   口味   环境   服务
0   北京  私房菜           梧桐宇私房菜    45.0   80.0  7.3  7.3  7.1
1   北京  私房菜           小东北私房菜     1.0   35.0  6.9  6.9  6.9
2   北京  私房菜            辣家私房菜     1.0    NaN  6.9  6.9  6.9
3   北京  私房菜             鸿福天原     NaN    NaN  NaN  NaN  NaN
4   北京  私房菜  虾而美(北京)餐饮管理有限公司     NaN    NaN  NaN  NaN  NaN
5   北京  私房菜        热炼地带健身工作室     NaN    NaN  NaN  NaN  NaN
6   北京  私房菜         原点老板娘私房菜     2.0    NaN  6.9  6.9  6.9
7   北京  私房菜           常百味家常菜     NaN    NaN  NaN  NaN  NaN
8   北京  北京菜       紫光园(常营店)分店  4420.0   74.0  8.9  8.5  8.3
9   北京  北京菜         府膳(回龙观店)   894.0   86.0  8.6  8.8  8.4
10  北京  北京菜            京门小院儿    46.0   62.0  8.3  8.5  8.3
11  北京  北京菜    我家春饼(龙湖大兴天街店)  1098.0   44.0  8.0  8.2  7.6
12  北京  台湾菜    小明同学(当代商城店)分店   465.0   65.0  8.0  9.0  8.9
13  北京  台湾菜        东都台员(亦庄店)  1757.0   61.0  8.5  8.3  8.4
14  北京  北京菜   红莲烤鸭店(红莲北里店)分店  1320.0   72.0  7.0  6.4  6.2
15  北京  台湾菜          过路人台湾饭团     1.0    NaN  NaN  NaN  NaN
16  北京  家常菜   常赢三兄弟(陆港城总店)分店   305.0  110.0  8.7  8.5  8.0
17  北京  家常菜   太熟悉家常菜(右安门店)分店  3007.0   81.0  7.4  7.6  7.0
18  北京  家常菜              慈孝宫   349.0   88.0  7.2  7.3  6.8
19  北京  家常菜    中国医学科学院肿瘤医院食堂    18.0    NaN  6.6  6.7  6.7

In [4]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   城市      20 non-null     object
 1   类型      20 non-null     object
 2   店名      20 non-null     object
 3   点评      16 non-null     float64
 4   人均      12 non-null     float64
 5   口味      15 non-null     float64
 6   环境      15 non-null     float64
 7   服务      15 non-null     float64
dtypes: float64(5), object(3)
memory usage: 1.4+ KB

In [5]:
d2 = d1.fillna(0)
display(d1, d2)

    城市   类型               店名      点评     人均   口味   环境   服务
0   北京  私房菜           梧桐宇私房菜    45.0   80.0  7.3  7.3  7.1
1   北京  私房菜           小东北私房菜     1.0   35.0  6.9  6.9  6.9
2   北京  私房菜            辣家私房菜     1.0    NaN  6.9  6.9  6.9
3   北京  私房菜             鸿福天原     NaN    NaN  NaN  NaN  NaN
4   北京  私房菜  虾而美(北京)餐饮管理有限公司     NaN    NaN  NaN  NaN  NaN
5   北京  私房菜        热炼地带健身工作室     NaN    NaN  NaN  NaN  NaN
6   北京  私房菜         原点老板娘私房菜     2.0    NaN  6.9  6.9  6.9
7   北京  私房菜           常百味家常菜     NaN    NaN  NaN  NaN  NaN
8   北京  北京菜       紫光园(常营店)分店  4420.0   74.0  8.9  8.5  8.3
9   北京  北京菜         府膳(回龙观店)   894.0   86.0  8.6  8.8  8.4
10  北京  北京菜            京门小院儿    46.0   62.0  8.3  8.5  8.3
11  北京  北京菜    我家春饼(龙湖大兴天街店)  1098.0   44.0  8.0  8.2  7.6
12  北京  台湾菜    小明同学(当代商城店)分店   465.0   65.0  8.0  9.0  8.9
13  北京  台湾菜        东都台员(亦庄店)  1757.0   61.0  8.5  8.3  8.4
14  北京  北京菜   红莲烤鸭店(红莲北里店)分店  1320.0   72.0  7.0  6.4  6.2
15  北京  台湾菜          过路人台湾饭团     1.0    NaN  NaN  NaN  NaN
16  北京  家常菜   常赢三兄弟(陆港城总店)分店   305.0  110.0  8.7  8.5  8.0
17  北京  家常菜   太熟悉家常菜(右安门店)分店  3007.0   81.0  7.4  7.6  7.0
18  北京  家常菜              慈孝宫   349.0   88.0  7.2  7.3  6.8
19  北京  家常菜    中国医学科学院肿瘤医院食堂    18.0    NaN  6.6  6.7  6.7

    城市   类型               店名      点评     人均   口味   环境   服务
0   北京  私房菜           梧桐宇私房菜    45.0   80.0  7.3  7.3  7.1
1   北京  私房菜           小东北私房菜     1.0   35.0  6.9  6.9  6.9
2   北京  私房菜            辣家私房菜     1.0    0.0  6.9  6.9  6.9
3   北京  私房菜             鸿福天原     0.0    0.0  0.0  0.0  0.0
4   北京  私房菜  虾而美(北京)餐饮管理有限公司     0.0    0.0  0.0  0.0  0.0
5   北京  私房菜        热炼地带健身工作室     0.0    0.0  0.0  0.0  0.0
6   北京  私房菜         原点老板娘私房菜     2.0    0.0  6.9  6.9  6.9
7   北京  私房菜           常百味家常菜     0.0    0.0  0.0  0.0  0.0
8   北京  北京菜       紫光园(常营店)分店  4420.0   74.0  8.9  8.5  8.3
9   北京  北京菜         府膳(回龙观店)   894.0   86.0  8.6  8.8  8.4
10  北京  北京菜            京门小院儿    46.0   62.0  8.3  8.5  8.3
11  北京  北京菜    我家春饼(龙湖大兴天街店)  1098.0   44.0  8.0  8.2  7.6
12  北京  台湾菜    小明同学(当代商城店)分店   465.0   65.0  8.0  9.0  8.9
13  北京  台湾菜        东都台员(亦庄店)  1757.0   61.0  8.5  8.3  8.4
14  北京  北京菜   红莲烤鸭店(红莲北里店)分店  1320.0   72.0  7.0  6.4  6.2
15  北京  台湾菜          过路人台湾饭团     1.0    0.0  0.0  0.0  0.0
16  北京  家常菜   常赢三兄弟(陆港城总店)分店   305.0  110.0  8.7  8.5  8.0
17  北京  家常菜   太熟悉家常菜(右安门店)分店  3007.0   81.0  7.4  7.6  7.0
18  北京  家常菜              慈孝宫   349.0   88.0  7.2  7.3  6.8
19  北京  家常菜    中国医学科学院肿瘤医院食堂    18.0    0.0  6.6  6.7  6.7

In [6]:
d1.drop_duplicates().info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   城市      20 non-null     object
 1   类型      20 non-null     object
 2   店名      20 non-null     object
 3   点评      16 non-null     float64
 4   人均      12 non-null     float64
 5   口味      15 non-null     float64
 6   环境      15 non-null     float64
 7   服务      15 non-null     float64
dtypes: float64(5), object(3)
memory usage: 1.4+ KB

In [7]:
d3 = d1.iloc[1:12, :]
d4 = d1.iloc[8:, :18]
xlsx = pd.ExcelWriter(r'./cateringData.xlsx')
d3.to_excel(xlsx, sheet_name='d3')
d4.to_excel(xlsx, sheet_name='d4')
xlsx.close()
# with open('cateringData.xlsx','a+') as file:

display(d3, d4)

    城市   类型               店名      点评    人均   口味   环境   服务
1   北京  私房菜           小东北私房菜     1.0  35.0  6.9  6.9  6.9
2   北京  私房菜            辣家私房菜     1.0   NaN  6.9  6.9  6.9
3   北京  私房菜             鸿福天原     NaN   NaN  NaN  NaN  NaN
4   北京  私房菜  虾而美(北京)餐饮管理有限公司     NaN   NaN  NaN  NaN  NaN
5   北京  私房菜        热炼地带健身工作室     NaN   NaN  NaN  NaN  NaN
6   北京  私房菜         原点老板娘私房菜     2.0   NaN  6.9  6.9  6.9
7   北京  私房菜           常百味家常菜     NaN   NaN  NaN  NaN  NaN
8   北京  北京菜       紫光园(常营店)分店  4420.0  74.0  8.9  8.5  8.3
9   北京  北京菜         府膳(回龙观店)   894.0  86.0  8.6  8.8  8.4
10  北京  北京菜            京门小院儿    46.0  62.0  8.3  8.5  8.3
11  北京  北京菜    我家春饼(龙湖大兴天街店)  1098.0  44.0  8.0  8.2  7.6

    城市   类型              店名      点评     人均   口味   环境   服务
8   北京  北京菜      紫光园(常营店)分店  4420.0   74.0  8.9  8.5  8.3
9   北京  北京菜        府膳(回龙观店)   894.0   86.0  8.6  8.8  8.4
10  北京  北京菜           京门小院儿    46.0   62.0  8.3  8.5  8.3
11  北京  北京菜   我家春饼(龙湖大兴天街店)  1098.0   44.0  8.0  8.2  7.6
12  北京  台湾菜   小明同学(当代商城店)分店   465.0   65.0  8.0  9.0  8.9
13  北京  台湾菜       东都台员(亦庄店)  1757.0   61.0  8.5  8.3  8.4
14  北京  北京菜  红莲烤鸭店(红莲北里店)分店  1320.0   72.0  7.0  6.4  6.2
15  北京  台湾菜         过路人台湾饭团     1.0    NaN  NaN  NaN  NaN
16  北京  家常菜  常赢三兄弟(陆港城总店)分店   305.0  110.0  8.7  8.5  8.0
17  北京  家常菜  太熟悉家常菜(右安门店)分店  3007.0   81.0  7.4  7.6  7.0
18  北京  家常菜             慈孝宫   349.0   88.0  7.2  7.3  6.8
19  北京  家常菜   中国医学科学院肿瘤医院食堂    18.0    NaN  6.6  6.7  6.7

In [8]:
pd.merge(d3, d4, how='outer')

    城市   类型               店名      点评     人均   口味   环境   服务
0   北京  私房菜           小东北私房菜     1.0   35.0  6.9  6.9  6.9
1   北京  私房菜            辣家私房菜     1.0    NaN  6.9  6.9  6.9
2   北京  私房菜             鸿福天原     NaN    NaN  NaN  NaN  NaN
3   北京  私房菜  虾而美(北京)餐饮管理有限公司     NaN    NaN  NaN  NaN  NaN
4   北京  私房菜        热炼地带健身工作室     NaN    NaN  NaN  NaN  NaN
5   北京  私房菜         原点老板娘私房菜     2.0    NaN  6.9  6.9  6.9
6   北京  私房菜           常百味家常菜     NaN    NaN  NaN  NaN  NaN
7   北京  北京菜       紫光园(常营店)分店  4420.0   74.0  8.9  8.5  8.3
8   北京  北京菜         府膳(回龙观店)   894.0   86.0  8.6  8.8  8.4
9   北京  北京菜            京门小院儿    46.0   62.0  8.3  8.5  8.3
10  北京  北京菜    我家春饼(龙湖大兴天街店)  1098.0   44.0  8.0  8.2  7.6
11  北京  台湾菜    小明同学(当代商城店)分店   465.0   65.0  8.0  9.0  8.9
12  北京  台湾菜        东都台员(亦庄店)  1757.0   61.0  8.5  8.3  8.4
13  北京  北京菜   红莲烤鸭店(红莲北里店)分店  1320.0   72.0  7.0  6.4  6.2
14  北京  台湾菜          过路人台湾饭团     1.0    NaN  NaN  NaN  NaN
15  北京  家常菜   常赢三兄弟(陆港城总店)分店   305.0  110.0  8.7  8.5  8.0
16  北京  家常菜   太熟悉家常菜(右安门店)分店  3007.0   81.0  7.4  7.6  7.0
17  北京  家常菜              慈孝宫   349.0   88.0  7.2  7.3  6.8
18  北京  家常菜    中国医学科学院肿瘤医院食堂    18.0    NaN  6.6  6.7  6.7

In [9]:
pd.merge(d3, d4, on='服务')

,城市_x,类型_x,店名_x,点评_x,人均_x,口味_x,环境_x,服务,城市_y,类型_y,店名_y,点评_y,人均_y,口味_y,环境_y
0,北京,私房菜,鸿福天原,NaN,NaN,NaN,NaN,NaN,北京,台湾菜,过路人台湾饭团,1.0,NaN,NaN,NaN
1,北京,私房菜,虾而美(北京)餐饮管理有限公司,NaN,NaN,NaN,NaN,NaN,北京,台湾菜,过路人台湾饭团,1.0,NaN,NaN,NaN
2,北京,私房菜,热炼地带健身工作室,NaN,NaN,NaN,NaN,NaN,北京,台湾菜,过路人台湾饭团,1.0,NaN,NaN,NaN
3,北京,私房菜,常百味家常菜,NaN,NaN,NaN,NaN,NaN,北京,台湾菜,过路人台湾饭团,1.0,NaN,NaN,NaN
4,北京,北京菜,紫光园(常营店)分店,4420.0,74.0,8.9,8.5,8.3,北京,北京菜,紫光园(常营店)分店,4420.0,74.0,8.9,8.5
5,北京,北京菜,紫光园(常营店)分店,4420.0,74.0,8.9,8.5,8.3,北京,北京菜,京门小院儿,46.0,62.0,8.3,8.5
6,北京,北京菜,京门小院儿,46.0,62.0,8.3,8.5,8.3,北京,北京菜,紫光园(常营店)分店,4420.0,74.0,8.9,8.5
7,北京,北京菜,京门小院儿,46.0,62.0,8.3,8.5,8.3,北京,北京菜,京门小院儿,46.0,62.0,8.3,8.5
8,北京,北京菜,府膳(回龙观店),894.0,86.0,8.6,8.8,8.4,北京,北京菜,府膳(回龙观店),894.0,86.0,8.6,8.8
9,北京,北京菜,府膳(回龙观店),894.0,86.0,8.6,8.8,8.4,北京,台湾菜,东都台员(亦庄店),1757.0,61.0,8.5,8.3
10,北京,北京菜,我家春饼(龙湖大兴天街店),1098.0,44.0,8.0,8.2,7.6,北京,北京菜,我家春饼(龙湖大兴天街店),1098.0,44.0,8.0,8.2

In [10]:
pd.concat([d3, d4])

    城市   类型               店名      点评     人均   口味   环境   服务
1   北京  私房菜           小东北私房菜     1.0   35.0  6.9  6.9  6.9
2   北京  私房菜            辣家私房菜     1.0    NaN  6.9  6.9  6.9
3   北京  私房菜             鸿福天原     NaN    NaN  NaN  NaN  NaN
4   北京  私房菜  虾而美(北京)餐饮管理有限公司     NaN    NaN  NaN  NaN  NaN
5   北京  私房菜        热炼地带健身工作室     NaN    NaN  NaN  NaN  NaN
6   北京  私房菜         原点老板娘私房菜     2.0    NaN  6.9  6.9  6.9
7   北京  私房菜           常百味家常菜     NaN    NaN  NaN  NaN  NaN
8   北京  北京菜       紫光园(常营店)分店  4420.0   74.0  8.9  8.5  8.3
9   北京  北京菜         府膳(回龙观店)   894.0   86.0  8.6  8.8  8.4
10  北京  北京菜            京门小院儿    46.0   62.0  8.3  8.5  8.3
11  北京  北京菜    我家春饼(龙湖大兴天街店)  1098.0   44.0  8.0  8.2  7.6
8   北京  北京菜       紫光园(常营店)分店  4420.0   74.0  8.9  8.5  8.3
9   北京  北京菜         府膳(回龙观店)   894.0   86.0  8.6  8.8  8.4
10  北京  北京菜            京门小院儿    46.0   62.0  8.3  8.5  8.3
11  北京  北京菜    我家春饼(龙湖大兴天街店)  1098.0   44.0  8.0  8.2  7.6
12  北京  台湾菜    小明同学(当代商城店)分店   465.0   65.0  8.0  9.0  8.9
13  北京  台湾菜        东都台员(亦庄店)  1757.0   61.0  8.5  8.3  8.4
14  北京  北京菜   红莲烤鸭店(红莲北里店)分店  1320.0   72.0  7.0  6.4  6.2
15  北京  台湾菜          过路人台湾饭团     1.0    NaN  NaN  NaN  NaN
16  北京  家常菜   常赢三兄弟(陆港城总店)分店   305.0  110.0  8.7  8.5  8.0
17  北京  家常菜   太熟悉家常菜(右安门店)分店  3007.0   81.0  7.4  7.6  7.0
18  北京  家常菜              慈孝宫   349.0   88.0  7.2  7.3  6.8
19  北京  家常菜    中国医学科学院肿瘤医院食堂    18.0    NaN  6.6  6.7  6.7

In [11]:
pd.concat([d3, d4], ignore_index=True)

    城市   类型               店名      点评     人均   口味   环境   服务
0   北京  私房菜           小东北私房菜     1.0   35.0  6.9  6.9  6.9
1   北京  私房菜            辣家私房菜     1.0    NaN  6.9  6.9  6.9
2   北京  私房菜             鸿福天原     NaN    NaN  NaN  NaN  NaN
3   北京  私房菜  虾而美(北京)餐饮管理有限公司     NaN    NaN  NaN  NaN  NaN
4   北京  私房菜        热炼地带健身工作室     NaN    NaN  NaN  NaN  NaN
5   北京  私房菜         原点老板娘私房菜     2.0    NaN  6.9  6.9  6.9
6   北京  私房菜           常百味家常菜     NaN    NaN  NaN  NaN  NaN
7   北京  北京菜       紫光园(常营店)分店  4420.0   74.0  8.9  8.5  8.3
8   北京  北京菜         府膳(回龙观店)   894.0   86.0  8.6  8.8  8.4
9   北京  北京菜            京门小院儿    46.0   62.0  8.3  8.5  8.3
10  北京  北京菜    我家春饼(龙湖大兴天街店)  1098.0   44.0  8.0  8.2  7.6
11  北京  北京菜       紫光园(常营店)分店  4420.0   74.0  8.9  8.5  8.3
12  北京  北京菜         府膳(回龙观店)   894.0   86.0  8.6  8.8  8.4
13  北京  北京菜            京门小院儿    46.0   62.0  8.3  8.5  8.3
14  北京  北京菜    我家春饼(龙湖大兴天街店)  1098.0   44.0  8.0  8.2  7.6
15  北京  台湾菜    小明同学(当代商城店)分店   465.0   65.0  8.0  9.0  8.9
16  北京  台湾菜        东都台员(亦庄店)  1757.0   61.0  8.5  8.3  8.4
17  北京  北京菜   红莲烤鸭店(红莲北里店)分店  1320.0   72.0  7.0  6.4  6.2
18  北京  台湾菜          过路人台湾饭团     1.0    NaN  NaN  NaN  NaN
19  北京  家常菜   常赢三兄弟(陆港城总店)分店   305.0  110.0  8.7  8.5  8.0
20  北京  家常菜   太熟悉家常菜(右安门店)分店  3007.0   81.0  7.4  7.6  7.0
21  北京  家常菜              慈孝宫   349.0   88.0  7.2  7.3  6.8
22  北京  家常菜    中国医学科学院肿瘤医院食堂    18.0    NaN  6.6  6.7  6.7

In [12]:
d3.append({"城市": "南充", "类型": "火锅", "店名": "春意"},ignore_index=True).loc[11,::]

城市     南充
类型     火锅
店名     春意
点评    NaN
人均    NaN
口味    NaN
环境    NaN
服务    NaN
Name: 11, dtype: object

In [13]:
d3.describe()

                点评         人均        口味        环境        服务
count     7.000000   5.000000  7.000000  7.000000  7.000000
mean    923.142857  60.200000  7.785714  7.814286  7.614286
std    1611.314828  20.957099  0.872599  0.872599  0.717469
min       1.000000  35.000000  6.900000  6.900000  6.900000
25%       1.500000  44.000000  6.900000  6.900000  6.900000
50%      46.000000  62.000000  8.000000  8.200000  7.600000
75%     996.000000  74.000000  8.450000  8.500000  8.300000
max    4420.000000  86.000000  8.900000  8.800000  8.400000

In [14]:
d1.corr()

          点评        人均        口味        环境        服务
点评  1.000000  0.063225  0.464290  0.292114  0.233841
人均  0.063225  1.000000  0.282558  0.166539  0.037315
口味  0.464290  0.282558  1.000000  0.911361  0.869899
环境  0.292114  0.166539  0.911361  1.000000  0.961194
服务  0.233841  0.037315  0.869899  0.961194  1.000000

In [15]:
pd.DataFrame(d1.corr())

          点评        人均        口味        环境        服务
点评  1.000000  0.063225  0.464290  0.292114  0.233841
人均  0.063225  1.000000  0.282558  0.166539  0.037315
口味  0.464290  0.282558  1.000000  0.911361  0.869899
环境  0.292114  0.166539  0.911361  1.000000  0.961194
服务  0.233841  0.037315  0.869899  0.961194  1.000000