# 数据清洗

In [2]:
import pandas as pd

## 加载数据

In [3]:
import pandas as pd
from store.db.db_store import Mongo
mongo = Mongo()
raw_data = mongo.find(
    't2_job',
    columns_conditions={
        '_id': 0
    },
    limit=1000
)
raw_data = pd.DataFrame(raw_data)
raw_data.info()

,third_industry,job_name,job_area,salary,job_experience,job_degree,skill_list,welfare_list,boss_name,boss_title,...,pub_time,crawled_time,city,first_industry,industry,skills,welfares,salary_high,salary_low,second_industry
0,运营&运营&微信运营,交互图形工程师,北京·朝阳区·红庙,35-50K·14薪,5-10年,硕士,"[图形, GPU图形渲染, VTK, 机器学习]",[交通补助，补充医疗保险，员工旅游，节日福利，餐补，年终奖，带薪年假，零食下午茶，五险一金],闫女士,HR,...,2023-03-06,2023-03-07 10:08:03,北京,运营,微信运营,"图形, GPU图形渲染, VTK, 机器学习",交通补助，补充医疗保险，员工旅游，节日福利，餐补，年终奖，带薪年假，零食下午茶，五险一金,58330,40830,运营
1,运营&运营&微信运营,研发专家,北京·海淀区·北太平庄,30-60K,10年以上,本科,"[容器技术, 分布式技术, 微服务架构, SpringCloud, 平台架构, , ]",[],刘先生,研发专家,...,2023-03-07,2023-03-07 10:08:40,北京,运营,微信运营,"容器技术, 分布式技术, 微服务架构, SpringCloud, 平台架构",,60000,30000,运营
2,运营&运营&微信运营,web前端开发工程师,北京·朝阳区·望京,15-23K,3-5年,学历不限,"[Web前端, react]",[],宋女士,招聘者,...,2023-02-05,2023-03-07 10:09:13,北京,运营,微信运营,"Web前端, react",,23000,15000,运营
3,运营&运营&微信运营,网络工程师,上海,8-12K,1-3年,大专,"[交换机配置, CCNP证书, CCIE证书, 网络工程师证, , , , ]",[补充医疗保险，股票期权，交通补助，培养体系，加班补助，五险一金，节日福利，带薪年假，通讯补...,陆先生,部门经理,...,2023-02-24,2023-03-07 10:09:18,上海,运营,微信运营,"交换机配置, CCNP证书, CCIE证书, 网络工程师证",补充医疗保险，股票期权，交通补助，培养体系，加班补助，五险一金，节日福利，带薪年假，通讯补贴...,12000,8000,运营
4,运营&运营&微信运营,Unity游戏开发工程师（高级）,北京·东城区·安定门,20-30K,3-5年,本科,[游戏],[餐补，带薪年假，节日福利，定期体检，五险一金，员工旅游，全勤奖],茹女士,HR,...,2023-02-05,2023-03-07 10:09:27,北京,运营,微信运营,游戏,餐补，带薪年假，节日福利，定期体检，五险一金，员工旅游，全勤奖,30000,20000,运营

## 查看数据基本信息

In [4]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   third_industry    1000 non-null   object
 1   job_name          1000 non-null   object
 2   job_area          1000 non-null   object
 3   salary            1000 non-null   object
 4   job_experience    1000 non-null   object
 5   job_degree        1000 non-null   object
 6   skill_list        1000 non-null   object
 7   welfare_list      1000 non-null   object
 8   boss_name         1000 non-null   object
 9   boss_title        1000 non-null   object
 10  brand_logo        1000 non-null   object
 11  brand_name        1000 non-null   object
 12  brand_industry    1000 non-null   object
 13  brand_scale_name  1000 non-null   object
 14  brand_stage_name  817 non-null    object
 15  company_id        1000 non-null   object
 16  details           1000 non-null   object
 17  pub_time          1000 non-null   object
 18  crawled_time      1000 non-null   object
 19  city              1000 non-null   object
 20  first_industry    1000 non-null   object
 21  industry          1000 non-null   object
 22  skills            1000 non-null   object
 23  welfares          1000 non-null   object
 24  salary_high       1000 non-null   int64
 25  salary_low        1000 non-null   int64
 26  second_industry   1000 non-null   object
dtypes: int64(2), object(25)
memory usage: 211.1+ KB

In [ ]:
raw_data.drop_duplicates()

In [ ]:
raw_data.describe()

## 数据类型判断和转换

In [ ]:
raw_data.dtypes

In [ ]:
raw_data.skill_list = raw_data.skill_list.map(lambda x: ','.join(x) if x else None)
raw_data.skill_list

In [ ]:
raw_data.welfare_list = raw_data.welfare_list.map(lambda x: ','.join(x) if x else None)

In [5]:
raw_data.skill_list = raw_data.skill_list.map(lambda x: ','.join(x) if x else None)
raw_data.welfare_list = raw_data.welfare_list.map(lambda x: ','.join(x) if x else None)
raw_data.head(5)

,third_industry,job_name,job_area,salary,job_experience,job_degree,skill_list,welfare_list,boss_name,boss_title,...,pub_time,crawled_time,city,first_industry,industry,skills,welfares,salary_high,salary_low,second_industry
0,运营&运营&微信运营,交互图形工程师,北京·朝阳区·红庙,35-50K·14薪,5-10年,硕士,"图形,GPU图形渲染,VTK,机器学习",交通补助，补充医疗保险，员工旅游，节日福利，餐补，年终奖，带薪年假，零食下午茶，五险一金,闫女士,HR,...,2023-03-06,2023-03-07 10:08:03,北京,运营,微信运营,"图形, GPU图形渲染, VTK, 机器学习",交通补助，补充医疗保险，员工旅游，节日福利，餐补，年终奖，带薪年假，零食下午茶，五险一金,58330,40830,运营
1,运营&运营&微信运营,研发专家,北京·海淀区·北太平庄,30-60K,10年以上,本科,"容器技术,分布式技术,微服务架构,SpringCloud,平台架构,,",,刘先生,研发专家,...,2023-03-07,2023-03-07 10:08:40,北京,运营,微信运营,"容器技术, 分布式技术, 微服务架构, SpringCloud, 平台架构",,60000,30000,运营
2,运营&运营&微信运营,web前端开发工程师,北京·朝阳区·望京,15-23K,3-5年,学历不限,"Web前端,react",,宋女士,招聘者,...,2023-02-05,2023-03-07 10:09:13,北京,运营,微信运营,"Web前端, react",,23000,15000,运营
3,运营&运营&微信运营,网络工程师,上海,8-12K,1-3年,大专,"交换机配置,CCNP证书,CCIE证书,网络工程师证,,,,",补充医疗保险，股票期权，交通补助，培养体系，加班补助，五险一金，节日福利，带薪年假，通讯补贴...,陆先生,部门经理,...,2023-02-24,2023-03-07 10:09:18,上海,运营,微信运营,"交换机配置, CCNP证书, CCIE证书, 网络工程师证",补充医疗保险，股票期权，交通补助，培养体系，加班补助，五险一金，节日福利，带薪年假，通讯补贴...,12000,8000,运营
4,运营&运营&微信运营,Unity游戏开发工程师（高级）,北京·东城区·安定门,20-30K,3-5年,本科,游戏,餐补，带薪年假，节日福利，定期体检，五险一金，员工旅游，全勤奖,茹女士,HR,...,2023-02-05,2023-03-07 10:09:27,北京,运营,微信运营,游戏,餐补，带薪年假，节日福利，定期体检，五险一金，员工旅游，全勤奖,30000,20000,运营

## 数据去重

In [ ]:
raw_data.drop_duplicates()

In [ ]:
raw_data.salary

## 薪资转换函数

In [9]:
def simple_salary_transform(salary: str):
    """ 简单薪资区间转换 如： 12-17K  """
    low, raw_high = salary.split('-')
    high = raw_high[:-1]
    return int(low), int(high)

def salary_range_handle(salary: str):
    """" 薪资转换函数 """
    if '薪' in salary:
        s1, r_xin = salary.split('·')
        xin = int(r_xin[:-1])
        r_low, r_high = simple_salary_transform(s1)
        low, high = round(r_low * xin / 12, 2), round(r_high * xin / 12, 2)
    elif '元' in salary:
        s1 = salary.split('/')[0]
        r_low, r_high = simple_salary_transform(s1)
        low, high = round(r_low * 20 / 1000, 2), round(r_high * 20 // 1000, 2)
    else:
        low, high = simple_salary_transform(salary)
    return round(low * 1000), round(high * 1000)

## 增加字段 salary_low，salary_high

In [ ]:
# 效率较低
# x = list()
# y = list()
# for t in raw_data.salary.map(salary_range_handle):
#     t1, t2 = t
#     x.append(t1)
#     y.append(t2)
# raw_data['salary_low'], raw_data['salary_high'] = x, y
# raw_data['salary_low'], raw_data['salary_high']

In [10]:
salary = raw_data.salary.map(salary_range_handle)
salary

0      (40830, 58330)
1      (30000, 60000)
2      (15000, 23000)
3       (8000, 12000)
4      (20000, 30000)
            ...
995    (37500, 75000)
996    (21670, 43330)
997    (40830, 64170)
998    (13750, 27500)
999      (5000, 6000)
Name: salary, Length: 1000, dtype: object

### 切分元组，增加字段

In [11]:
raw_data['salary_low'] = salary.map(lambda x: x[0])
raw_data['salary_high'] = salary.map(lambda x: x[1])

In [12]:
raw_data.head()

,third_industry,job_name,job_area,salary,job_experience,job_degree,skill_list,welfare_list,boss_name,boss_title,...,pub_time,crawled_time,city,first_industry,industry,skills,welfares,salary_high,salary_low,second_industry
0,运营&运营&微信运营,交互图形工程师,北京·朝阳区·红庙,35-50K·14薪,5-10年,硕士,"图形,GPU图形渲染,VTK,机器学习",交通补助，补充医疗保险，员工旅游，节日福利，餐补，年终奖，带薪年假，零食下午茶，五险一金,闫女士,HR,...,2023-03-06,2023-03-07 10:08:03,北京,运营,微信运营,"图形, GPU图形渲染, VTK, 机器学习",交通补助，补充医疗保险，员工旅游，节日福利，餐补，年终奖，带薪年假，零食下午茶，五险一金,58330,40830,运营
1,运营&运营&微信运营,研发专家,北京·海淀区·北太平庄,30-60K,10年以上,本科,"容器技术,分布式技术,微服务架构,SpringCloud,平台架构,,",,刘先生,研发专家,...,2023-03-07,2023-03-07 10:08:40,北京,运营,微信运营,"容器技术, 分布式技术, 微服务架构, SpringCloud, 平台架构",,60000,30000,运营
2,运营&运营&微信运营,web前端开发工程师,北京·朝阳区·望京,15-23K,3-5年,学历不限,"Web前端,react",,宋女士,招聘者,...,2023-02-05,2023-03-07 10:09:13,北京,运营,微信运营,"Web前端, react",,23000,15000,运营
3,运营&运营&微信运营,网络工程师,上海,8-12K,1-3年,大专,"交换机配置,CCNP证书,CCIE证书,网络工程师证,,,,",补充医疗保险，股票期权，交通补助，培养体系，加班补助，五险一金，节日福利，带薪年假，通讯补贴...,陆先生,部门经理,...,2023-02-24,2023-03-07 10:09:18,上海,运营,微信运营,"交换机配置, CCNP证书, CCIE证书, 网络工程师证",补充医疗保险，股票期权，交通补助，培养体系，加班补助，五险一金，节日福利，带薪年假，通讯补贴...,12000,8000,运营
4,运营&运营&微信运营,Unity游戏开发工程师（高级）,北京·东城区·安定门,20-30K,3-5年,本科,游戏,餐补，带薪年假，节日福利，定期体检，五险一金，员工旅游，全勤奖,茹女士,HR,...,2023-02-05,2023-03-07 10:09:27,北京,运营,微信运营,游戏,餐补，带薪年假，节日福利，定期体检，五险一金，员工旅游，全勤奖,30000,20000,运营

### 查看按天的薪资

In [ ]:
raw_data.salary[raw_data.salary.map(lambda x: '天' in x)]

In [6]:
raw_data['salary_low'] = salary.map(lambda x: x[0])
raw_data['salary_high'] = salary.map(lambda x: x[1])
raw_data.head(5)

NameError: name 'salary' is not defined

In [ ]:
raw_data['fi'] = raw_data['third_industry'].map(lambda x: x.split('&')[0])
raw_data['si'] = raw_data['third_industry'].map(lambda x: x.split('&')[1])
raw_data['ti'] = raw_data['third_industry'].map(lambda x: x.split('&')[2])
raw_data.head(5)

In [ ]:
raw_data.groupby('fi')['fi'].count()

In [ ]:
raw_data.groupby(['fi', 'si']).count()

In [ ]:
raw_data.groupby(['fi', 'si', 'ti']).count().to_dict()

In [ ]:
raw_data.groupby(['fi', 'si', 'ti']).describe()

In [ ]:
df = raw_data.groupby(['fi', 'si', 'ti'])
df.count()

In [ ]:
df.max()

In [ ]:
df.min()

In [ ]:
df.mean()

In [ ]:
raw_data.salary_high.max()

In [ ]:
raw_data.groupby('fi').describe()

In [ ]:
raw_data.head(10)

In [ ]:
raw_data.salary_low[raw_data.fi.map(lambda x: x == '运营')].sum()

In [ ]:
raw_data.salary_low[raw_data.fi.map(lambda x: x == '运营')].count()

In [ ]:
raw_data.salary_low[raw_data.fi.map(lambda x: x == '运营')].mean()

In [ ]:
raw_data.salary_low[raw_data.fi.map(lambda x: x == '运营')].median()

## 统计热门行业

In [13]:

hot_industry = sorted([i for i in raw_data['fi'].value_counts().items()], key=lambda x: x[1], reverse=True)[:7]
hot_industry = {i[0]: i[1] for i in hot_industry}
hot_industry

KeyError: 'fi'

In [ ]:
for i in hot_industry:
    industry = i[0]
    raw_data.groupby('fi')

In [ ]:

# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_low','salary_high']].count(),
# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_low','salary_high']].median(),
# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_low','salary_high']].median(),
# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_low','salary_high']].mean()
# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_low','salary_high']].min()
# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_low','salary_high']]

In [ ]:
raw_data.head()

In [ ]:
raw_data['salary_avg'] = (raw_data['salary_low'] + raw_data['salary_high']) // 2
raw_data.dtypes

## 统计薪资区间

In [ ]:
# raw_data[raw_data.fi.map(lambda x: x == '运营')][['salary_avg']].max().to_dict()
# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_avg']].median()
# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_avg']].mean()
raw_data[raw_data.fi.map(lambda x: x == '运营')][['salary_avg']].min()
# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_avg']].count()

# raw_data[raw_data.fi.map(lambda  x : x == '运营')][['salary_avg']]

In [ ]:
raw_data['salary_avg'] = (raw_data['salary_low'] + raw_data['salary_high']) // 2
hls = {}
for i in hot_industry.keys():
    dt = {
        'min': int(raw_data[raw_data.fi.map(lambda x: x == i)][['salary_avg']].min()[0]),
        'mean': int(raw_data[raw_data.fi.map(lambda x: x == i)][['salary_avg']].mean()[0]),
        'max': int(raw_data[raw_data.fi.map(lambda x: x == i)][['salary_avg']].max()[0]),
        'median': int(raw_data[raw_data.fi.map(lambda x: x == i)][['salary_avg']].median()[0]),
    }
    hls[i] = dt
hls

In [340]:
raw_data['salary_avg'] = (raw_data['salary_low'] + raw_data['salary_high']) // 2
hls = {}
for i in hot_industry.keys():
    dt = {
        'min': int(raw_data[raw_data.fi.map(lambda x: x == i)][['salary_avg']].min()[0]),
        'mean': int(raw_data[raw_data.fi.map(lambda x: x == i)][['salary_avg']].mean()[0]),
        'max': int(raw_data[raw_data.fi.map(lambda x: x == i)][['salary_avg']].max()[0]),
        'median': int(raw_data[raw_data.fi.map(lambda x: x == i)][['salary_avg']].median()[0]),
    }
    hls[i] = dt
hls

{'销售': {'min': 1000, 'mean': 23833, 'max': 106250, 'median': 20000},
 '教育培训': {'min': 1500, 'mean': 22560, 'max': 100000, 'median': 19000},
 '市场': {'min': 1000, 'mean': 23397, 'max': 180000, 'median': 20000},
 '传媒': {'min': 250, 'mean': 21135, 'max': 297500, 'median': 17500},
 '金融': {'min': 1500, 'mean': 23088, 'max': 297500, 'median': 20000},
 '人事/财务/行政': {'min': 1500, 'mean': 23280, 'max': 180000, 'median': 20000},
 '运营': {'min': 1000, 'mean': 23402, 'max': 166665, 'median': 20000}}

In [346]:
salary_range = hls.items()
columns = list(map(lambda x: x[0], salary_range))
print(columns)
dt = {'columns': columns}
for line in salary_range:
    tt = line[1]
    for k in tt:
        dt[k] = dt.get(k, []) + [tt[k]]
print('dt', dt)

['销售', '教育培训', '市场', '传媒', '金融', '人事/财务/行政', '运营']
dt {'columns': ['销售', '教育培训', '市场', '传媒', '金融', '人事/财务/行政', '运营'], 'min': [1000, 1500, 1000, 250, 1500, 1500, 1000], 'mean': [23833, 22560, 23397, 21135, 23088, 23280, 23402], 'max': [106250, 100000, 180000, 297500, 297500, 180000, 166665], 'median': [20000, 19000, 20000, 17500, 20000, 20000, 20000]}

## 存储至Redis

In [ ]:

import ujson
from store.db.db_store import get_redis

redis = get_redis()
redis.set('hotIndustry:all', ujson.dumps(hot_industry))
redis.set('salaryRange:all', ujson.dumps(dt))

## 获取所有行业

In [ ]:
raw = mongo.find('industry_info', columns_conditions={"_id": 0, "third_industry_url": 0})
df_industries = pd.DataFrame(raw)
df_industries.head()

In [ ]:
rg = [i[0] for i in df_industries.groupby(['first_industry', 'second_industry', 'third_industry'])]

In [ ]:
for i in rg[:5]:
    print(i)

### 将行业装换为字典

In [ ]:
def generate_industries(seq: list):
    dt = {}
    for i in seq:
        if dt.get(i[0], None):
            if dt[i[0]].get(i[1], None):
                dt[i[0]][i[1]] = dt[i[0]][i[1]] + [i[2]]
            else:
                dt[i[0]][i[1]] = [i[2]]
        else:
            dt[i[0]] = {i[1]: [i[2]]}
    return dt

In [ ]:
dt = generate_industries(rg)
dt

### 将行业字典处理为前台需要格式数据

In [ ]:
def generate_options(dt):
    if isinstance(dt, list):
        return [{'value': i, 'label': i} for i in dt]
    rt = []
    for k in dt:
        rt.append({'value': k, 'label': k, "children": generate_options(dt.get(k))})
    return rt

In [ ]:
industry_data = generate_options(dt)
industry_data

In [ ]:
redis.set('fontEnd:industry_data',ujson.dumps(industry_data))

In [ ]:
raw = mongo.find('industry_info', columns_conditions={"_id": 0, "third_industry_url": 0})
df_industries = pd.DataFrame(raw)
df_industries.head()

In [ ]:
rg = [i[0] for i in df_industries.groupby(['first_industry', 'second_industry', 'third_industry'])]

In [ ]:
for i in rg[:5]:
    print(i)

### 将行业装换为字典

In [ ]:
def generate_industries(seq: list):
    dt = {}
    for i in seq:
        if dt.get(i[0], None):
            if dt[i[0]].get(i[1], None):
                dt[i[0]][i[1]] = dt[i[0]][i[1]] + [i[2]]
            else:
                dt[i[0]][i[1]] = [i[2]]
        else:
            dt[i[0]] = {i[1]: [i[2]]}
    return dt

In [ ]:
dt = generate_industries(rg)
dt

### 将行业字典处理为前台需要格式数据

In [ ]:
def generate_options(dt):
    if isinstance(dt, list):
        return [{'value': i, 'label': i} for i in dt]
    rt = []
    for k in dt:
        rt.append({'value': k, 'label': k, "children": generate_options(dt.get(k))})
    return rt

In [ ]:
industry_data = generate_options(dt)
industry_data

In [ ]:
redis.set('fontEnd:industry_data',ujson.dumps(industry_data))

In [365]:
raw = mongo.find('industry_info', columns_conditions={"_id": 0, "third_industry_url": 0})
df_industries = pd.DataFrame(raw)
df_industries.head()

  first_industry second_industry third_industry
0             技术            后端开发           Java
1             技术            后端开发            C++
2             技术            后端开发            PHP
3             技术            后端开发              C
4             技术            后端开发             C#

In [370]:
rg = [i[0] for i in df_industries.groupby(['first_industry', 'second_industry', 'third_industry'])]

In [371]:
for i in rg[:5]:
    print(i)

('产品', '产品经理', 'AI产品经理')
('产品', '产品经理', '产品专员')
('产品', '产品经理', '产品助理')
('产品', '产品经理', '产品经理')
('产品', '产品经理', '化妆品产品经理')

### 将行业装换为字典

In [398]:
def generate_industries(seq: list):
    dt = {}
    for i in seq:
        if dt.get(i[0], None):
            if dt[i[0]].get(i[1], None):
                dt[i[0]][i[1]] = dt[i[0]][i[1]] + [i[2]]
            else:
                dt[i[0]][i[1]] = [i[2]]
        else:
            dt[i[0]] = {i[1]: [i[2]]}
    return dt

In [405]:
dt = generate_industries(rg)
dt

{'产品': {'产品经理': ['AI产品经理',
   '产品专员',
   '产品助理',
   '产品经理',
   '化妆品产品经理',
   '数据产品经理',
   '游戏策划',
   '电商产品经理',
   '硬件产品经理',
   '移动产品经理'],
  '其他产品职位': ['其他产品职位'],
  '高端产品职位': ['游戏制作人', '高级产品管理岗']},
 '人事/财务/行政': {'人力资源': ['HRBP',
   '人力资源专员/助理',
   '人力资源总监',
   '人力资源经理/主管',
   '企业文化',
   '员工关系',
   '培训',
   '招聘',
   '组织发展',
   '薪酬绩效'],
  '其他职能职位': ['其他职能职位'],
  '法务': ['律师', '法务专员/助理', '法务总监', '法务经理/主管', '法律顾问'],
  '行政': ['前台', '后勤', '文员', '经理助理', '行政专员/助理', '行政总监', '行政经理/主管'],
  '财务': ['CFO',
   '会计',
   '出纳',
   '审计',
   '建筑/工程会计',
   '总账会计',
   '成本会计',
   '税务',
   '税务外勤会计',
   '结算会计',
   '统计员',
   '财务',
   '财务分析/财务BP',
   '财务总监/VP',
   '财务经理/主管',
   '财务顾问']},
 '传媒': {'公关媒介': ['公关媒介', '品牌公关', '媒介专员', '媒介策划', '媒介经理', '广告客户执行', '活动策划执行'],
  '其他传媒职位': ['其他传媒职位'],
  '广告': ['媒介合作',
   '媒介投放',
   '广告',
   '广告/会展项目经理',
   '广告创意设计',
   '广告制作',
   '广告审核',
   '广告文案',
   '广告设计',
   '策划经理',
   '美术指导'],
  '影视媒体': ['主持人/DJ',
   '主播',
   '主播助理',
   '儿童引导师',
   '制片人',
   '剧本杀主持人',
   '剧本杀编剧',
   '剪辑师',
   '化妆/造型/服装',
   '后期制作',
   '导演/编导',
   '带货主播',
   '录音/音效',
   '影视发行',
   '影视媒体',
   '影视特效',
   '影视策划',
   '摄影/摄像',
   '放映员',
   '演员/配音/模特',
   '灯光师',
   '经纪人',
   '编剧',
   '艺人助理',
   '视频编辑',
   '音频编辑'],
  '采编/写作/出版': ['作者/撰稿人', '出版发行', '印刷排版', '校对录入', '编辑', '记者/采编', '采编/写作/出版']},
 '供应链/物流': {'交通/运输': ['交通/运输',
   '代驾司机',
   '商务司机',
   '快递员',
   '无人机飞手',
   '网约车司机',
   '货运司机',
   '运输经理/主管',
   '配送员',
   '驾校教练'],
  '仓储': ['仓储', '仓库文员', '仓库管理员', '仓库经理', '配/理/拣/发货'],
  '其他供应链职位': ['其他供应链职位'],
  '物流': ['供应链专员',
   '供应链经理',
   '核销员',
   '水/空/陆运操作',
   '物流',
   '物流/仓储项目经理',
   '物流专员',
   '物流经理',
   '物流跟单',
   '物流运营',
   '调度员',
   '货运代理专员',
   '货运代理经理',
   '配送站长',
   '集装箱管理'],
  '高端供应链职位': ['供应链总监', '物流总监', '高端供应链职位']},
 '农/林/牧/渔': {'农业/林业': ['农业/林业技术员'], '畜牧/渔业': ['畜牧兽医', '禽畜/水产养殖技术员', '饲养员']},
 '医疗健康': {'临床试验': ['临床医学总监',
   '临床医学经理/专员',
   '临床协调员',
   '临床数据分析',
   '临床监查员',
   '临床项目经理'],
  '健康整形': ['健康整形', '康复治疗师', '营养师/健康管理师'],
  '其他医疗健康职位': ['其他医疗健康职位', '医学编辑'],
  '医生/医技': ['中医',
   '儿科医生',
   '全科医生',
   '其他医生职位',
   '内科医生',
   '医务管理',
   '医生助理',
   '口腔科医生',
   '外科医生',
   '妇产科医生',
   '幼儿园保健医',
   '放射科医生',
   '整形医生',
   '检验科医师',
   '病理科医生',
   '皮肤科医生',
   '眼科医生',
   '精神心理科医生',
   '耳鼻喉科医生',
   '药剂师',
   '超声科医生',
   '验光师',
   '麻醉科医生'],
  '医疗器械': ['医疗器械注册', '医疗器械生产/质量管理', '医疗器械研发', '试剂研发'],
  '护士/护理': ['导医', '护士', '护士长'],
  '生物制药': ['医疗产品技术支持',
   '医药研发',
   '医药项目经理',
   '生物信息工程师',
   '生物学研究人员',
   '细胞培养员',
   '药品注册',
   '药品生产',
   '药物分析',
   '药物合成'],
  '药店': ['执业药师/驻店药师', '药店店员', '药店店长']},
 '咨询/翻译/法律': {'其他咨询类职位': ['其他咨询/翻译类职位'],
  '咨询/调研': ['IT咨询顾问',
   '人力资源咨询顾问',
   '企业管理咨询',
   '其他咨询顾问',
   '咨询/调研',
   '咨询总监',
   '咨询经理',
   '咨询项目管理',
   '婚恋咨询师',
   '市场调研',
   '心理咨询师',
   '战略咨询',
   '数据分析师',
   '猎头顾问',
   '知识产权/专利/商标代理人',
   '财务咨询顾问'],
  '律师': ['专利律师', '事务所律师', '律师助理', '法务', '知识产权律师'],
  '翻译': ['俄语翻译',
   '其他语种翻译',
   '德语翻译',
   '日语翻译',
   '法语翻译',
   '英语翻译',
   '西班牙语翻译',
   '韩语/朝鲜语翻译']},
 '市场': {'会务会展': ['会务会展', '会展活动执行', '会展活动策划', '会议活动执行', '会议活动策划'],
  '公关媒介': ['公关媒介', '品牌公关', '媒介专员', '媒介策划', '媒介经理', '广告客户执行', '活动策划执行'],
  '其他市场职位': ['其他市场职位'],
  '市场/营销': ['APP推广',
   'SEM',
   'SEO',
   '信息流优化师',
   '商业数据分析',
   '商务渠道',
   '市场推广',
   '市场策划',
   '市场营销',
   '市场顾问',
   '活动策划',
   '海外市场',
   '游戏推广',
   '网络推广',
   '网络营销',
   '营销主管',
   '选址开发'],
  '广告': ['媒介合作',
   '媒介投放',
   '广告',
   '广告/会展项目经理',
   '广告创意设计',
   '广告制作',
   '广告审核',
   '广告文案',
   '广告设计',
   '策划经理',
   '美术指导'],
  '政府事务': ['企业党建', '政府关系', '政策研究', '社工'],
  '高端市场职位': ['CMO', '公关总监', '创意总监', '媒介总监', '市场总监', '高端市场职位']},
 '房地产/建筑': {'其他房地产职位': ['其他房地产职位'],
  '工程管理': ['工程监理',
   '工程造价',
   '工程预算',
   '建筑施工项目经理',
   '施工员',
   '施工安全员',
   '材料员',
   '测绘/测量',
   '资料员'],
  '建筑/规划设计': ['BIM工程师',
   '园林/景观设计',
   '土木/土建/结构工程师',
   '城市规划设计',
   '幕墙工程师',
   '建筑工程师',
   '建筑机电工程师',
   '建筑设计师',
   '弱电工程师',
   '暖通工程师',
   '消防工程师',
   '给排水工程师',
   '设计装修与市政建设'],
  '房地产规划开发': ['地产招投标', '地产项目管理', '房产评估师', '房地产策划', '房地产规划开发'],
  '物业管理': ['物业管理员', '物业经理', '综合维修工', '绿化工'],
  '装饰装修': ['室内设计', '装修项目经理', '软装设计师'],
  '高端房地产职位': ['地产招投标总监', '地产策划总监', '地产项目总监', '高端房地产职位']},
 '技术': {'人工智能': ['人工智能',
   '反欺诈/风控算法',
   '图像识别',
   '推荐算法',
   '搜索算法',
   '数据挖掘',
   '智能驾驶系统工程师',
   '机器学习',
   '深度学习',
   '算法工程师',
   '算法研究员',
   '自然语言处理',
   '语音识别'],
  '其他技术职位': ['其他技术职位'],
  '前端开发': ['Flash开发', '前端开发工程师'],
  '后端开发': ['.NET',
   'C',
   'C#',
   'C++',
   'Delphi',
   'Erlang',
   'GIS工程师',
   'Golang',
   'Hadoop',
   'Java',
   'Node.js',
   'PHP',
   'Perl',
   'Python',
   'Ruby',
   'VB',
   '全栈工程师',
   '后端开发',
   '数据采集',
   '语音/视频/图形开发'],
  '数据': ['ETL工程师', '数据', '数据仓库', '数据分析师', '数据开发', '数据挖掘', '数据架构师'],
  '测试': ['功能测试',
   '性能测试',
   '测试工程师',
   '测试开发',
   '渗透测试',
   '游戏测试',
   '硬件测试',
   '移动端测试',
   '自动化测试',
   '软件测试'],
  '电子/半导体': ['FAE',
   'IC验证工程师',
   '版图设计工程师',
   '电子工程师',
   '电气工程师',
   '电气设计工程师',
   '集成电路IC设计'],
  '硬件开发': ['ARM开发',
   'DSP开发',
   'FPGA开发',
   'PCB工艺',
   '光学工程师',
   '单片机',
   '射频工程师',
   '嵌入式',
   '电路设计',
   '硬件工程师',
   '系统集成',
   '自动化',
   '驱动开发'],
  '移动开发': ['Android',
   'Cocos',
   'Flash开发',
   'JavaScript',
   'U3D',
   'UE4',
   'iOS',
   '技术美术',
   '移动开发'],
  '运维/技术支持': ['DBA',
   'IT技术支持',
   '技术文档工程师',
   '系统安全',
   '系统工程师',
   '系统管理员',
   '网络安全',
   '网络工程师',
   '运维工程师',
   '运维开发工程师'],
  '通信': ['光传输工程师',
   '光网络工程师',
   '光通信工程师',
   '数据通信工程师',
   '无线/射频通信工程师',
   '有线传输工程师',
   '核心网工程师',
   '电信交换工程师',
   '电信网络工程师',
   '移动通信工程师',
   '通信技术工程师',
   '通信标准化工程师',
   '通信测试工程师',
   '通信电源工程师',
   '通信研发工程师',
   '通信设备工程师',
   '通信项目专员',
   '通信项目经理'],
  '销售技术支持': ['售前技术支持', '售后技术支持', '销售技术支持'],
  '项目管理': ['实施工程师', '实施顾问', '硬件项目经理', '需求分析工程师', '项目专员', '项目助理', '项目经理/主管'],
  '高端技术职位': ['CTO', '技术合伙人', '技术总监', '技术经理', '架构师', '测试经理', '运维总监', '高端技术职位']},
 '教育培训': {'IT培训': ['.NET培训讲师',
   'Android培训讲师',
   'C++培训讲师',
   'IT培训',
   'JAVA培训讲师',
   'PHP培训讲师',
   'UI设计培训讲师',
   'Unity 3D培训讲师',
   'Web前端培训讲师',
   'iOS培训讲师',
   '动漫培训讲师',
   '软件测试培训讲师'],
  '其他教育培训职位': ['其他教育培训职位'],
  '教师': ['体育教师/体育教练',
   '其他外语教师',
   '初中教师',
   '助教',
   '化学教师',
   '地理老师',
   '家教',
   '小学教师',
   '就业老师',
   '幼教',
   '感统训练教师',
   '托管老师',
   '教师',
   '数学教师',
   '文科教师',
   '日语教师',
   '早教老师',
   '物理教师',
   '理科教师',
   '生物教师',
   '美术教师',
   '英语教师',
   '语文教师',
   '音乐教师',
   '高中教师'],
  '教育产品研发': ['其他教育产品研发职位', '培训师', '培训研究', '培训策划', '教育产品研发', '课程编辑', '课程设计'],
  '教育行政': ['园长/副园长', '教务管理', '教学管理', '教育行政', '校长/副校长', '班主任/辅导员'],
  '特长培训': ['乐高教师',
   '乒乓球教练',
   '书法教师',
   '健身教练',
   '古筝教师',
   '吉他教师',
   '少儿编程老师',
   '播音主持教师',
   '教练',
   '机器人教师',
   '架子鼓老师',
   '武术教练',
   '游泳教练',
   '瑜伽老师',
   '篮球教练',
   '羽毛球教练',
   '舞蹈老师',
   '表演教师',
   '足球教练',
   '跆拳道教练',
   '轮滑教练',
   '钢琴教师'],
  '职业培训': ['培训师', '拓展培训', '财会培训讲师']},
 '旅游': {'其他旅游职位': ['其他旅游职位'],
  '旅游产品开发/策划': ['旅游产品开发/策划', '旅游产品经理', '旅游策划师'],
  '旅游服务': ['导游', '旅游服务', '签证专员', '计调', '讲解员', '预定票务']},
 '服务业': {'其他服务业职位': ['其他服务业职位', '网吧网管'],
  '婚礼/花艺': ['婚礼策划', '花艺师'],
  '安保/家政/维修': ['产后康复师',
   '保姆',
   '保安',
   '保安经理',
   '保洁',
   '保洁经理',
   '安检员',
   '家电维修',
   '手机维修',
   '护工',
   '押运员',
   '月嫂',
   '消防中控员',
   '电脑维修',
   '育婴师',
   '钟点工'],
  '宠物服务': ['宠物医生', '宠物美容'],
  '汽车服务': ['4S店店长/维修站长',
   '二手车评估师',
   '加油员',
   '汽车改装工程师',
   '汽车服务顾问',
   '汽车查勘定损',
   '汽车维修',
   '汽车美容',
   '洗车工'],
  '美容保健': ['养发师',
   '化妆师',
   '发型师',
   '按摩师',
   '理疗师',
   '纹绣师',
   '美体师',
   '美发助理/学徒',
   '美容师',
   '美容店长',
   '美甲师',
   '美睫师',
   '足疗师',
   '采耳师',
   '针灸推拿'],
  '运动健身': ['健身', '健身教练', '救生员', '游泳教练', '瑜伽老师', '舞蹈老师'],
  '酒店': ['客房服务员', '客房经理', '民宿管家', '礼仪/迎宾/接待', '酒店前厅经理', '酒店前台', '酒店经理'],
  '零售': ['促销员', '卖场经理', '导购', '店员/营业员', '理货员', '督导/巡店', '门店店长', '防损员', '陈列员'],
  '餐饮': ['中餐厨师',
   '传菜员',
   '凉菜厨师',
   '前厅经理/领班',
   '厨师',
   '厨师长',
   '后厨',
   '咖啡师',
   '奶茶店店员',
   '收银',
   '日料厨师',
   '服务员',
   '水台',
   '洗碗工',
   '烧烤师傅',
   '茶艺师',
   '蛋糕/裱花师',
   '行政总厨',
   '西餐厨师',
   '调酒师',
   '送餐员',
   '配菜打荷',
   '面包/烘焙师',
   '面点师',
   '餐饮',
   '餐饮储备店长/干部',
   '餐饮学徒',
   '餐饮店长']},
 '生产制造': {'其他生产制造职位': ['其他生产制造职位'],
  '化工': ['化妆品研发', '化工工程师', '化工项目经理', '实验室技术员', '涂料研发', '食品/饮料研发'],
  '技工/普工': ['切割工',
   '包装工',
   '叉车工',
   '喷塑工',
   '学徒工',
   '弱电工',
   '折弯工',
   '抛光工',
   '挖掘机司机',
   '搬运工/装卸工',
   '普工/操作工',
   '木工',
   '机修工',
   '样衣工',
   '模具工',
   '氩弧焊工',
   '水电工',
   '油漆工',
   '注塑工',
   '焊工',
   '电工',
   '电梯工',
   '电镀工',
   '磨工',
   '空调工',
   '组装工',
   '缝纫工',
   '裁剪工',
   '车工',
   '钣金工',
   '钳工',
   '钻工',
   '铆工',
   '铣工',
   '铲车司机',
   '锅炉工'],
  '新能源': ['充电桩设计', '电机工程师', '电池工程师', '线束设计'],
  '服装/纺织/皮革': ['打样/制版', '服装/纺织/皮革跟单', '服装/纺织设计', '量体师', '面料辅料开发'],
  '机械设计/制造': ['CNC/数控',
   '冲压工程师',
   '夹具工程师',
   '工业工程师(IE)',
   '工艺工程师',
   '机械制图员',
   '机械工程师',
   '机械结构工程师',
   '机械维修/保养',
   '机械设备工程师',
   '机械设计/制造',
   '机电工程师',
   '材料工程师',
   '模具工程师',
   '注塑工程师',
   '液压工程师',
   '热设计工程师',
   '焊接工程师',
   '铸造/锻造工程师'],
  '汽车制造': ['内外饰设计工程师',
   '动力系统工程师',
   '底盘工程师',
   '总装工程师',
   '汽车电子工程师',
   '汽车设计',
   '汽车零部件设计',
   '汽车项目管理',
   '车身/造型设计'],
  '环保': ['EHS工程师', '环保工程师', '环境检测员', '环评工程师', '碳排放管理师'],
  '生产营运': ['厂务',
   '厂长',
   '生产总监',
   '生产文员',
   '生产组长/拉长',
   '生产营运',
   '生产计划/物料管理(PMC)',
   '生产设备管理员',
   '车间主任'],
  '能源/地质': ['光伏系统工程师', '地质工程师', '水利工程师', '风电运维工程师'],
  '质量安全': ['产品认证工程师',
   '体系审核员',
   '体系工程师',
   '可靠度工程师',
   '失效分析工程师',
   '安全评价师',
   '汽车质量工程师',
   '生产安全员',
   '计量工程师',
   '质检员',
   '质量管理/测试']},
 '设计': {'其他设计职位': ['其他设计职位'],
  '游戏设计': ['游戏主美术',
   '游戏动作',
   '游戏场景',
   '游戏数值策划',
   '游戏特效',
   '游戏界面设计师',
   '游戏角色',
   '系统策划'],
  '用户研究': ['UX设计师', '数据分析师', '用户研究员', '用户研究总监', '用户研究经理'],
  '视觉/交互设计': ['3D设计师',
   'CAD设计/制图',
   'Flash设计师',
   'UI设计师',
   '交互设计师',
   '人像修图师',
   '动画设计',
   '包装设计',
   '原画师',
   '多媒体设计师',
   '平面设计',
   '广告设计',
   '插画师',
   '漫画师',
   '网页设计师',
   '美工',
   '视觉设计',
   '视觉设计师',
   '设计师助理'],
  '非视觉设计': ['室内设计',
   '家具设计',
   '家居设计',
   '展览/展示设计',
   '工业设计',
   '服装/纺织设计',
   '橱柜设计',
   '照明设计',
   '珠宝设计',
   '陈列设计',
   '非视觉设计'],
  '高端设计职位': ['视觉设计总监', '设计总监', '设计经理/主管', '高端设计职位']},
 '运营': {'其他运营职位': ['其他运营职位'],
  '客服': ['咨询热线/呼叫中心客服',
   '售前客服',
   '售后客服',
   '客服专员',
   '客服主管',
   '客服经理',
   '电话客服',
   '网络客服'],
  '编辑': ['主编/副主编', '文案编辑', '编辑', '网站编辑', '采编'],
  '运营': ['亚马逊产品开发',
   '亚马逊运营',
   '产品运营',
   '京东运营',
   '内容审核',
   '内容运营',
   '品类运营',
   '商家运营',
   '国内电商运营',
   '天猫运营',
   '微信运营',
   '拼多多运营',
   '数据/策略运营',
   '数据标注/AI训练师',
   '新媒体运营',
   '活动运营',
   '淘宝运营',
   '游戏运营',
   '用户运营',
   '直播运营',
   '社区运营',
   '线下拓展运营',
   '网站运营',
   '视频运营',
   '跨境电商运营',
   '车辆运营',
   '运营',
   '运营助理/专员',
   '速卖通运营',
   '阿里国际站运营'],
  '高端运营职位': ['COO', '客服总监', '运营总监', '运营经理/主管', '高端运营职位']},
 '采购/贸易': {'其他采购/贸易职位': ['其他采购/贸易类职位'],
  '进出口贸易': ['单证员', '报关/报检员', '贸易跟单', '进出口贸易'],
  '采购': ['买手',
   '供应商质量工程师',
   '商品经理',
   '投标专员',
   '招标专员',
   '采购',
   '采购专员/助理',
   '采购工程师',
   '采购总监',
   '采购经理/主管']},
 '金融': {'中后台': ['催收员', '合规稽查', '法务', '清算', '资产评估', '资信评估', '金融产品经理', '风控'],
  '互联网金融': ['互联网金融'],
  '保险': ['保险理赔', '保险精算师'],
  '其他金融职位': ['其他金融职位'],
  '投融资': ['其他投融资职位',
   '并购',
   '投后管理',
   '投融资',
   '投资助理',
   '投资总监/VP',
   '投资经理',
   '投资者关系/证券事务代表',
   '融资',
   '行业研究'],
  '证券/基金/期货': ['买方分析师',
   '卖方分析师',
   '基金经理',
   '投资银行业务',
   '证券/基金/期货',
   '证券交易员',
   '量化研究员'],
  '银行': ['信贷专员', '客户经理', '柜员', '银行', '银行大堂经理']},
 '销售': {'其他销售职位': ['其他销售职位'],
  '医疗销售': ['健康顾问', '医疗器械销售', '医疗销售', '医美咨询', '医药代表', '口腔咨询师'],
  '外贸销售': ['外贸业务员', '外贸经理'],
  '广告/会展销售': ['会展活动销售', '会议活动销售', '广告销售'],
  '房地产销售/招商': ['地产中介', '房地产销售/招商', '房地产销售总监', '物业招商管理', '置业顾问'],
  '服务业销售': ['会籍顾问', '化妆品导购', '旅游顾问', '服装导购', '珠宝销售', '瘦身顾问', '美容顾问'],
  '汽车销售': ['汽车配件销售', '汽车销售'],
  '课程销售': ['招生顾问', '留学顾问', '课程顾问'],
  '金融销售': ['保险顾问', '信用卡销售', '理财顾问', '证券经纪人'],
  '销售': ['BD经理',
   '代理商销售',
   '大客户代表',
   '客户代表',
   '客户经理',
   '渠道销售',
   '电话销售',
   '网络销售',
   '销售专员',
   '销售工程师',
   '销售顾问'],
  '销售管理': ['区域总监', '团队经理', '城市经理', '销售VP', '销售总监', '销售经理'],
  '销售行政/商务': ['商务专员', '商务总监', '商务经理', '客户成功', '销售助理', '销售运营']},
 '高级管理': {'高级管理职位': ['分公司/代表处负责人',
   '副总裁/副总经理/VP',
   '区域负责人(辖多个分公司)',
   '总助/CEO助理/董事长助理',
   '总裁/总经理/CEO',
   '联合创始人',
   '董事会秘书',
   '高级管理职位']}}

### 将行业字典处理为前台需要格式数据

In [433]:
def generate_options(dt):
    if isinstance(dt, list):
        return [{'value': i, 'label': i} for i in dt]
    rt = []
    for k in dt:
        rt.append({'value': k, 'label': k, "children": generate_options(dt.get(k))})
    return rt

In [435]:
industry_data = generate_options(dt)
industry_data

[{'value': '产品',
  'label': '产品',
  'children': [{'value': '产品经理',
    'label': '产品经理',
    'children': [{'value': 'AI产品经理', 'label': 'AI产品经理'},
     {'value': '产品专员', 'label': '产品专员'},
     {'value': '产品助理', 'label': '产品助理'},
     {'value': '产品经理', 'label': '产品经理'},
     {'value': '化妆品产品经理', 'label': '化妆品产品经理'},
     {'value': '数据产品经理', 'label': '数据产品经理'},
     {'value': '游戏策划', 'label': '游戏策划'},
     {'value': '电商产品经理', 'label': '电商产品经理'},
     {'value': '硬件产品经理', 'label': '硬件产品经理'},
     {'value': '移动产品经理', 'label': '移动产品经理'}]},
   {'value': '其他产品职位',
    'label': '其他产品职位',
    'children': [{'value': '其他产品职位', 'label': '其他产品职位'}]},
   {'value': '高端产品职位',
    'label': '高端产品职位',
    'children': [{'value': '游戏制作人', 'label': '游戏制作人'},
     {'value': '高级产品管理岗', 'label': '高级产品管理岗'}]}]},
 {'value': '人事/财务/行政',
  'label': '人事/财务/行政',
  'children': [{'value': '人力资源',
    'label': '人力资源',
    'children': [{'value': 'HRBP', 'label': 'HRBP'},
     {'value': '人力资源专员/助理', 'label': '人力资源专员/助理'},
     {'value': '人力资源总监', 'label': '人力资源总监'},
     {'value': '人力资源经理/主管', 'label': '人力资源经理/主管'},
     {'value': '企业文化', 'label': '企业文化'},
     {'value': '员工关系', 'label': '员工关系'},
     {'value': '培训', 'label': '培训'},
     {'value': '招聘', 'label': '招聘'},
     {'value': '组织发展', 'label': '组织发展'},
     {'value': '薪酬绩效', 'label': '薪酬绩效'}]},
   {'value': '其他职能职位',
    'label': '其他职能职位',
    'children': [{'value': '其他职能职位', 'label': '其他职能职位'}]},
   {'value': '法务',
    'label': '法务',
    'children': [{'value': '律师', 'label': '律师'},
     {'value': '法务专员/助理', 'label': '法务专员/助理'},
     {'value': '法务总监', 'label': '法务总监'},
     {'value': '法务经理/主管', 'label': '法务经理/主管'},
     {'value': '法律顾问', 'label': '法律顾问'}]},
   {'value': '行政',
    'label': '行政',
    'children': [{'value': '前台', 'label': '前台'},
     {'value': '后勤', 'label': '后勤'},
     {'value': '文员', 'label': '文员'},
     {'value': '经理助理', 'label': '经理助理'},
     {'value': '行政专员/助理', 'label': '行政专员/助理'},
     {'value': '行政总监', 'label': '行政总监'},
     {'value': '行政经理/主管', 'label': '行政经理/主管'}]},
   {'value': '财务',
    'label': '财务',
    'children': [{'value': 'CFO', 'label': 'CFO'},
     {'value': '会计', 'label': '会计'},
     {'value': '出纳', 'label': '出纳'},
     {'value': '审计', 'label': '审计'},
     {'value': '建筑/工程会计', 'label': '建筑/工程会计'},
     {'value': '总账会计', 'label': '总账会计'},
     {'value': '成本会计', 'label': '成本会计'},
     {'value': '税务', 'label': '税务'},
     {'value': '税务外勤会计', 'label': '税务外勤会计'},
     {'value': '结算会计', 'label': '结算会计'},
     {'value': '统计员', 'label': '统计员'},
     {'value': '财务', 'label': '财务'},
     {'value': '财务分析/财务BP', 'label': '财务分析/财务BP'},
     {'value': '财务总监/VP', 'label': '财务总监/VP'},
     {'value': '财务经理/主管', 'label': '财务经理/主管'},
     {'value': '财务顾问', 'label': '财务顾问'}]}]},
 {'value': '传媒',
  'label': '传媒',
  'children': [{'value': '公关媒介',
    'label': '公关媒介',
    'children': [{'value': '公关媒介', 'label': '公关媒介'},
     {'value': '品牌公关', 'label': '品牌公关'},
     {'value': '媒介专员', 'label': '媒介专员'},
     {'value': '媒介策划', 'label': '媒介策划'},
     {'value': '媒介经理', 'label': '媒介经理'},
     {'value': '广告客户执行', 'label': '广告客户执行'},
     {'value': '活动策划执行', 'label': '活动策划执行'}]},
   {'value': '其他传媒职位',
    'label': '其他传媒职位',
    'children': [{'value': '其他传媒职位', 'label': '其他传媒职位'}]},
   {'value': '广告',
    'label': '广告',
    'children': [{'value': '媒介合作', 'label': '媒介合作'},
     {'value': '媒介投放', 'label': '媒介投放'},
     {'value': '广告', 'label': '广告'},
     {'value': '广告/会展项目经理', 'label': '广告/会展项目经理'},
     {'value': '广告创意设计', 'label': '广告创意设计'},
     {'value': '广告制作', 'label': '广告制作'},
     {'value': '广告审核', 'label': '广告审核'},
     {'value': '广告文案', 'label': '广告文案'},
     {'value': '广告设计', 'label': '广告设计'},
     {'value': '策划经理', 'label': '策划经理'},
     {'value': '美术指导', 'label': '美术指导'}]},
   {'value': '影视媒体',
    'label': '影视媒体',
    'children': [{'value': '主持人/DJ', 'label': '主持人/DJ'},
     {'value': '主播', 'label': '主播'},
     {'value': '主播助理', 'label': '主播助理'},
     {'value': '儿童引导师', 'label': '儿童引导师'},
     {'value': '制片人', 'label': '制片人'},
     {'value': '剧本杀主持人', 'label': '剧本杀主持人'},
     {'value': '剧本杀编剧', 'label': '剧本杀编剧'},
     {'value': '剪辑师', 'label': '剪辑师'},
     {'value': '化妆/造型/服装', 'label': '化妆/造型/服装'},
     {'value': '后期制作', 'label': '后期制作'},
     {'value': '导演/编导', 'label': '导演/编导'},
     {'value': '带货主播', 'label': '带货主播'},
     {'value': '录音/音效', 'label': '录音/音效'},
     {'value': '影视发行', 'label': '影视发行'},
     {'value': '影视媒体', 'label': '影视媒体'},
     {'value': '影视特效', 'label': '影视特效'},
     {'value': '影视策划', 'label': '影视策划'},
     {'value': '摄影/摄像', 'label': '摄影/摄像'},
     {'value': '放映员', 'label': '放映员'},
     {'value': '演员/配音/模特', 'label': '演员/配音/模特'},
     {'value': '灯光师', 'label': '灯光师'},
     {'value': '经纪人', 'label': '经纪人'},
     {'value': '编剧', 'label': '编剧'},
     {'value': '艺人助理', 'label': '艺人助理'},
     {'value': '视频编辑', 'label': '视频编辑'},
     {'value': '音频编辑', 'label': '音频编辑'}]},
   {'value': '采编/写作/出版',
    'label': '采编/写作/出版',
    'children': [{'value': '作者/撰稿人', 'label': '作者/撰稿人'},
     {'value': '出版发行', 'label': '出版发行'},
     {'value': '印刷排版', 'label': '印刷排版'},
     {'value': '校对录入', 'label': '校对录入'},
     {'value': '编辑', 'label': '编辑'},
     {'value': '记者/采编', 'label': '记者/采编'},
     {'value': '采编/写作/出版', 'label': '采编/写作/出版'}]}]},
 {'value': '供应链/物流',
  'label': '供应链/物流',
  'children': [{'value': '交通/运输',
    'label': '交通/运输',
    'children': [{'value': '交通/运输', 'label': '交通/运输'},
     {'value': '代驾司机', 'label': '代驾司机'},
     {'value': '商务司机', 'label': '商务司机'},
     {'value': '快递员', 'label': '快递员'},
     {'value': '无人机飞手', 'label': '无人机飞手'},
     {'value': '网约车司机', 'label': '网约车司机'},
     {'value': '货运司机', 'label': '货运司机'},
     {'value': '运输经理/主管', 'label': '运输经理/主管'},
     {'value': '配送员', 'label': '配送员'},
     {'value': '驾校教练', 'label': '驾校教练'}]},
   {'value': '仓储',
    'label': '仓储',
    'children': [{'value': '仓储', 'label': '仓储'},
     {'value': '仓库文员', 'label': '仓库文员'},
     {'value': '仓库管理员', 'label': '仓库管理员'},
     {'value': '仓库经理', 'label': '仓库经理'},
     {'value': '配/理/拣/发货', 'label': '配/理/拣/发货'}]},
   {'value': '其他供应链职位',
    'label': '其他供应链职位',
    'children': [{'value': '其他供应链职位', 'label': '其他供应链职位'}]},
   {'value': '物流',
    'label': '物流',
    'children': [{'value': '供应链专员', 'label': '供应链专员'},
     {'value': '供应链经理', 'label': '供应链经理'},
     {'value': '核销员', 'label': '核销员'},
     {'value': '水/空/陆运操作', 'label': '水/空/陆运操作'},
     {'value': '物流', 'label': '物流'},
     {'value': '物流/仓储项目经理', 'label': '物流/仓储项目经理'},
     {'value': '物流专员', 'label': '物流专员'},
     {'value': '物流经理', 'label': '物流经理'},
     {'value': '物流跟单', 'label': '物流跟单'},
     {'value': '物流运营', 'label': '物流运营'},
     {'value': '调度员', 'label': '调度员'},
     {'value': '货运代理专员', 'label': '货运代理专员'},
     {'value': '货运代理经理', 'label': '货运代理经理'},
     {'value': '配送站长', 'label': '配送站长'},
     {'value': '集装箱管理', 'label': '集装箱管理'}]},
   {'value': '高端供应链职位',
    'label': '高端供应链职位',
    'children': [{'value': '供应链总监', 'label': '供应链总监'},
     {'value': '物流总监', 'label': '物流总监'},
     {'value': '高端供应链职位', 'label': '高端供应链职位'}]}]},
 {'value': '农/林/牧/渔',
  'label': '农/林/牧/渔',
  'children': [{'value': '农业/林业',
    'label': '农业/林业',
    'children': [{'value': '农业/林业技术员', 'label': '农业/林业技术员'}]},
   {'value': '畜牧/渔业',
    'label': '畜牧/渔业',
    'children': [{'value': '畜牧兽医', 'label': '畜牧兽医'},
     {'value': '禽畜/水产养殖技术员', 'label': '禽畜/水产养殖技术员'},
     {'value': '饲养员', 'label': '饲养员'}]}]},
 {'value': '医疗健康',
  'label': '医疗健康',
  'children': [{'value': '临床试验',
    'label': '临床试验',
    'children': [{'value': '临床医学总监', 'label': '临床医学总监'},
     {'value': '临床医学经理/专员', 'label': '临床医学经理/专员'},
     {'value': '临床协调员', 'label': '临床协调员'},
     {'value': '临床数据分析', 'label': '临床数据分析'},
     {'value': '临床监查员', 'label': '临床监查员'},
     {'value': '临床项目经理', 'label': '临床项目经理'}]},
   {'value': '健康整形',
    'label': '健康整形',
    'children': [{'value': '健康整形', 'label': '健康整形'},
     {'value': '康复治疗师', 'label': '康复治疗师'},
     {'value': '营养师/健康管理师', 'label': '营养师/健康管理师'}]},
   {'value': '其他医疗健康职位',
    'label': '其他医疗健康职位',
    'children': [{'value': '其他医疗健康职位', 'label': '其他医疗健康职位'},
     {'value': '医学编辑', 'label': '医学编辑'}]},
   {'value': '医生/医技',
    'label': '医生/医技',
    'children': [{'value': '中医', 'label': '中医'},
     {'value': '儿科医生', 'label': '儿科医生'},
     {'value': '全科医生', 'label': '全科医生'},
     {'value': '其他医生职位', 'label': '其他医生职位'},
     {'value': '内科医生', 'label': '内科医生'},
     {'value': '医务管理', 'label': '医务管理'},
     {'value': '医生助理', 'label': '医生助理'},
     {'value': '口腔科医生', 'label': '口腔科医生'},
     {'value': '外科医生', 'label': '外科医生'},
     {'value': '妇产科医生', 'label': '妇产科医生'},
     {'value': '幼儿园保健医', 'label': '幼儿园保健医'},
     {'value': '放射科医生', 'label': '放射科医生'},
     {'value': '整形医生', 'label': '整形医生'},
     {'value': '检验科医师', 'label': '检验科医师'},
     {'value': '病理科医生', 'label': '病理科医生'},
     {'value': '皮肤科医生', 'label': '皮肤科医生'},
     {'value': '眼科医生', 'label': '眼科医生'},
     {'value': '精神心理科医生', 'label': '精神心理科医生'},
     {'value': '耳鼻喉科医生', 'label': '耳鼻喉科医生'},
     {'value': '药剂师', 'label': '药剂师'},
     {'value': '超声科医生', 'label': '超声科医生'},
     {'value': '验光师', 'label': '验光师'},
     {'value': '麻醉科医生', 'label': '麻醉科医生'}]},
   {'value': '医疗器械',
    'label': '医疗器械',
    'children': [{'value': '医疗器械注册', 'label': '医疗器械注册'},
     {'value': '医疗器械生产/质量管理', 'label': '医疗器械生产/质量管理'},
     {'value': '医疗器械研发', 'label': '医疗器械研发'},
     {'value': '试剂研发', 'label': '试剂研发'}]},
   {'value': '护士/护理',
    'label': '护士/护理',
    'children': [{'value': '导医', 'label': '导医'},
     {'value': '护士', 'label': '护士'},
     {'value': '护士长', 'label': '护士长'}]},
   {'value': '生物制药',
    'label': '生物制药',
    'children': [{'value': '医疗产品技术支持', 'label': '医疗产品技术支持'},
     {'value': '医药研发', 'label': '医药研发'},
     {'value': '医药项目经理', 'label': '医药项目经理'},
     {'value': '生物信息工程师', 'label': '生物信息工程师'},
     {'value': '生物学研究人员', 'label': '生物学研究人员'},
     {'value': '细胞培养员', 'label': '细胞培养员'},
     {'value': '药品注册', 'label': '药品注册'},
     {'value': '药品生产', 'label': '药品生产'},
     {'value': '药物分析', 'label': '药物分析'},
     {'value': '药物合成', 'label': '药物合成'}]},
   {'value': '药店',
    'label': '药店',
    'children': [{'value': '执业药师/驻店药师', 'label': '执业药师/驻店药师'},
     {'value': '药店店员', 'label': '药店店员'},
     {'value': '药店店长', 'label': '药店店长'}]}]},
 {'value': '咨询/翻译/法律',
  'label': '咨询/翻译/法律',
  'children': [{'value': '其他咨询类职位',
    'label': '其他咨询类职位',
    'children': [{'value': '其他咨询/翻译类职位', 'label': '其他咨询/翻译类职位'}]},
   {'value': '咨询/调研',
    'label': '咨询/调研',
    'children': [{'value': 'IT咨询顾问', 'label': 'IT咨询顾问'},
     {'value': '人力资源咨询顾问', 'label': '人力资源咨询顾问'},
     {'value': '企业管理咨询', 'label': '企业管理咨询'},
     {'value': '其他咨询顾问', 'label': '其他咨询顾问'},
     {'value': '咨询/调研', 'label': '咨询/调研'},
     {'value': '咨询总监', 'label': '咨询总监'},
     {'value': '咨询经理', 'label': '咨询经理'},
     {'value': '咨询项目管理', 'label': '咨询项目管理'},
     {'value': '婚恋咨询师', 'label': '婚恋咨询师'},
     {'value': '市场调研', 'label': '市场调研'},
     {'value': '心理咨询师', 'label': '心理咨询师'},
     {'value': '战略咨询', 'label': '战略咨询'},
     {'value': '数据分析师', 'label': '数据分析师'},
     {'value': '猎头顾问', 'label': '猎头顾问'},
     {'value': '知识产权/专利/商标代理人', 'label': '知识产权/专利/商标代理人'},
     {'value': '财务咨询顾问', 'label': '财务咨询顾问'}]},
   {'value': '律师',
    'label': '律师',
    'children': [{'value': '专利律师', 'label': '专利律师'},
     {'value': '事务所律师', 'label': '事务所律师'},
     {'value': '律师助理', 'label': '律师助理'},
     {'value': '法务', 'label': '法务'},
     {'value': '知识产权律师', 'label': '知识产权律师'}]},
   {'value': '翻译',
    'label': '翻译',
    'children': [{'value': '俄语翻译', 'label': '俄语翻译'},
     {'value': '其他语种翻译', 'label': '其他语种翻译'},
     {'value': '德语翻译', 'label': '德语翻译'},
     {'value': '日语翻译', 'label': '日语翻译'},
     {'value': '法语翻译', 'label': '法语翻译'},
     {'value': '英语翻译', 'label': '英语翻译'},
     {'value': '西班牙语翻译', 'label': '西班牙语翻译'},
     {'value': '韩语/朝鲜语翻译', 'label': '韩语/朝鲜语翻译'}]}]},
 {'value': '市场',
  'label': '市场',
  'children': [{'value': '会务会展',
    'label': '会务会展',
    'children': [{'value': '会务会展', 'label': '会务会展'},
     {'value': '会展活动执行', 'label': '会展活动执行'},
     {'value': '会展活动策划', 'label': '会展活动策划'},
     {'value': '会议活动执行', 'label': '会议活动执行'},
     {'value': '会议活动策划', 'label': '会议活动策划'}]},
   {'value': '公关媒介',
    'label': '公关媒介',
    'children': [{'value': '公关媒介', 'label': '公关媒介'},
     {'value': '品牌公关', 'label': '品牌公关'},
     {'value': '媒介专员', 'label': '媒介专员'},
     {'value': '媒介策划', 'label': '媒介策划'},
     {'value': '媒介经理', 'label': '媒介经理'},
     {'value': '广告客户执行', 'label': '广告客户执行'},
     {'value': '活动策划执行', 'label': '活动策划执行'}]},
   {'value': '其他市场职位',
    'label': '其他市场职位',
    'children': [{'value': '其他市场职位', 'label': '其他市场职位'}]},
   {'value': '市场/营销',
    'label': '市场/营销',
    'children': [{'value': 'APP推广', 'label': 'APP推广'},
     {'value': 'SEM', 'label': 'SEM'},
     {'value': 'SEO', 'label': 'SEO'},
     {'value': '信息流优化师', 'label': '信息流优化师'},
     {'value': '商业数据分析', 'label': '商业数据分析'},
     {'value': '商务渠道', 'label': '商务渠道'},
     {'value': '市场推广', 'label': '市场推广'},
     {'value': '市场策划', 'label': '市场策划'},
     {'value': '市场营销', 'label': '市场营销'},
     {'value': '市场顾问', 'label': '市场顾问'},
     {'value': '活动策划', 'label': '活动策划'},
     {'value': '海外市场', 'label': '海外市场'},
     {'value': '游戏推广', 'label': '游戏推广'},
     {'value': '网络推广', 'label': '网络推广'},
     {'value': '网络营销', 'label': '网络营销'},
     {'value': '营销主管', 'label': '营销主管'},
     {'value': '选址开发', 'label': '选址开发'}]},
   {'value': '广告',
    'label': '广告',
    'children': [{'value': '媒介合作', 'label': '媒介合作'},
     {'value': '媒介投放', 'label': '媒介投放'},
     {'value': '广告', 'label': '广告'},
     {'value': '广告/会展项目经理', 'label': '广告/会展项目经理'},
     {'value': '广告创意设计', 'label': '广告创意设计'},
     {'value': '广告制作', 'label': '广告制作'},
     {'value': '广告审核', 'label': '广告审核'},
     {'value': '广告文案', 'label': '广告文案'},
     {'value': '广告设计', 'label': '广告设计'},
     {'value': '策划经理', 'label': '策划经理'},
     {'value': '美术指导', 'label': '美术指导'}]},
   {'value': '政府事务',
    'label': '政府事务',
    'children': [{'value': '企业党建', 'label': '企业党建'},
     {'value': '政府关系', 'label': '政府关系'},
     {'value': '政策研究', 'label': '政策研究'},
     {'value': '社工', 'label': '社工'}]},
   {'value': '高端市场职位',
    'label': '高端市场职位',
    'children': [{'value': 'CMO', 'label': 'CMO'},
     {'value': '公关总监', 'label': '公关总监'},
     {'value': '创意总监', 'label': '创意总监'},
     {'value': '媒介总监', 'label': '媒介总监'},
     {'value': '市场总监', 'label': '市场总监'},
     {'value': '高端市场职位', 'label': '高端市场职位'}]}]},
 {'value': '房地产/建筑',
  'label': '房地产/建筑',
  'children': [{'value': '其他房地产职位',
    'label': '其他房地产职位',
    'children': [{'value': '其他房地产职位', 'label': '其他房地产职位'}]},
   {'value': '工程管理',
    'label': '工程管理',
    'children': [{'value': '工程监理', 'label': '工程监理'},
     {'value': '工程造价', 'label': '工程造价'},
     {'value': '工程预算', 'label': '工程预算'},
     {'value': '建筑施工项目经理', 'label': '建筑施工项目经理'},
     {'value': '施工员', 'label': '施工员'},
     {'value': '施工安全员', 'label': '施工安全员'},
     {'value': '材料员', 'label': '材料员'},
     {'value': '测绘/测量', 'label': '测绘/测量'},
     {'value': '资料员', 'label': '资料员'}]},
   {'value': '建筑/规划设计',
    'label': '建筑/规划设计',
    'children': [{'value': 'BIM工程师', 'label': 'BIM工程师'},
     {'value': '园林/景观设计', 'label': '园林/景观设计'},
     {'value': '土木/土建/结构工程师', 'label': '土木/土建/结构工程师'},
     {'value': '城市规划设计', 'label': '城市规划设计'},
     {'value': '幕墙工程师', 'label': '幕墙工程师'},
     {'value': '建筑工程师', 'label': '建筑工程师'},
     {'value': '建筑机电工程师', 'label': '建筑机电工程师'},
     {'value': '建筑设计师', 'label': '建筑设计师'},
     {'value': '弱电工程师', 'label': '弱电工程师'},
     {'value': '暖通工程师', 'label': '暖通工程师'},
     {'value': '消防工程师', 'label': '消防工程师'},
     {'value': '给排水工程师', 'label': '给排水工程师'},
     {'value': '设计装修与市政建设', 'label': '设计装修与市政建设'}]},
   {'value': '房地产规划开发',
    'label': '房地产规划开发',
    'children': [{'value': '地产招投标', 'label': '地产招投标'},
     {'value': '地产项目管理', 'label': '地产项目管理'},
     {'value': '房产评估师', 'label': '房产评估师'},
     {'value': '房地产策划', 'label': '房地产策划'},
     {'value': '房地产规划开发', 'label': '房地产规划开发'}]},
   {'value': '物业管理',
    'label': '物业管理',
    'children': [{'value': '物业管理员', 'label': '物业管理员'},
     {'value': '物业经理', 'label': '物业经理'},
     {'value': '综合维修工', 'label': '综合维修工'},
     {'value': '绿化工', 'label': '绿化工'}]},
   {'value': '装饰装修',
    'label': '装饰装修',
    'children': [{'value': '室内设计', 'label': '室内设计'},
     {'value': '装修项目经理', 'label': '装修项目经理'},
     {'value': '软装设计师', 'label': '软装设计师'}]},
   {'value': '高端房地产职位',
    'label': '高端房地产职位',
    'children': [{'value': '地产招投标总监', 'label': '地产招投标总监'},
     {'value': '地产策划总监', 'label': '地产策划总监'},
     {'value': '地产项目总监', 'label': '地产项目总监'},
     {'value': '高端房地产职位', 'label': '高端房地产职位'}]}]},
 {'value': '技术',
  'label': '技术',
  'children': [{'value': '人工智能',
    'label': '人工智能',
    'children': [{'value': '人工智能', 'label': '人工智能'},
     {'value': '反欺诈/风控算法', 'label': '反欺诈/风控算法'},
     {'value': '图像识别', 'label': '图像识别'},
     {'value': '推荐算法', 'label': '推荐算法'},
     {'value': '搜索算法', 'label': '搜索算法'},
     {'value': '数据挖掘', 'label': '数据挖掘'},
     {'value': '智能驾驶系统工程师', 'label': '智能驾驶系统工程师'},
     {'value': '机器学习', 'label': '机器学习'},
     {'value': '深度学习', 'label': '深度学习'},
     {'value': '算法工程师', 'label': '算法工程师'},
     {'value': '算法研究员', 'label': '算法研究员'},
     {'value': '自然语言处理', 'label': '自然语言处理'},
     {'value': '语音识别', 'label': '语音识别'}]},
   {'value': '其他技术职位',
    'label': '其他技术职位',
    'children': [{'value': '其他技术职位', 'label': '其他技术职位'}]},
   {'value': '前端开发',
    'label': '前端开发',
    'children': [{'value': 'Flash开发', 'label': 'Flash开发'},
     {'value': '前端开发工程师', 'label': '前端开发工程师'}]},
   {'value': '后端开发',
    'label': '后端开发',
    'children': [{'value': '.NET', 'label': '.NET'},
     {'value': 'C', 'label': 'C'},
     {'value': 'C#', 'label': 'C#'},
     {'value': 'C++', 'label': 'C++'},
     {'value': 'Delphi', 'label': 'Delphi'},
     {'value': 'Erlang', 'label': 'Erlang'},
     {'value': 'GIS工程师', 'label': 'GIS工程师'},
     {'value': 'Golang', 'label': 'Golang'},
     {'value': 'Hadoop', 'label': 'Hadoop'},
     {'value': 'Java', 'label': 'Java'},
     {'value': 'Node.js', 'label': 'Node.js'},
     {'value': 'PHP', 'label': 'PHP'},
     {'value': 'Perl', 'label': 'Perl'},
     {'value': 'Python', 'label': 'Python'},
     {'value': 'Ruby', 'label': 'Ruby'},
     {'value': 'VB', 'label': 'VB'},
     {'value': '全栈工程师', 'label': '全栈工程师'},
     {'value': '后端开发', 'label': '后端开发'},
     {'value': '数据采集', 'label': '数据采集'},
     {'value': '语音/视频/图形开发', 'label': '语音/视频/图形开发'}]},
   {'value': '数据',
    'label': '数据',
    'children': [{'value': 'ETL工程师', 'label': 'ETL工程师'},
     {'value': '数据', 'label': '数据'},
     {'value': '数据仓库', 'label': '数据仓库'},
     {'value': '数据分析师', 'label': '数据分析师'},
     {'value': '数据开发', 'label': '数据开发'},
     {'value': '数据挖掘', 'label': '数据挖掘'},
     {'value': '数据架构师', 'label': '数据架构师'}]},
   {'value': '测试',
    'label': '测试',
    'children': [{'value': '功能测试', 'label': '功能测试'},
     {'value': '性能测试', 'label': '性能测试'},
     {'value': '测试工程师', 'label': '测试工程师'},
     {'value': '测试开发', 'label': '测试开发'},
     {'value': '渗透测试', 'label': '渗透测试'},
     {'value': '游戏测试', 'label': '游戏测试'},
     {'value': '硬件测试', 'label': '硬件测试'},
     {'value': '移动端测试', 'label': '移动端测试'},
     {'value': '自动化测试', 'label': '自动化测试'},
     {'value': '软件测试', 'label': '软件测试'}]},
   {'value': '电子/半导体',
    'label': '电子/半导体',
    'children': [{'value': 'FAE', 'label': 'FAE'},
     {'value': 'IC验证工程师', 'label': 'IC验证工程师'},
     {'value': '版图设计工程师', 'label': '版图设计工程师'},
     {'value': '电子工程师', 'label': '电子工程师'},
     {'value': '电气工程师', 'label': '电气工程师'},
     {'value': '电气设计工程师', 'label': '电气设计工程师'},
     {'value': '集成电路IC设计', 'label': '集成电路IC设计'}]},
   {'value': '硬件开发',
    'label': '硬件开发',
    'children': [{'value': 'ARM开发', 'label': 'ARM开发'},
     {'value': 'DSP开发', 'label': 'DSP开发'},
     {'value': 'FPGA开发', 'label': 'FPGA开发'},
     {'value': 'PCB工艺', 'label': 'PCB工艺'},
     {'value': '光学工程师', 'label': '光学工程师'},
     {'value': '单片机', 'label': '单片机'},
     {'value': '射频工程师', 'label': '射频工程师'},

In [436]:
redis.set('fontEnd:industry_data',ujson.dumps(industry_data))

True