In [1]:


import pandas as pd

In [3]:
from store.db.db_store import Mongo

mongo = Mongo()

In [13]:

pd.DataFrame(mongo.db.industry_info.find().limit(5).skip(3))

,_id,first_industry,second_industry,third_industry,third_industry_url
0,63e74e1a3b81c5a5e25c1493,技术,后端开发,C,https://www.zhipin.com/c101270100-p100105/
1,63e74e1a3b81c5a5e25c1494,技术,后端开发,C#,https://www.zhipin.com/c101270100-p100106/
2,63e74e1a3b81c5a5e25c1495,技术,后端开发,.NET,https://www.zhipin.com/c101270100-p100107/
3,63e74e1a3b81c5a5e25c1496,技术,后端开发,Hadoop,https://www.zhipin.com/c101270100-p100108/
4,63e74e1a3b81c5a5e25c1497,技术,后端开发,Python,https://www.zhipin.com/c101270100-p100109/

In [4]:
mongo.db.industry_info.find().count()

945

In [11]:
pd.DataFrame(mongo.db.industry_info.find().limit(5).skip(0))

,_id,first_industry,second_industry,third_industry,third_industry_url
0,63e74e1a3b81c5a5e25c1490,技术,后端开发,Java,https://www.zhipin.com/c101270100-p100101/
1,63e74e1a3b81c5a5e25c1491,技术,后端开发,C++,https://www.zhipin.com/c101270100-p100102/
2,63e74e1a3b81c5a5e25c1492,技术,后端开发,PHP,https://www.zhipin.com/c101270100-p100103/
3,63e74e1a3b81c5a5e25c1493,技术,后端开发,C,https://www.zhipin.com/c101270100-p100105/
4,63e74e1a3b81c5a5e25c1494,技术,后端开发,C#,https://www.zhipin.com/c101270100-p100106/

In [16]:
pd.DataFrame(mongo.db.industry_info.find({}, {"_id": 0}).limit(0).skip(0))

,first_industry,second_industry,third_industry,third_industry_url
0,技术,后端开发,Java,https://www.zhipin.com/c101270100-p100101/
1,技术,后端开发,C++,https://www.zhipin.com/c101270100-p100102/
2,技术,后端开发,PHP,https://www.zhipin.com/c101270100-p100103/
3,技术,后端开发,C,https://www.zhipin.com/c101270100-p100105/
4,技术,后端开发,C#,https://www.zhipin.com/c101270100-p100106/
...,...,...,...,...
940,生产制造,技工/普工,搬运工/装卸工,https://www.zhipin.com/c101270100-p300630/
941,生产制造,技工/普工,切割工,https://www.zhipin.com/c101270100-p300631/
942,生产制造,技工/普工,样衣工,https://www.zhipin.com/c101270100-p300632/
943,生产制造,技工/普工,模具工,https://www.zhipin.com/c101270100-p300633/
944,生产制造,其他生产制造职位,其他生产制造职位,https://www.zhipin.com/c101270100-p300701/

In [5]:
job_df = pd.DataFrame(mongo.find("job", limit=100))

In [6]:
job_df

,job_name,job_area,salary,job_experience,job_degree,skill_list,welfare_list,boss_name,boss_title,brand_logo,brand_name,brand_industry,brand_scale_name,brand_stage_name,detail_url,company_detail_url
0,Java开发工程师,成都·武侯区·环球中心,7-12K,3-5年,本科,"[Java, 后端开发, Javascript]",[餐补，节日福利，员工旅游，年终奖，五险一金],涂先生,人事经理,https://img.bosszhipin.com/beijin/mcs/chatphot...,云麦尔,计算机软件,未融资,20-99人,https://www.zhipin.com//job_detail/3b79fa5972b...,https://www.zhipin.com//gongsi/3554a281ccf5b91...
1,Java开发工程师,成都·金牛区·抚琴,10-15K,3-5年,本科,[Java],[餐补，节日福利，带薪年假，双休，五险一金],赵女士,招聘主管,https://img.bosszhipin.com/beijin/mcs/banner/9...,天阳科技,计算机软件,已上市,1000-9999人,https://www.zhipin.com//job_detail/09d3f60c1fe...,https://www.zhipin.com//gongsi/6378403b3ea8ffc...
2,JAVA开发工程师,成都·郫都区·高新西,10-15K,3-5年,本科,"[MVC开发, 服务器配置, Socket技术, 分布式技术, 架构师, 服务器端开发, S...",[],叶女士,HR,https://img.bosszhipin.com/beijin/app/mobile/n...,瀚德科技,通信/网络设备,20-99人,None,https://www.zhipin.com//job_detail/307a66a05a9...,https://www.zhipin.com//gongsi/4987526eca2c48b...
3,游戏服务器,成都·双流区·华阳,8-12K,1-3年,学历不限,"[后端工程师, Hibernate, 全栈开发, 负载均衡技术, 游戏引擎, MySQL, ...",[],李女士,HR,https://img.bosszhipin.com/beijin/icon/894ce6f...,一起玩乐,游戏,0-20人,None,https://www.zhipin.com//job_detail/81c2b2891da...,https://www.zhipin.com//gongsi/de6766108258f9e...
4,Java,成都·武侯区·新会展中心,20-40K·16薪,经验不限,本科,"[分布式技术, 多线程, 微服务架构, 后端开发, Linux, 高级软件工程师, 银行]",[],彭先生,高级后端开发工程师,https://img.bosszhipin.com/beijin/icon/894ce6f...,蚂蚁智服(成都)信息,互联网,20-99人,None,https://www.zhipin.com//job_detail/260a9e7a967...,https://www.zhipin.com//gongsi/4a1ac5e56504536...
5,Java开发工程师-成都,成都·锦江区·三圣乡,7-10K·13薪,经验不限,大专,"[SpringBoot, SpringCloud, Spring, Oracle]",[年终奖，零食下午茶，五险一金，全勤奖],周女士,产品经理,https://img.bosszhipin.com/beijin/upload/com/l...,吉姆科技,互联网,未融资,0-20人,https://www.zhipin.com//job_detail/a7584ea2c3a...,https://www.zhipin.com//gongsi/a5c675f419b19bf...
6,Java程序员,成都·郫都区·郫县城区,11-20K,3-5年,本科,"[SQL, 分布式技术, MVC开发, Spring, Hibernate, MySQL, ...",[带薪年假，五险一金，节日福利，交通补助],谭女士,hr,https://img.bosszhipin.com/beijin/icon/894ce6f...,华迪信息,计算机软件,100-499人,None,https://www.zhipin.com//job_detail/fb0405a320f...,https://www.zhipin.com//gongsi/573c52da0ce3b5d...
7,云服务java开发工程师（OD）,成都·郫都区·高新西,15-28K·14薪,经验不限,本科,"[Python, 微服务架构, 分布式技术, 数据结构, SpringBoot, Sprin...",[定期体检，年终奖，员工旅游，加班补助，股票期权，节日福利，五险一金，补充医疗保险，餐补，零...,谷女士,高级工程师,https://img.bosszhipin.com/beijin/upload/com/l...,华为,计算机软件,不需要融资,10000人以上,https://www.zhipin.com//job_detail/c9a9175eca8...,https://www.zhipin.com//gongsi/02cd05cce753437...
8,中间件Redis存储研发工程师,成都·武侯区·新会展中心,25-50K·16薪,3-5年,本科,"[Java开发经验, 云原生, Java, 分布式系统开发经验, Redis, 高级后端工程...",[年终奖，带薪年假，股票期权，五险一金，零食下午茶，定期体检],何先生,招聘者,https://img.bosszhipin.com/beijin/mcs/bar/2019...,OPPO,互联网,不需要融资,10000人以上,https://www.zhipin.com//job_detail/35d0c403844...,https://www.zhipin.com//gongsi/cd2e2ae2dcc3913...
9,软件开发工程师,成都·双流区·城南优品道广场,8-13K·13薪,5-10年,本科,"[Python, Shell, SQL, 多线程, 高级软件工程师, 后端开发, 驱动开发,...",[年终奖，员工旅游，补充医疗保险，节日福利，定期体检，五险一金，带薪年假],任先生,综合管理部部长,https://img.bosszhipin.com/beijin/upload/com/w...,四川橙科通信,移动互联网,未融资,20-99人,https://www.zhipin.com//job_detail/80c959ac7d7...,https://www.zhipin.com//gongsi/f804489dbb767fe...
10,游戏服务端开发,成都·双流区·华阳,9-13K·13薪,5-10年,大专,"[Java, C/C++]",[五险一金，年终奖，零食下午茶],白女士,行政人事,https://img.bosszhipin.com/beijin/upload/com/l...,锋魔互娱,游戏,未融资,20-99人,https://www.zhipin.com//job_detail/a02ff08f58a...,https://www.zhipin.com//gongsi/14bd82201afb548...
11,研发工程师,成都·武侯区·磨子桥,7-12K,在校/应届,本科,"[Java, 数据库, Android]",[五险一金，年终奖，全勤奖，交通补助，定期体检，节日福利，餐补，带薪年假，住房补贴，零食下午...,李女士,HR,https://img.bosszhipin.com/beijin/mcs/chatphot...,中科院信息技术,互联网,已上市,100-499人,https://www.zhipin.com//job_detail/7592a1c8137...,https://www.zhipin.com//gongsi/391f2a96aab598a...
12,高级Java广告后台工程师,成都·武侯区·新会展中心,30-60K·15薪,5-10年,本科,"[Java, Java开发经验, 分布式系统开发经验, 团队管理经验, 广告 广告推荐系统]",[定期体检，团建聚餐，补充医疗保险，保底工资，年终奖，五险一金，带薪年假],刘女士,hr,https://img.bosszhipin.com/beijin/upload/com/w...,美团,互联网,已上市,10000人以上,https://www.zhipin.com//job_detail/a90be8f6392...,https://www.zhipin.com//gongsi/b633a34f787d94f...
13,IT经理/主管,成都·武侯区·新会展中心,15-20K,3-5年,本科,"[后端工程师, Java]",[五险一金，加班补助，年终奖，带薪年假，节日福利，零食下午茶],孟女士,人事经理,https://c-res.zhipin.com/jrs/9fae23c91dd91b0bd...,汇九通网络,互联网,A轮,100-499人,https://www.zhipin.com//job_detail/b9206330d51...,https://www.zhipin.com//gongsi/f6b9bb1a038793d...
14,程序员,成都·武侯区·红牌楼,4-9K,1年以内,本科,"[Java, Web前端, HTML/CSS]",[五险一金，全勤奖，年终奖，带薪年假，节日福利],熊女士,人事,https://img.bosszhipin.com/beijin/mcs/chatphot...,浩诺优,计算机软件,不需要融资,100-499人,https://www.zhipin.com//job_detail/9093316e084...,https://www.zhipin.com//gongsi/4b7593e2cae8b88...
15,java开发工程师,成都,10-15K·14薪,3-5年,本科,"[Spring, HTML, Oracle, WEB开发, Mybatis, Hiberna...",[包吃，补充医疗保险，交通补助，带薪年假，员工旅游，年终奖，餐补，定期体检，通讯补贴，节日福...,张女士,HR,https://img.bosszhipin.com/beijin/mcs/chatphot...,成都运达科技,其他行业,已上市,500-999人,https://www.zhipin.com//job_detail/68274834bd5...,https://www.zhipin.com//gongsi/af2836104a9866f...
16,高级Java开发工程师,成都·武侯区·新会展中心,20-40K·16薪,5-10年,本科,"[Java, 分布式技术, 多线程, Redis, SpringBoot, 后端工程师, S...",[],丁女士,招聘,https://img.bosszhipin.com/beijin/icon/894ce6f...,英悦芯瑞,互联网,1000-9999人,None,https://www.zhipin.com//job_detail/e4125d83d93...,https://www.zhipin.com//gongsi/13c8b7a755f79cf...
17,Java开发工程师（CPYF）(J10149),成都·武侯区·新会展中心,12-24K,3-5年,本科,"[SpringBoot, SpringCloud, Spring, SpringMVC]",[高温假，股票期权，节日福利，交通补助，补充医疗保险，年终奖，五险一金，通讯补贴，带薪年假，...,刘先生,HRBP主管,https://img.bosszhipin.com/beijin/mcs/bar/2019...,卫士通,信息安全,已上市,1000-9999人,https://www.zhipin.com//job_detail/f9da4f8c083...,https://www.zhipin.com//gongsi/68ef96cc5c4392e...
18,后端开发工程师,成都·武侯区·火车南站,10-15K,3-5年,本科,"[PHP, SQL, 分布式技术, 网络协议, 多线程, 后端开发, Netty, MySQL]",[定期体检，通讯补贴，节日福利，五险一金，补充医疗保险，员工旅游，住房补贴，交通补助，带薪年...,冉女士,H R,https://img.bosszhipin.com/beijin/upload/com/w...,CSCT,移动互联网,未融资,100-499人,https://www.zhipin.com//job_detail/5b85a3954fb...,https://www.zhipin.com//gongsi/29f2dce388599f5...
19,成都Java开发工程师,成都·锦江区·天府广场,9-14K·14薪,3-5年,本科,"[CSS, 网络协议, Oracle, SQL, 微服务架构, 分布式技术, MVC开发, ...",[住房补贴，通讯补贴，节日福利，交通补助，年终奖，餐补，定期体检，带薪年假，五险一金，员工旅游],索女士,HR,https://img.bosszhipin.com/beijin/mcs/banner/8...,新点软件,计算机软件,已上市,1000-9999人,https://www.zhipin.com//job_detail/accf89b22d2...,https://www.zhipin.com//gongsi/1947e93f01e5744...
20,java后端工程师,成都·武侯区·大源,15-30K,3-5年,本科,"[后端工程师, Java]",[补充医疗保险，带薪年假，年终奖，餐补，员工旅游，定期体检，五险一金],赵先生,架构师,https://img.bosszhipin.com/beijin/mcs/chatphot...,斑马网络,互联网,A轮,1000-9999人,https://www.zhipin.com//job_detail/56ba31b87ac...,https://www.zhipin.com//gongsi/27fb2459c5457b1...
21,Java讲师/助理讲师,成都·金牛区·沙湾,15-20K·13薪,3-5年,本科,"[SpringBoot, SSM, MySQL, SpringMVC, Spring, 后端开发]",[五险一金，餐补，节日福利，员工旅游，通讯补贴，带薪年假，全勤奖，年终奖，定期体检，零食下午茶],李女士,人事经理,https://img.bosszhipin.com/beijin/mcs/chatphot...,法赛特科技,智能硬件,不需要融资,100-499人,https://www.zhipin.com//job_detail/a9efb302245...,https://www.zhipin.com//gongsi/0a9ba86f971a42d...
22,后端开发工程师,成都·双流区·华阳,12-20K·14薪,3-5年,本科,"[SQL, 分布式技术, 架构师, SpringBoot, Spring, NoSQL, M...",[五险一金，通讯补贴，定期体检，补充医疗保险，带薪年假，意外险，节日福利，企业年金，交通补助...,张先生,研发部总经理,https://img.bosszhipin.com/beijin/upload/com/w...,联通产互,互联网,未融资,100-499人,https://www.zhipin.com//job_detail/a1922495eb0...,https://www.zhipin.com//gongsi/ca86601cfc23893...
23,系统软件开发,成都·成华区·万年场,5-9K·13薪,经验不限,大专,"[HTML, CSS, 网络协议, MVC开发, Spring]",[],杜女士,人事,https://img.bosszhipin.com/beijin/upload/com/l...,蕾琼丹,贸易/进出口,20-99人,None,https://www.zhipin.com//job_detail/fa31eda1c85...,https://www.zhipin.com//gongsi/7b4be5c341341f5...
24,中级JAVA开发工程师,成都·武侯区·孵化园,13-17K,3-5年,本科,"[全栈工程师, Java]",[零食下午茶，股票期权，五险一金，带薪年假，节假日加班费，夜班补助，生日福利，年终奖],缪女士,综合部经理,https://img.bosszhipin.com/beijin/mcs/chatphot...,迅鳐科技,数据服务,B轮,20-99人,https://www.zhipin.com//job_detail/a4e656befad...,https://www.zhipin.com//gongsi/95764af43634250...
25,Java开发工程师,成都·青羊区·贝森,15-25K,5-10年,本科,"[架构师, GIT, 分布式技术, Linux, 微服务架构, scala, hadoop,...",[五险一金，员工旅游，加班补助，生日卡，通讯补贴，定期体检，节日福利，带薪年假，餐补，年终奖],李先生,招聘经理,https://img.bosszhipin.com/beijin/mcs/banner/8...,上海直真君智,计算机软件,未融资,100-499人,https://www.zhipin.com//job_detail/2eea2042942...,https://www.zhipin.com//gongsi/f089d5785a56df8...
26,全栈开发工程师,成都·青羊区·太升路,6-8K,3-5年,本科,"[全栈开发, 软件工程师]",[五险一金，零食下午茶，股票期权，节日福利，员工旅游，年终奖],何女士,招聘者,https://img.bosszhipin.com/beijin/mcs/chatphot...,噬极兽,宠物服务,天使轮,0-20人,https://www.zhipin.com//job_detail/1f0bc84f876...,https://www.zhipin.com//gongsi/92813c4bf842c4b...
27,中级Java开发工程师,成都·武侯区·新会展中心,6-11K·13薪,1-3年,大专,"[Java, SQL, MySQL, 后端开发, SQL Server, Maven]",[],雷先生,招聘者,https://img.bosszhipin.com/beijin/app/mobile/n...,智能时代,互联网,20-99人,None,https://www.zhipin.com//job_detail/62dcf978f5e...,https://www.zhipin.com//gongsi/ea5a1a07c929f26...
28,Java开发工程师,成都·锦江区·柳江,6-10K·13薪,1-3年,本科,"[HTML, 后端开发, Oracle, SQL, 软件工程师, SSM, IDEA]",[五险一金，餐补，加班补助，全勤奖，员工旅游，带薪年假，年终奖，定期体检，节日福利],万先生,开发,https://img.bosszhipin.com/beijin/mcs/banner/f...,久远银海,计算机软件,已上市,1000-9999人,https://www.zhipin.com//job_detail/d63674256aa...,https://www.zhipin.com//gongsi/64e388bae68360a...
29,JAVA 开发工程师,成都·武侯区·新会展中心,11-20K·13薪,3-5年,大专,"[HTML, CSS, 分布式技术, 后端开发, MySQL]",[节日福利，员工旅游，餐补，年终奖，全勤奖，合伙人，晋升机会多，住房补贴，股票期权，工龄补贴],唐先生,技术经理,https://img.bosszhipin.com/beijin/upload/com/l...,云丰档案,其他专业服务,未融资,100-499人,https://www.zhipin.com//job_detail/e9073f4d119...,https://www.zhipin.com//gongsi/160d0a5e263eca6...

In [8]:
job_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_name            30 non-null     object
 1   job_area            30 non-null     object
 2   salary              30 non-null     object
 3   job_experience      30 non-null     object
 4   job_degree          30 non-null     object
 5   skill_list          30 non-null     object
 6   welfare_list        30 non-null     object
 7   boss_name           30 non-null     object
 8   boss_title          30 non-null     object
 9   brand_logo          30 non-null     object
 10  brand_name          30 non-null     object
 11  brand_industry      30 non-null     object
 12  brand_scale_name    30 non-null     object
 13  brand_stage_name    23 non-null     object
 14  detail_url          30 non-null     object
 15  company_detail_url  30 non-null     object
dtypes: object(16)
memory usage: 3.9+ KB

In [9]:
job_df.describe()

,job_name,job_area,salary,job_experience,job_degree,skill_list,welfare_list,boss_name,boss_title,brand_logo,brand_name,brand_industry,brand_scale_name,brand_stage_name,detail_url,company_detail_url
count,30,30,30,30,30,30,30,30,30,30,30,30,30,23,30,30
unique,26,20,26,6,3,29,25,28,20,26,30,12,10,6,30,30
top,Java开发工程师,成都·武侯区·新会展中心,10-15K,3-5年,本科,"[后端工程师, Java]",[],李女士,HR,https://img.bosszhipin.com/beijin/icon/894ce6f...,云麦尔,互联网,未融资,100-499人,https://www.zhipin.com//job_detail/3b79fa5972b...,https://www.zhipin.com//gongsi/3554a281ccf5b91...
freq,4,8,3,16,24,2,6,3,5,4,1,10,8,8,1,1

## 修改industry_info的third_industry_url

In [7]:
up_df = pd.DataFrame(mongo.find('industry_info'))
up_df

,first_industry,second_industry,third_industry,third_industry_url
0,技术,后端开发,Java,https://www.zhipin.com/c101270100-p100101/
1,技术,后端开发,C++,https://www.zhipin.com/c101270100-p100102/
2,技术,后端开发,PHP,https://www.zhipin.com/c101270100-p100103/
3,技术,后端开发,C,https://www.zhipin.com/c101270100-p100105/
4,技术,后端开发,C#,https://www.zhipin.com/c101270100-p100106/
...,...,...,...,...
940,生产制造,技工/普工,搬运工/装卸工,https://www.zhipin.com/c101270100-p300630/
941,生产制造,技工/普工,切割工,https://www.zhipin.com/c101270100-p300631/
942,生产制造,技工/普工,样衣工,https://www.zhipin.com/c101270100-p300632/
943,生产制造,技工/普工,模具工,https://www.zhipin.com/c101270100-p300633/
944,生产制造,其他生产制造职位,其他生产制造职位,https://www.zhipin.com/c101270100-p300701/

### 切分出url列的城市编号

In [9]:
up_df.third_industry_url

AttributeError: 'Series' object has no attribute 'split'

In [26]:
url_sp = up_df.third_industry_url.str.rsplit("p", n=1, expand=True)[1].str.rstrip("/")
url_sp

0      100101
1      100102
2      100103
3      100105
4      100106
        ...
940    300630
941    300631
942    300632
943    300633
944    300701
Name: 1, Length: 945, dtype: object

In [27]:
url_sp

0      100101
1      100102
2      100103
3      100105
4      100106
        ...
940    300630
941    300631
942    300632
943    300633
944    300701
Name: 1, Length: 945, dtype: object

### 使用apply()拼接字符串

In [40]:
from spider.coroutine_crawl import RECRUITMENT_URL

up_df.third_industry_url = url_sp.apply(lambda x: f'{RECRUITMENT_URL}?city=100010000&position={x}')
up_df

,first_industry,second_industry,third_industry,third_industry_url
0,技术,后端开发,Java,https://www.zhipin.com/web/geek/job?city=10001...
1,技术,后端开发,C++,https://www.zhipin.com/web/geek/job?city=10001...
2,技术,后端开发,PHP,https://www.zhipin.com/web/geek/job?city=10001...
3,技术,后端开发,C,https://www.zhipin.com/web/geek/job?city=10001...
4,技术,后端开发,C#,https://www.zhipin.com/web/geek/job?city=10001...
...,...,...,...,...
940,生产制造,技工/普工,搬运工/装卸工,https://www.zhipin.com/web/geek/job?city=10001...
941,生产制造,技工/普工,切割工,https://www.zhipin.com/web/geek/job?city=10001...
942,生产制造,技工/普工,样衣工,https://www.zhipin.com/web/geek/job?city=10001...
943,生产制造,技工/普工,模具工,https://www.zhipin.com/web/geek/job?city=10001...
944,生产制造,其他生产制造职位,其他生产制造职位,https://www.zhipin.com/web/geek/job?city=10001...

In [94]:
up_dict = up_df.iloc[:, -2:].to_dict()
up_dict

{'third_industry': {0: 'Java',
  1: 'C++',
  2: 'PHP',
  3: 'C',
  4: 'C#',
  5: '.NET',
  6: 'Hadoop',
  7: 'Python',
  8: 'Delphi',
  9: 'VB',
  10: 'Perl',
  11: 'Ruby',
  12: 'Node.js',
  13: 'Golang',
  14: 'Erlang',
  15: '语音/视频/图形开发',
  16: '数据采集',
  17: '全栈工程师',
  18: 'GIS工程师',
  19: '后端开发',
  20: '技术美术',
  21: 'Android',
  22: 'iOS',
  23: 'Flash开发',
  24: 'JavaScript',
  25: 'U3D',
  26: 'Cocos',
  27: 'UE4',
  28: '移动开发',
  29: '测试工程师',
  30: '自动化测试',
  31: '功能测试',
  32: '性能测试',
  33: '测试开发',
  34: '移动端测试',
  35: '游戏测试',
  36: '硬件测试',
  37: '软件测试',
  38: '渗透测试',
  39: '技术文档工程师',
  40: '运维工程师',
  41: '运维开发工程师',
  42: '网络工程师',
  43: '系统工程师',
  44: 'IT技术支持',
  45: '系统管理员',
  46: '网络安全',
  47: '系统安全',
  48: 'DBA',
  49: '数据',
  50: 'ETL工程师',
  51: '数据仓库',
  52: '数据开发',
  53: '数据挖掘',
  54: '数据分析师',
  55: '数据架构师',
  56: '项目经理/主管',
  57: '项目助理',
  58: '项目专员',
  59: '实施顾问',
  60: '实施工程师',
  61: '需求分析工程师',
  62: '硬件项目经理',
  63: '光学工程师',
  64: '硬件工程师',
  65: '嵌入式',
  66: '自动化',
  67: '单片机',
  68: '电路设计',
  69: '驱动开发',
  70: '系统集成',
  71: 'FPGA开发',
  72: 'DSP开发',
  73: 'ARM开发',
  74: 'PCB工艺',
  75: '射频工程师',
  76: '前端开发工程师',
  77: 'Flash开发',
  78: '通信技术工程师',
  79: '通信研发工程师',
  80: '数据通信工程师',
  81: '移动通信工程师',
  82: '电信网络工程师',
  83: '电信交换工程师',
  84: '有线传输工程师',
  85: '无线/射频通信工程师',
  86: '通信电源工程师',
  87: '通信标准化工程师',
  88: '通信项目专员',
  89: '通信项目经理',
  90: '核心网工程师',
  91: '通信测试工程师',
  92: '通信设备工程师',
  93: '光通信工程师',
  94: '光传输工程师',
  95: '光网络工程师',
  96: '版图设计工程师',
  97: '电气工程师',
  98: '电气设计工程师',
  99: '电子工程师',
  100: '集成电路IC设计',
  101: 'FAE',
  102: 'IC验证工程师',
  103: '高端技术职位',
  104: '技术经理',
  105: '技术总监',
  106: '测试经理',
  107: '架构师',
  108: 'CTO',
  109: '运维总监',
  110: '技术合伙人',
  111: '人工智能',
  112: '数据挖掘',
  113: '搜索算法',
  114: '自然语言处理',
  115: '推荐算法',
  116: '算法工程师',
  117: '智能驾驶系统工程师',
  118: '反欺诈/风控算法',
  119: '机器学习',
  120: '深度学习',
  121: '语音识别',
  122: '图像识别',
  123: '算法研究员',
  124: '销售技术支持',
  125: '售前技术支持',
  126: '售后技术支持',
  127: '其他技术职位',
  128: 'AI产品经理',
  129: '化妆品产品经理',
  130: '产品经理',
  131: '移动产品经理',
  132: '产品助理',
  133: '数据产品经理',
  134: '电商产品经理',
  135: '游戏策划',
  136: '产品专员',
  137: '硬件产品经理',
  138: '高级产品管理岗',
  139: '游戏制作人',
  140: '其他产品职位',
  141: '视觉设计',
  142: '视觉设计师',
  143: '网页设计师',
  144: 'Flash设计师',
  145: 'UI设计师',
  146: '平面设计',
  147: '3D设计师',
  148: '广告设计',
  149: '多媒体设计师',
  150: '原画师',
  151: 'CAD设计/制图',
  152: '美工',
  153: '包装设计',
  154: '设计师助理',
  155: '动画设计',
  156: '插画师',
  157: '漫画师',
  158: '人像修图师',
  159: '交互设计师',
  160: '系统策划',
  161: '游戏主美术',
  162: '游戏特效',
  163: '游戏界面设计师',
  164: '游戏场景',
  165: '游戏角色',
  166: '游戏动作',
  167: '游戏数值策划',
  168: '数据分析师',
  169: '用户研究员',
  170: 'UX设计师',
  171: '用户研究经理',
  172: '用户研究总监',
  173: '高端设计职位',
  174: '设计经理/主管',
  175: '设计总监',
  176: '视觉设计总监',
  177: '非视觉设计',
  178: '展览/展示设计',
  179: '照明设计',
  180: '服装/纺织设计',
  181: '工业设计',
  182: '橱柜设计',
  183: '家具设计',
  184: '家居设计',
  185: '珠宝设计',
  186: '室内设计',
  187: '陈列设计',
  188: '其他设计职位',
  189: '淘宝运营',
  190: '天猫运营',
  191: '京东运营',
  192: '拼多多运营',
  193: '亚马逊运营',
  194: '速卖通运营',
  195: '阿里国际站运营',
  196: '亚马逊产品开发',
  197: '运营',
  198: '用户运营',
  199: '产品运营',
  200: '数据/策略运营',
  201: '内容运营',
  202: '活动运营',
  203: '商家运营',
  204: '品类运营',
  205: '游戏运营',
  206: '网站运营',
  207: '新媒体运营',
  208: '社区运营',
  209: '微信运营',
  210: '线下拓展运营',
  211: '国内电商运营',
  212: '运营助理/专员',
  213: '内容审核',
  214: '数据标注/AI训练师',
  215: '直播运营',
  216: '车辆运营',
  217: '跨境电商运营',
  218: '视频运营',
  219: '编辑',
  220: '主编/副主编',
  221: '文案编辑',
  222: '网站编辑',
  223: '采编',
  224: '售前客服',
  225: '售后客服',
  226: '网络客服',
  227: '客服经理',
  228: '客服专员',
  229: '客服主管',
  230: '电话客服',
  231: '咨询热线/呼叫中心客服',
  232: '高端运营职位',
  233: '运营总监',
  234: 'COO',
  235: '客服总监',
  236: '运营经理/主管',
  237: '其他运营职位',
  238: '社工',
  239: '政府关系',
  240: '政策研究',
  241: '企业党建',
  242: '信息流优化师',
  243: '网络推广',
  244: '市场营销',
  245: '市场策划',
  246: '市场顾问',
  247: '市场推广',
  248: 'SEO',
  249: 'SEM',
  250: '商务渠道',
  251: '商业数据分析',
  252: '活动策划',
  253: '网络营销',
  254: '海外市场',
  255: 'APP推广',
  256: '选址开发',
  257: '游戏推广',
  258: '营销主管',
  259: '公关媒介',
  260: '媒介经理',
  261: '广告客户执行',
  262: '品牌公关',
  263: '媒介专员',
  264: '活动策划执行',
  265: '媒介策划',
  266: '会务会展',
  267: '会议活动策划',
  268: '会议活动执行',
  269: '会展活动策划',
  270: '会展活动执行',
  271: '广告',
  272: '广告/会展项目经理',
  273: '广告创意设计',
  274: '美术指导',
  275: '广告设计',
  276: '策划经理',
  277: '广告文案',
  278: '广告制作',
  279: '媒介投放',
  280: '媒介合作',
  281: '广告审核',
  282: '高端市场职位',
  283: '市场总监',
  284: 'CMO',
  285: '公关总监',
  286: '媒介总监',
  287: '创意总监',
  288: '其他市场职位',
  289: '企业文化',
  290: '招聘',
  291: 'HRBP',
  292: '人力资源专员/助理',
  293: '培训',
  294: '薪酬绩效',
  295: '人力资源经理/主管',
  296: '人力资源总监',
  297: '员工关系',
  298: '组织发展',
  299: '文员',
  300: '行政专员/助理',
  301: '前台',
  302: '经理助理',
  303: '后勤',
  304: '行政经理/主管',
  305: '行政总监',
  306: '建筑/工程会计',
  307: '税务外勤会计',
  308: '统计员',
  309: '财务分析/财务BP',
  310: '财务',
  311: '会计',
  312: '出纳',
  313: '财务顾问',
  314: '结算会计',
  315: '税务',
  316: '审计',
  317: '成本会计',
  318: '总账会计',
  319: '财务经理/主管',
  320: 'CFO',
  321: '财务总监/VP',
  322: '法务专员/助理',
  323: '律师',
  324: '法律顾问',
  325: '法务经理/主管',
  326: '法务总监',
  327: '其他职能职位',
  328: '高级管理职位',
  329: '总裁/总经理/CEO',
  330: '副总裁/副总经理/VP',
  331: '分公司/代表处负责人',
  332: '区域负责人(辖多个分公司)',
  333: '总助/CEO助理/董事长助理',
  334: '联合创始人',
  335: '董事会秘书',
  336: '商务专员',
  337: '商务经理',
  338: '客户成功',
  339: '销售助理',
  340: '商务总监',
  341: '销售运营',
  342: '置业顾问',
  343: '地产中介',
  344: '房地产销售/招商',
  345: '物业招商管理',
  346: '房地产销售总监',
  347: '服装导购',
  348: '化妆品导购',
  349: '美容顾问',
  350: '会籍顾问',
  351: '珠宝销售',
  352: '旅游顾问',
  353: '瘦身顾问',
  354: '汽车销售',
  355: '汽车配件销售',
  356: '广告销售',
  357: '会议活动销售',
  358: '会展活动销售',
  359: '证券经纪人',
  360: '信用卡销售',
  361: '保险顾问',
  362: '理财顾问',
  363: '外贸经理',
  364: '外贸业务员',
  365: '销售专员',
  366: '客户代表',
  367: '大客户代表',
  368: 'BD经理',
  369: '渠道销售',
  370: '代理商销售',
  371: '电话销售',
  372: '销售顾问',
  373: '网络销售',
  374: '销售工程师',
  375: '客户经理',
  376: '课程顾问',
  377: '招生顾问',
  378: '留学顾问',
  379: '口腔咨询师',
  380: '医疗销售',
  381: '医疗器械销售',
  382: '医药代表',
  383: '健康顾问',
  384: '医美咨询',
  385: '销售经理',
  386: '销售总监',
  387: '区域总监',
  388: '城市经理',
  389: '销售VP',
  390: '团队经理',
  391: '其他销售职位',
  392: '采编/写作/出版',
  393: '印刷排版',
  394: '记者/采编',
  395: '编辑',
  396: '作者/撰稿人',
  397: '出版发行',
  398: '校对录入',
  399: '公关媒介',
  400: '媒介经理',
  401: '媒介专员',
  402: '广告客户执行',
  403: '品牌公关',
  404: '活动策划执行',
  405: '媒介策划',
  406: '广告',
  407: '广告/会展项目经理',
  408: '广告创意设计',
  409: '美术指导',
  410: '广告设计',
  411: '策划经理',
  412: '广告文案',
  413: '广告制作',
  414: '媒介投放',
  415: '媒介合作',
  416: '广告审核',
  417: '带货主播',
  418: '剧本杀主持人',
  419: '剧本杀编剧',
  420: '儿童引导师',
  421: '影视媒体',
  422: '艺人助理',
  423: '主持人/DJ',
  424: '主播助理',
  425: '灯光师',
  426: '剪辑师',
  427: '影视特效',
  428: '导演/编导',
  429: '摄影/摄像',
  430: '视频编辑',
  431: '音频编辑',
  432: '经纪人',
  433: '后期制作',
  434: '影视发行',
  435: '影视策划',
  436: '主播',
  437: '演员/配音/模特',
  438: '化妆/造型/服装',
  439: '放映员',
  440: '录音/音效',
  441: '制片人',
  442: '编剧',
  443: '其他传媒职位',
  444: '买方分析师',
  445: '基金经理',
  446: '投资银行业务',
  447: '量化研究员',
  448: '证券/基金/期货',
  449: '卖方分析师',
  450: '证券交易员',
  451: '投资者关系/证券事务代表',
  452: '投融资',
  453: '投资经理',
  454: '行业研究',
  455: '投资总监/VP',
  456: '融资',
  457: '并购',
  458: '投后管理',
  459: '投资助理',
  460: '其他投融资职位',
  461: '银行',
  462: '柜员',
  463: '客户经理',
  464: '银行大堂经理',
  465: '信贷专员',
  466: '保险精算师',
  467: '保险理赔',
  468: '风控',
  469: '金融产品经理',
  470: '法务',
  471: '资信评估',
  472: '催收员',
  473: '资产评估',
  474: '合规稽查',
  475: '清算',
  476: '互联网金融',
  477: '其他金融职位',
  478: '教育产品研发',
  479: '课程设计',
  480: '课程编辑',
  481: '培训研究',
  482: '培训师',
  483: '培训策划',
  484: '其他教育产品研发职位',
  485: '教育行政',
  486: '园长/副园长',
  487: '校长/副校长',
  488: '教务管理',
  489: '教学管理',
  490: '班主任/辅导员',
  491: '地理老师',
  492: '教师',
  493: '感统训练教师',
  494: '日语教师',
  495: '其他外语教师',
  496: '语文教师',
  497: '数学教师',
  498: '物理教师',
  499: '化学教师',
  500: '生物教师',
  501: '家教',
  502: '托管老师',
  503: '早教老师',
  504: '助教',
  505: '高中教师',
  506: '初中教师',
  507: '小学教师',
  508: '幼教',
  509: '理科教师',
  510: '文科教师',
  511: '英语教师',
  512: '音乐教师',
  513: '美术教师',
  514: '体育教师/体育教练',
  515: '就业老师',
  516: 'IT培训',
  517: 'JAVA培训讲师',
  518: 'Android培训讲师',
  519: 'iOS培训讲师',
  520: 'PHP培训讲师',
  521: '.NET培训讲师',
  522: 'C++培训讲师',
  523: 'Unity 3D培训讲师',
  524: 'Web前端培训讲师',
  525: '软件测试培训讲师',
  526: '动漫培训讲师',
  527: 'UI设计培训讲师',
  528: '财会培训讲师',
  529: '培训师',
  530: '拓展培训',
  531: '少儿编程老师',
  532: '乒乓球教练',
  533: '羽毛球教练',
  534: '足球教练',
  535: '架子鼓老师',
  536: '教练',
  537: '武术教练',
  538: '轮滑教练',
  539: '表演教师',
  540: '机器人教师',
  541: '书法教师',
  542: '钢琴教师',
  543: '吉他教师',
  544: '古筝教师',
  545: '播音主持教师',
  546: '乐高教师',
  547: '舞蹈老师',
  548: '瑜伽老师',
  549: '游泳教练',
  550: '健身教练',
  551: '篮球教练',
  552: '跆拳道教练',
  553: '其他教育培训职位',
  554: '临床监查员',
  555: '临床医学经理/专员',
  556: '临床协调员',
  557: '临床数据分析',
  558: '临床项目经理',
  559: '临床医学总监',
  560: '其他医生职位',
  561: '幼儿园保健医',
  562: '外科医生',
  563: '儿科医生',
  564: '妇产科医生',
  565: '眼科医生',
  566: '皮肤科医生',
  567: '耳鼻喉科医生',
  568: '麻醉科医生',
  569: '病理科医生',
  570: '医务管理',
  571: '医生助理',
  572: '放射科医生',
  573: '超声科医生',
  574: '内科医生',
  575: '全科医生',
  576: '中医',
  577: '整形医生',
  578: '精神心理科医生',
  579: '药剂师',
  580: '口腔科医生',
  581: '验光师',
  582: '检验科医师',
  583: '护士长',
  584: '护士',
  585: '导医',
  586: '健康整形',
  587: '营养师/健康管理师',
  588: '康复治疗师',
  589: '细胞培养员',
  590: '药物分析',
  591: '药物合成',
  592: '医疗产品技术支持',
  593: '生物信息工程师',
  594: '生物学研究人员',
  595: '药品注册',
  596: '药品生产',
  597: '医药项目经理',
  598: '医药研发',
  599: '试剂研发',
  600: '医疗器械注册',
  601: '医疗器械生产/质量管理',
  602: '医疗器械研发',
  603: '药店店长',
  604: '执业药师/驻店药师',
  605: '药店店员',
  606: '医学编辑',
  607: '其他医疗健康职位',
  608: '招标专员',
  609: '投标专员',
  610: '采购',
  611: '商品经理',
  612: '供应商质量工程师',
  613: '采购总监',
  614: '采购经理/主管',
  615: '采购专员/助理',
  616: '买手',
  617: '采购工程师',
  618: '进出口贸易',
  619: '贸易跟单',
  620: '报关/报检员',
  621: '单证员',
  622: '其他采购/贸易类职位',
  623: '配送站长',
  624: '物流',
  625: '供应链专员',
  626: '供应链经理',
  627: '集装箱管理',
  628: '物流专员',
  629: '物流经理',
  630: '物流运营',
  631: '物流跟单',
  632: '调度员',
  633: '物流/仓储项目经理',
  634: '货运代理专员',
  635: '货运代理经理',
  636: '水/空/陆运操作',
  637: '核销员',
  638: '仓储',
  639: '仓库经理',
  640: '仓库管理员',
  641: '仓库文员',
  642: '配/理/拣/发货',
  643: '无人机飞手',
  644: '交通/运输',
  645: '商务司机',
  646: '网约车司机',
  647: '代驾司机',
  648: '驾校教练',
  649: '货运司机',
  650: '配送员',
  651: '快递员',
  652: '运输经理/主管',
  653: '高端供应链职位',
  654: '供应链总监',
  655: '物流总监',
  656: '其他供应链职位',
  657: '室内设计',
  658: '软装设计师',
  659: '装修项目经理',
  660: '工程监理',
  661: '工程造价',
  662: '工程预算',
  663: '资料员',
  664: '建筑施工项目经理',
  665: '施工员',
  666: '测绘/测量',
  667: '材料员',
  668: '施工安全员',
  669: '房地产规划开发',
  670: '房地产策划',
  671: '地产项目管理',
  672: '地产招投标',
  673: '房产评估师',
  674: '设计装修与市政建设',
  675: '建筑工程师',
  676: '建筑设计师',
  677: '土木/土建/结构工程师',
  678: '园林/景观设计',
  679: '城市规划设计',
  680: '弱电工程师',
  681: '给排水工程师',
  682: '暖通工程师',
  683: '幕墙工程师',
  684: 'BIM工程师',
  685: '建筑机电工程师',
  686: '消防工程师',
  687: '物业经理',
  688: '综合维修工',
  689: '绿化工',
  690: '物业管理员',
  691: '高端房地产职位',
  692: '地产项目总监',
  693: '地产策划总监',
  694: '地产招投标总监',
  695: '其他房地产职位',
  696: '农业/林业技术员',
  697: '饲养员',
  698: '禽畜/水产养殖技术员',
  699: '畜牧兽医',
  700: '咨询/调研',
  701: '知识产权/专利/商标代理人',
  702: '心理咨询师',
  703: '婚恋咨询师',
  704: '企业管理咨询',
  705: '咨询总监',
  706: '数据分析师',
  707: '咨询经理',
  708: '财务咨询顾问',
  709: 'IT咨询顾问',
  710: '人力资源咨询顾问',
  711: '咨询项目管理',
  712: '战略咨询',
  713: '猎头顾问',
  714: '市场调研',
  715: '其他咨询顾问',
  716: '专利律师',
  717: '知识产权律师',
  718: '律师助理',
  719: '事务所律师',
  720: '法务',
  721: '英语翻译',
  722: '日语翻译',
  723: '韩语/朝鲜语翻译',
  724: '法语翻译',
  725: '德语翻译',
  726: '俄语翻译',
  727: '西班牙语翻译',
  728: '其他语种翻译',
  729: '其他咨询/翻译类职位',
  730: '旅游服务',
  731: '计调',
  732: '签证专员',
  733: '导游',
  734: '预定票务',
  735: '讲解员',
  736: '旅游产品开发/策划',
  737: '旅游产品经理',
  738: '旅游策划师',
  739: '其他旅游职位',
  740: '奶茶店店员',
  741: '水台',
  742: '面包/烘焙师',
  743: '餐饮储备店长/干部',
  744: '调酒师',
  745: '餐饮',
  746: '后厨',
  747: '配菜打荷',
  748: '茶艺师',
  749: '蛋糕/裱花师',
  750: '餐饮学徒',
  751: '面点师',
  752: '行政总厨',
  753: '厨师长',
  754: '传菜员',
  755: '洗碗工',
  756: '凉菜厨师',
  757: '中餐厨师',
  758: '西餐厨师',
  759: '日料厨师',
  760: '烧烤师傅',
  761: '收银',
  762: '服务员',
  763: '厨师',
  764: '咖啡师',
  765: '送餐员',
  766: '餐饮店长',
  767: '前厅经理/领班',
  768: '民宿管家',
  769: '礼仪/迎宾/接待',
  770: '酒店前厅经理',
  771: '客房经理',
  772: '酒店前台',
  773: '客房服务员',
  774: '酒店经理',
  775: '督导/巡店',
  776: '陈列员',
  777: '理货员',
  778: '防损员',
  779: '卖场经理',
  780: '促销员',
  781: '导购',
  782: '店员/营业员',
  783: '门店店长',
  784: '纹绣师',
  785: '美体师',
  786: '美发助理/学徒',
  787: '美容店长',
  788: '足疗师',
  789: '按摩师',
  790: '美睫师',
  791: '采耳师',
  792: '发型师',
  793: '美甲师',
  794: '化妆师',
  795: '养发师',
  796: '理疗师',
  797: '针灸推拿',
  798: '美容师',
  799: '健身',
  800: '救生员',
  801: '瑜伽老师',
  802: '游泳教练',
  803: '舞蹈老师',
  804: '健身教练',
  805: '洗车工',
  806: '加油员',
  807: '汽车服务顾问',
  808: '汽车维修',
  809: '汽车美容',
  810: '汽车查勘定损',
  811: '二手车评估师',
  812: '4S店店长/维修站长',
  813: '汽车改装工程师',
  814: '花艺师',
  815: '婚礼策划',
  816: '宠物美容',
  817: '宠物医生',
  818: '保安',
  819: '保洁',
  820: '保姆',
  821: '月嫂',
  822: '育婴师',
  823: '护工',
  824: '安检员',
  825: '手机维修',
  826: '家电维修',
  827: '保安经理',
  828: '产后康复师',
  829: '钟点工',
  830: '押运员',
  831: '消防中控员',
  832: '保洁经理',
  833: '电脑维修',
  834: '网吧网管',
  835: '其他服务业职位',
  836: '环保工程师',
  837: '环评工程师',
  838: 'EHS工程师',
  839: '碳排放管理师',
  840: '环境检测员',
  841: '地质工程师',
  842: '光伏系统工程师',
  843: '风电运维工程师',
  844: '水利工程师',
  845: '厂务',
  846: '生产营运',
  847: '厂长',
  848: '生产总监',
  849: '车间主任',
  850: '生产组长/拉长',
  851: '生产设备管理员',
  852: '生产计划/物料管理(PMC)',
  853: '生产文员',
  854: '质检员',
  855: '计量工程师',
  856: '安全评价师',
  857: '质量管理/测试',
  858: '可靠度工程师',
  859: '失效分析工程师',
  860: '产品认证工程师',
  861: '体系工程师',
  862: '体系审核员',
  863: '生产安全员',
  864: '汽车质量工程师',
  865: '电池工程师',
  866: '电机工程师',
  867: '线束设计',
  868: '充电桩设计',
  869: '汽车设计',
  870: '车身/造型设计',
  871: '底盘工程师',
  872: '动力系统工程师',
  873: '汽车电子工程师',
  874: '汽车零部件设计',
  875: '汽车项目管理',
  876: '内外饰设计工程师',
  877: '总装工程师',
  878: '液压工程师',
  879: '机械设计/制造',
  880: '热设计工程师',
  881: '机械工程师',
  882: '机械设备工程师',
  883: '机械维修/保养',
  884: '机械制图员',
  885: '机械结构工程师',
  886: '工业工程师(IE)',
  887: '工艺工程师',
  888: '材料工程师',
  889: '机电工程师',
  890: 'CNC/数控',
  891: '冲压工程师',
  892: '夹具工程师',
  893: '模具工程师',
  894: '焊接工程师',
  895: '注塑工程师',
  896: '铸造/锻造工程师',
  897: '化工项目经理',
  898: '化工工程师',
  899: '实验室技术员',
  900: '涂料研发',
  901: '化妆品研发',
  902: '食品/饮料研发',
  903: '量体师',
  904: '服装/纺织设计',
  905: '面料辅料开发',
  906: '打样/制版',
  907: '服装/纺织/皮革跟单',
  908: '普工/操作工',
  909: '挖掘机司机',
  910: '弱电工',
  911: '裁剪工',
  912: '水电工',
  913: '叉车工',
  914: '铲车司机',
  915: '焊工',
  916: '氩弧焊工',
  917: '电工',
  918: '木工',
  919: '油漆工',
  920: '车工',
  921: '磨工',
  922: '铣工',
  923: '钳工',
  924: '钻工',
  925: '铆工',
  926: '钣金工',
  927: '抛光工',
  928: '机修工',
  929: '折弯工',
  930: '电镀工',
  931: '喷塑工',
  932: '注塑工',
  933: '组装工',
  934: '包装工',
  935: '空调工',
  936: '电梯工',
  937: '锅炉工',
  938: '学徒工',
  939: '缝纫工',
  940: '搬运工/装卸工',
  941: '切割工',
  942: '样衣工',
  943: '模具工',
  944: '其他生产制造职位'},
 'third_industry_url': {0: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100101',
  1: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100102',
  2: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100103',
  3: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100105',
  4: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100106',
  5: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100107',
  6: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100108',
  7: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100109',
  8: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100110',
  9: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100111',
  10: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100112',
  11: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100113',
  12: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100114',
  13: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100116',
  14: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100119',
  15: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100121',
  16: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100122',
  17: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100123',
  18: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100124',
  19: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100199',
  20: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100212',
  21: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100202',
  22: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100203',
  23: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100206',
  24: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100208',
  25: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100209',
  26: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100210',
  27: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100211',
  28: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100299',
  29: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100301',
  30: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100302',
  31: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100303',
  32: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100304',
  33: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100305',
  34: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100306',
  35: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100307',
  36: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100308',
  37: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100309',
  38: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100310',
  39: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100410',
  40: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100401',
  41: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100402',
  42: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100403',
  43: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100404',
  44: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100405',
  45: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100406',
  46: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100407',
  47: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100408',
  48: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100409',
  49: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100599',
  50: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100506',
  51: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100507',
  52: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100508',
  53: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100509',
  54: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100511',
  55: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100512',
  56: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100601',
  57: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100603',
  58: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100604',
  59: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100605',
  60: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100606',
  61: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100607',
  62: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100817',
  63: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100818',
  64: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100801',
  65: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100802',
  66: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100803',

In [98]:


up_dict.values()
# redis = get_redis()
# redis.

dict_values([{0: 'Java', 1: 'C++', 2: 'PHP', 3: 'C', 4: 'C#', 5: '.NET', 6: 'Hadoop', 7: 'Python', 8: 'Delphi', 9: 'VB', 10: 'Perl', 11: 'Ruby', 12: 'Node.js', 13: 'Golang', 14: 'Erlang', 15: '语音/视频/图形开发', 16: '数据采集', 17: '全栈工程师', 18: 'GIS工程师', 19: '后端开发', 20: '技术美术', 21: 'Android', 22: 'iOS', 23: 'Flash开发', 24: 'JavaScript', 25: 'U3D', 26: 'Cocos', 27: 'UE4', 28: '移动开发', 29: '测试工程师', 30: '自动化测试', 31: '功能测试', 32: '性能测试', 33: '测试开发', 34: '移动端测试', 35: '游戏测试', 36: '硬件测试', 37: '软件测试', 38: '渗透测试', 39: '技术文档工程师', 40: '运维工程师', 41: '运维开发工程师', 42: '网络工程师', 43: '系统工程师', 44: 'IT技术支持', 45: '系统管理员', 46: '网络安全', 47: '系统安全', 48: 'DBA', 49: '数据', 50: 'ETL工程师', 51: '数据仓库', 52: '数据开发', 53: '数据挖掘', 54: '数据分析师', 55: '数据架构师', 56: '项目经理/主管', 57: '项目助理', 58: '项目专员', 59: '实施顾问', 60: '实施工程师', 61: '需求分析工程师', 62: '硬件项目经理', 63: '光学工程师', 64: '硬件工程师', 65: '嵌入式', 66: '自动化', 67: '单片机', 68: '电路设计', 69: '驱动开发', 70: '系统集成', 71: 'FPGA开发', 72: 'DSP开发', 73: 'ARM开发', 74: 'PCB工艺', 75: '射频工程师', 76: '前端开发工程师', 77: 'Flash开发', 78: '通信技术工程师', 79: '通信研发工程师', 80: '数据通信工程师', 81: '移动通信工程师', 82: '电信网络工程师', 83: '电信交换工程师', 84: '有线传输工程师', 85: '无线/射频通信工程师', 86: '通信电源工程师', 87: '通信标准化工程师', 88: '通信项目专员', 89: '通信项目经理', 90: '核心网工程师', 91: '通信测试工程师', 92: '通信设备工程师', 93: '光通信工程师', 94: '光传输工程师', 95: '光网络工程师', 96: '版图设计工程师', 97: '电气工程师', 98: '电气设计工程师', 99: '电子工程师', 100: '集成电路IC设计', 101: 'FAE', 102: 'IC验证工程师', 103: '高端技术职位', 104: '技术经理', 105: '技术总监', 106: '测试经理', 107: '架构师', 108: 'CTO', 109: '运维总监', 110: '技术合伙人', 111: '人工智能', 112: '数据挖掘', 113: '搜索算法', 114: '自然语言处理', 115: '推荐算法', 116: '算法工程师', 117: '智能驾驶系统工程师', 118: '反欺诈/风控算法', 119: '机器学习', 120: '深度学习', 121: '语音识别', 122: '图像识别', 123: '算法研究员', 124: '销售技术支持', 125: '售前技术支持', 126: '售后技术支持', 127: '其他技术职位', 128: 'AI产品经理', 129: '化妆品产品经理', 130: '产品经理', 131: '移动产品经理', 132: '产品助理', 133: '数据产品经理', 134: '电商产品经理', 135: '游戏策划', 136: '产品专员', 137: '硬件产品经理', 138: '高级产品管理岗', 139: '游戏制作人', 140: '其他产品职位', 141: '视觉设计', 142: '视觉设计师', 143: '网页设计师', 144: 'Flash设计师', 145: 'UI设计师', 146: '平面设计', 147: '3D设计师', 148: '广告设计', 149: '多媒体设计师', 150: '原画师', 151: 'CAD设计/制图', 152: '美工', 153: '包装设计', 154: '设计师助理', 155: '动画设计', 156: '插画师', 157: '漫画师', 158: '人像修图师', 159: '交互设计师', 160: '系统策划', 161: '游戏主美术', 162: '游戏特效', 163: '游戏界面设计师', 164: '游戏场景', 165: '游戏角色', 166: '游戏动作', 167: '游戏数值策划', 168: '数据分析师', 169: '用户研究员', 170: 'UX设计师', 171: '用户研究经理', 172: '用户研究总监', 173: '高端设计职位', 174: '设计经理/主管', 175: '设计总监', 176: '视觉设计总监', 177: '非视觉设计', 178: '展览/展示设计', 179: '照明设计', 180: '服装/纺织设计', 181: '工业设计', 182: '橱柜设计', 183: '家具设计', 184: '家居设计', 185: '珠宝设计', 186: '室内设计', 187: '陈列设计', 188: '其他设计职位', 189: '淘宝运营', 190: '天猫运营', 191: '京东运营', 192: '拼多多运营', 193: '亚马逊运营', 194: '速卖通运营', 195: '阿里国际站运营', 196: '亚马逊产品开发', 197: '运营', 198: '用户运营', 199: '产品运营', 200: '数据/策略运营', 201: '内容运营', 202: '活动运营', 203: '商家运营', 204: '品类运营', 205: '游戏运营', 206: '网站运营', 207: '新媒体运营', 208: '社区运营', 209: '微信运营', 210: '线下拓展运营', 211: '国内电商运营', 212: '运营助理/专员', 213: '内容审核', 214: '数据标注/AI训练师', 215: '直播运营', 216: '车辆运营', 217: '跨境电商运营', 218: '视频运营', 219: '编辑', 220: '主编/副主编', 221: '文案编辑', 222: '网站编辑', 223: '采编', 224: '售前客服', 225: '售后客服', 226: '网络客服', 227: '客服经理', 228: '客服专员', 229: '客服主管', 230: '电话客服', 231: '咨询热线/呼叫中心客服', 232: '高端运营职位', 233: '运营总监', 234: 'COO', 235: '客服总监', 236: '运营经理/主管', 237: '其他运营职位', 238: '社工', 239: '政府关系', 240: '政策研究', 241: '企业党建', 242: '信息流优化师', 243: '网络推广', 244: '市场营销', 245: '市场策划', 246: '市场顾问', 247: '市场推广', 248: 'SEO', 249: 'SEM', 250: '商务渠道', 251: '商业数据分析', 252: '活动策划', 253: '网络营销', 254: '海外市场', 255: 'APP推广', 256: '选址开发', 257: '游戏推广', 258: '营销主管', 259: '公关媒介', 260: '媒介经理', 261: '广告客户执行', 262: '品牌公关', 263: '媒介专员', 264: '活动策划执行', 265: '媒介策划', 266: '会务会展', 267: '会议活动策划', 268: '会议活动执行', 269: '会展活动策划', 270: '会展活动执行', 271: '广告', 272: '广告/会展项目经理', 273: '广告创意设计', 274: '美术指导', 275: '广告设计', 276: '策划经理', 277: '广告文案', 278: '广告制作', 279: '媒介投放', 280: '媒介合作', 281: '广告审核', 282: '高端市场职位', 283: '市场总监', 284: 'CMO', 285: '公关总监', 286: '媒介总监', 287: '创意总监', 288: '其他市场职位', 289: '企业文化', 290: '招聘', 291: 'HRBP', 292: '人力资源专员/助理', 293: '培训', 294: '薪酬绩效', 295: '人力资源经理/主管', 296: '人力资源总监', 297: '员工关系', 298: '组织发展', 299: '文员', 300: '行政专员/助理', 301: '前台', 302: '经理助理', 303: '后勤', 304: '行政经理/主管', 305: '行政总监', 306: '建筑/工程会计', 307: '税务外勤会计', 308: '统计员', 309: '财务分析/财务BP', 310: '财务', 311: '会计', 312: '出纳', 313: '财务顾问', 314: '结算会计', 315: '税务', 316: '审计', 317: '成本会计', 318: '总账会计', 319: '财务经理/主管', 320: 'CFO', 321: '财务总监/VP', 322: '法务专员/助理', 323: '律师', 324: '法律顾问', 325: '法务经理/主管', 326: '法务总监', 327: '其他职能职位', 328: '高级管理职位', 329: '总裁/总经理/CEO', 330: '副总裁/副总经理/VP', 331: '分公司/代表处负责人', 332: '区域负责人(辖多个分公司)', 333: '总助/CEO助理/董事长助理', 334: '联合创始人', 335: '董事会秘书', 336: '商务专员', 337: '商务经理', 338: '客户成功', 339: '销售助理', 340: '商务总监', 341: '销售运营', 342: '置业顾问', 343: '地产中介', 344: '房地产销售/招商', 345: '物业招商管理', 346: '房地产销售总监', 347: '服装导购', 348: '化妆品导购', 349: '美容顾问', 350: '会籍顾问', 351: '珠宝销售', 352: '旅游顾问', 353: '瘦身顾问', 354: '汽车销售', 355: '汽车配件销售', 356: '广告销售', 357: '会议活动销售', 358: '会展活动销售', 359: '证券经纪人', 360: '信用卡销售', 361: '保险顾问', 362: '理财顾问', 363: '外贸经理', 364: '外贸业务员', 365: '销售专员', 366: '客户代表', 367: '大客户代表', 368: 'BD经理', 369: '渠道销售', 370: '代理商销售', 371: '电话销售', 372: '销售顾问', 373: '网络销售', 374: '销售工程师', 375: '客户经理', 376: '课程顾问', 377: '招生顾问', 378: '留学顾问', 379: '口腔咨询师', 380: '医疗销售', 381: '医疗器械销售', 382: '医药代表', 383: '健康顾问', 384: '医美咨询', 385: '销售经理', 386: '销售总监', 387: '区域总监', 388: '城市经理', 389: '销售VP', 390: '团队经理', 391: '其他销售职位', 392: '采编/写作/出版', 393: '印刷排版', 394: '记者/采编', 395: '编辑', 396: '作者/撰稿人', 397: '出版发行', 398: '校对录入', 399: '公关媒介', 400: '媒介经理', 401: '媒介专员', 402: '广告客户执行', 403: '品牌公关', 404: '活动策划执行', 405: '媒介策划', 406: '广告', 407: '广告/会展项目经理', 408: '广告创意设计', 409: '美术指导', 410: '广告设计', 411: '策划经理', 412: '广告文案', 413: '广告制作', 414: '媒介投放', 415: '媒介合作', 416: '广告审核', 417: '带货主播', 418: '剧本杀主持人', 419: '剧本杀编剧', 420: '儿童引导师', 421: '影视媒体', 422: '艺人助理', 423: '主持人/DJ', 424: '主播助理', 425: '灯光师', 426: '剪辑师', 427: '影视特效', 428: '导演/编导', 429: '摄影/摄像', 430: '视频编辑', 431: '音频编辑', 432: '经纪人', 433: '后期制作', 434: '影视发行', 435: '影视策划', 436: '主播', 437: '演员/配音/模特', 438: '化妆/造型/服装', 439: '放映员', 440: '录音/音效', 441: '制片人', 442: '编剧', 443: '其他传媒职位', 444: '买方分析师', 445: '基金经理', 446: '投资银行业务', 447: '量化研究员', 448: '证券/基金/期货', 449: '卖方分析师', 450: '证券交易员', 451: '投资者关系/证券事务代表', 452: '投融资', 453: '投资经理', 454: '行业研究', 455: '投资总监/VP', 456: '融资', 457: '并购', 458: '投后管理', 459: '投资助理', 460: '其他投融资职位', 461: '银行', 462: '柜员', 463: '客户经理', 464: '银行大堂经理', 465: '信贷专员', 466: '保险精算师', 467: '保险理赔', 468: '风控', 469: '金融产品经理', 470: '法务', 471: '资信评估', 472: '催收员', 473: '资产评估', 474: '合规稽查', 475: '清算', 476: '互联网金融', 477: '其他金融职位', 478: '教育产品研发', 479: '课程设计', 480: '课程编辑', 481: '培训研究', 482: '培训师', 483: '培训策划', 484: '其他教育产品研发职位', 485: '教育行政', 486: '园长/副园长', 487: '校长/副校长', 488: '教务管理', 489: '教学管理', 490: '班主任/辅导员', 491: '地理老师', 492: '教师', 493: '感统训练教师', 494: '日语教师', 495: '其他外语教师', 496: '语文教师', 497: '数学教师', 498: '物理教师', 499: '化学教师', 500: '生物教师', 501: '家教', 502: '托管老师', 503: '早教老师', 504: '助教', 505: '高中教师', 506: '初中教师', 507: '小学教师', 508: '幼教', 509: '理科教师', 510: '文科教师', 511: '英语教师', 512: '音乐教师', 513: '美术教师', 514: '体育教师/体育教练', 515: '就业老师', 516: 'IT培训', 517: 'JAVA培训讲师', 518: 'Android培训讲师', 519: 'iOS培训讲师', 520: 'PHP培训讲师', 521: '.NET培训讲师', 522: 'C++培训讲师', 523: 'Unity 3D培训讲师', 524: 'Web前端培训讲师', 525: '软件测试培训讲师', 526: '动漫培训讲师', 527: 'UI设计培训讲师', 528: '财会培训讲师', 529: '培训师', 530: '拓展培训', 531: '少儿编程老师', 532: '乒乓球教练', 533: '羽毛球教练', 534: '足球教练', 535: '架子鼓老师', 536: '教练', 537: '武术教练', 538: '轮滑教练', 539: '表演教师', 540: '机器人教师', 541: '书法教师', 542: '钢琴教师', 543: '吉他教师', 544: '古筝教师', 545: '播音主持教师', 546: '乐高教师', 547: '舞蹈老师', 548: '瑜伽老师', 549: '游泳教练', 550: '健身教练', 551: '篮球教练', 552: '跆拳道教练', 553: '其他教育培训职位', 554: '临床监查员', 555: '临床医学经理/专员', 556: '临床协调员', 557: '临床数据分析', 558: '临床项目经理', 559: '临床医学总监', 560: '其他医生职位', 561: '幼儿园保健医', 562: '外科医生', 563: '儿科医生', 564: '妇产科医生', 565: '眼科医生', 566: '皮肤科医生', 567: '耳鼻喉科医生', 568: '麻醉科医生', 569: '病理科医生', 570: '医务管理', 571: '医生助理', 572: '放射科医生', 573: '超声科医生', 574: '内科医生', 575: '全科医生', 576: '中医', 577: '整形医生', 578: '精神心理科医生', 579: '药剂师', 580: '口腔科医生', 581: '验光师', 582: '检验科医师', 583: '护士长', 584: '护士', 585: '导医', 586: '健康整形', 587: '营养师/健康管理师', 588: '康复治疗师', 589: '细胞培养员', 590: '药物分析', 591: '药物合成', 592: '医疗产品技术支持', 593: '生物信息工程师', 594: '生物学研究人员', 595: '药品注册', 596: '药品生产', 597: '医药项目经理', 598: '医药研发', 599: '试剂研发', 600: '医疗器械注册', 601: '医疗器械生产/质量管理', 602: '医疗器械研发', 603: '药店店长', 604: '执业药师/驻店药师', 605: '药店店员', 606: '医学编辑', 607: '其他医疗健康职位', 608: '招标专员', 609: '投标专员', 610: '采购', 611: '商品经理', 612: '供应商质量工程师', 613: '采购总监', 614: '采购经理/主管', 615: '采购专员/助理', 616: '买手', 617: '采购工程师', 618: '进出口贸易', 619: '贸易跟单', 620: '报关/报检员', 621: '单证员', 622: '其他采购/贸易类职位', 623: '配送站长', 624: '物流', 625: '供应链专员', 626: '供应链经理', 627: '集装箱管理', 628: '物流专员', 629: '物流经理', 630: '物流运营', 631: '物流跟单', 632: '调度员', 633: '物流/仓储项目经理', 634: '货运代理专员', 635: '货运代理经理', 636: '水/空/陆运操作', 637: '核销员', 638: '仓储', 639: '仓库经理', 640: '仓库管理员', 641: '仓库文员', 642: '配/理/拣/发货', 643: '无人机飞手', 644: '交通/运输', 645: '商务司机', 646: '网约车司机', 647: '代驾司机', 648: '驾校教练', 649: '货运司机', 650: '配送员', 651: '快递员', 652: '运输经理/主管', 653: '高端供应链职位', 654: '供应链总监', 655: '物流总监', 656: '其他供应链职位', 657: '室内设计', 658: '软装设计师', 659: '装修项目经理', 660: '工程监理', 661: '工程造价', 662: '工程预算', 663: '资料员', 664: '建筑施工项目经理', 665: '施工员', 666: '测绘/测量', 667: '材料员', 668: '施工安全员', 669: '房地产规划开发', 670: '房地产策划', 671: '地产项目管理', 672: '地产招投标', 673: '房产评估师', 674: '设计装修与市政建设', 675: '建筑工程师', 676: '建筑设计师', 677: '土木/土建/结构工程师', 678: '园林/景观设计', 679: '城市规划设计', 680: '弱电工程师', 681: '给排水工程师', 682: '暖通工程师', 683: '幕墙工程师', 684: 'BIM工程师', 685: '建筑机电工程师', 686: '消防工程师', 687: '物业经理', 688: '综合维修工', 689: '绿化工', 690: '物业管理员', 691: '高端房地产职位', 692: '地产项目总监', 693: '地产策划总监', 694: '地产招投标总监', 695: '其他房地产职位', 696: '农业/林业技术员', 697: '饲养员', 698: '禽畜/水产养殖技术员', 699: '畜牧兽医', 700: '咨询/调研', 701: '知识产权/专利/商标代理人', 702: '心理咨询师', 703: '婚恋咨询师', 704: '企业管理咨询', 705: '咨询总监', 706: '数据分析师', 707: '咨询经理', 708: '财务咨询顾问', 709: 'IT咨询顾问', 710: '人力资源咨询顾问', 711: '咨询项目管理', 712: '战略咨询', 713: '猎头顾问', 714: '市场调研', 715: '其他咨询顾问', 716: '专利律师', 717: '知识产权律师', 718: '律师助理', 719: '事务所律师', 720: '法务', 721: '英语翻译', 722: '日语翻译', 723: '韩语/朝鲜语翻译', 724: '法语翻译', 725: '德语翻译', 726: '俄语翻译', 727: '西班牙语翻译', 728: '其他语种翻译', 729: '其他咨询/翻译类职位', 730: '旅游服务', 731: '计调', 732: '签证专员', 733: '导游', 734: '预定票务', 735: '讲解员', 736: '旅游产品开发/策划', 737: '旅游产品经理', 738: '旅游策划师', 739: '其他旅游职位', 740: '奶茶店店员', 741: '水台', 742: '面包/烘焙师', 743: '餐饮储备店长/干部', 744: '调酒师', 745: '餐饮', 746: '后厨', 747: '配菜打荷', 748: '茶艺师', 749: '蛋糕/裱花师', 750: '餐饮学徒', 751: '面点师', 752: '行政总厨', 753: '厨师长', 754: '传菜员', 755: '洗碗工', 756: '凉菜厨师', 757: '中餐厨师', 758: '西餐厨师', 759: '日料厨师', 760: '烧烤师傅', 761: '收银', 762: '服务员', 763: '厨师', 764: '咖啡师', 765: '送餐员', 766: '餐饮店长', 767: '前厅经理/领班', 768: '民宿管家', 769: '礼仪/迎宾/接待', 770: '酒店前厅经理', 771: '客房经理', 772: '酒店前台', 773: '客房服务员', 774: '酒店经理', 775: '督导/巡店', 776: '陈列员', 777: '理货员', 778: '防损员', 779: '卖场经理', 780: '促销员', 781: '导购', 782: '店员/营业员', 783: '门店店长', 784: '纹绣师', 785: '美体师', 786: '美发助理/学徒', 787: '美容店长', 788: '足疗师', 789: '按摩师', 790: '美睫师', 791: '采耳师', 792: '发型师', 793: '美甲师', 794: '化妆师', 795: '养发师', 796: '理疗师', 797: '针灸推拿', 798: '美容师', 799: '健身', 800: '救生员', 801: '瑜伽老师', 802: '游泳教练', 803: '舞蹈老师', 804: '健身教练', 805: '洗车工', 806: '加油员', 807: '汽车服务顾问', 808: '汽车维修', 809: '汽车美容', 810: '汽车查勘定损', 811: '二手车评估师', 812: '4S店店长/维修站长', 813: '汽车改装工程师', 814: '花艺师', 815: '婚礼策划', 816: '宠物美容', 817: '宠物医生', 818: '保安', 819: '保洁', 820: '保姆', 821: '月嫂', 822: '育婴师', 823: '护工', 824: '安检员', 825: '手机维修', 826: '家电维修', 827: '保安经理', 828: '产后康复师', 829: '钟点工', 830: '押运员', 831: '消防中控员', 832: '保洁经理', 833: '电脑维修', 834: '网吧网管', 835: '其他服务业职位', 836: '环保工程师', 837: '环评工程师', 838: 'EHS工程师', 839: '碳排放管理师', 840: '环境检测员', 841: '地质工程师', 842: '光伏系统工程师', 843: '风电运维工程师', 844: '水利工程师', 845: '厂务', 846: '生产营运', 847: '厂长', 848: '生产总监', 849: '车间主任', 850: '生产组长/拉长', 851: '生产设备管理员', 852: '生产计划/物料管理(PMC)', 853: '生产文员', 854: '质检员', 855: '计量工程师', 856: '安全评价师', 857: '质量管理/测试', 858: '可靠度工程师', 859: '失效分析工程师', 860: '产品认证工程师', 861: '体系工程师', 862: '体系审核员', 863: '生产安全员', 864: '汽车质量工程师', 865: '电池工程师', 866: '电机工程师', 867: '线束设计', 868: '充电桩设计', 869: '汽车设计', 870: '车身/造型设计', 871: '底盘工程师', 872: '动力系统工程师', 873: '汽车电子工程师', 874: '汽车零部件设计', 875: '汽车项目管理', 876: '内外饰设计工程师', 877: '总装工程师', 878: '液压工程师', 879: '机械设计/制造', 880: '热设计工程师', 881: '机械工程师', 882: '机械设备工程师', 883: '机械维修/保养', 884: '机械制图员', 885: '机械结构工程师', 886: '工业工程师(IE)', 887: '工艺工程师', 888: '材料工程师', 889: '机电工程师', 890: 'CNC/数控', 891: '冲压工程师', 892: '夹具工程师', 893: '模具工程师', 894: '焊接工程师', 895: '注塑工程师', 896: '铸造/锻造工程师', 897: '化工项目经理', 898: '化工工程师', 899: '实验室技术员', 900: '涂料研发', 901: '化妆品研发', 902: '食品/饮料研发', 903: '量体师', 904: '服装/纺织设计', 905: '面料辅料开发', 906: '打样/制版', 907: '服装/纺织/皮革跟单', 908: '普工/操作工', 909: '挖掘机司机', 910: '弱电工', 911: '裁剪工', 912: '水电工', 913: '叉车工', 914: '铲车司机', 915: '焊工', 916: '氩弧焊工', 917: '电工', 918: '木工', 919: '油漆工', 920: '车工', 921: '磨工', 922: '铣工', 923: '钳工', 924: '钻工', 925: '铆工', 926: '钣金工', 927: '抛光工', 928: '机修工', 929: '折弯工', 930: '电镀工', 931: '喷塑工', 932: '注塑工', 933: '组装工', 934: '包装工', 935: '空调工', 936: '电梯工', 937: '锅炉工', 938: '学徒工', 939: '缝纫工', 940: '搬运工/装卸工', 941: '切割工', 942: '样衣工', 943: '模具工', 944: '其他生产制造职位'}, {0: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100101', 1: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100102', 2: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100103', 3: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100105', 4: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100106', 5: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100107', 6: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100108', 7: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100109', 8: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100110', 9: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100111', 10: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100112', 11: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100113', 12: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100114', 13: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100116', 14: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100119', 15: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100121', 16: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100122', 17: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100123', 18: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100124', 19: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100199', 20: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100212', 21: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100202', 22: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100203', 23: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100206', 24: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100208', 25: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100209', 26: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100210', 27: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100211', 28: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100299', 29: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100301', 30: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100302', 31: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100303', 32: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100304', 33: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100305', 34: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100306', 35: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100307', 36: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100308', 37: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100309', 38: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100310', 39: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100410', 40: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100401', 41: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100402', 42: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100403', 43: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100404', 44: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100405', 45: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100406', 46: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100407', 47: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100408', 48: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100409', 49: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100599', 50: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100506', 51: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100507', 52: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100508', 53: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100509', 54: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100511', 55: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100512', 56: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100601', 57: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100603', 58: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100604', 59: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100605', 60: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100606', 61: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100607', 62: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100817', 63: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100818', 64: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100801', 65: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100802', 66: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100803', 67: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100804', 68: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100805', 69: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100806', 70: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100807', 71: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100808', 72: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100809', 73: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100810', 74: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100811', 75: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100816', 76: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100901', 77: 'https://www.zhipin.com/web/geek/job?city=100010000&position=100903', 78: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101001', 79: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101002', 80: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101003', 81: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101004', 82: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101005', 83: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101006', 84: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101007', 85: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101008', 86: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101009', 87: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101010', 88: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101011', 89: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101012', 90: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101013', 91: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101014', 92: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101015', 93: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101016', 94: 'https://www.zhipin.com/web/geek/job?city=100010000&position=101017', 95: 'https://www.zhipin.c

In [115]:
job_list = list()

for i in up_df.columns:
    print(i)

first_industry
second_industry
third_industry
third_industry_url

In [44]:
mongo.insert_many('job2', up_df.values)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 提取 行业url到redis

In [6]:
from spider.coroutine_crawl import construct_recruitment_url,RECRUITMENT_URL
from store.db.db_store import Mongo
m = Mongo()
find: list = m.find("industry_info", columns_conditions={"_id": 0, "third_industry": 1, "third_industry_url": 1})
for item in find:
    p = item.get("third_industry_url").split("-")[1].rstrip("/")
    construct_recruitment_url(RECRUITMENT_URL, position=p)
    item["third_industry_url"] = construct_recruitment_url(RECRUITMENT_URL, position=p)
    m.update_one("industry_info",{"third_industry":item.get("third_industry")},{"third_industry_url":item["third_industry_url"]})

find

[{'third_industry': 'Java',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100101'},
 {'third_industry': 'C++',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100102'},
 {'third_industry': 'PHP',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100103'},
 {'third_industry': 'C',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100105'},
 {'third_industry': 'C#',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100106'},
 {'third_industry': '.NET',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100107'},
 {'third_industry': 'Hadoop',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100108'},
 {'third_industry': 'Python',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100109'},
 {'third_industry': 'Delphi',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100110'},
 {'third_industry': 'VB',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100111'},
 {'third_industry': 'Perl',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100112'},
 {'third_industry': 'Ruby',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100113'},
 {'third_industry': 'Node.js',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100114'},
 {'third_industry': 'Golang',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100116'},
 {'third_industry': 'Erlang',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100119'},
 {'third_industry': '语音/视频/图形开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100121'},
 {'third_industry': '数据采集',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100122'},
 {'third_industry': '全栈工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100123'},
 {'third_industry': 'GIS工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100124'},
 {'third_industry': '后端开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100199'},
 {'third_industry': '技术美术',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100212'},
 {'third_industry': 'Android',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100202'},
 {'third_industry': 'iOS',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100203'},
 {'third_industry': 'Flash开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100206'},
 {'third_industry': 'JavaScript',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100208'},
 {'third_industry': 'U3D',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100209'},
 {'third_industry': 'Cocos',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100210'},
 {'third_industry': 'UE4',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100211'},
 {'third_industry': '移动开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100299'},
 {'third_industry': '测试工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100301'},
 {'third_industry': '自动化测试',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100302'},
 {'third_industry': '功能测试',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100303'},
 {'third_industry': '性能测试',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100304'},
 {'third_industry': '测试开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100305'},
 {'third_industry': '移动端测试',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100306'},
 {'third_industry': '游戏测试',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100307'},
 {'third_industry': '硬件测试',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100308'},
 {'third_industry': '软件测试',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100309'},
 {'third_industry': '渗透测试',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100310'},
 {'third_industry': '技术文档工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100410'},
 {'third_industry': '运维工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100401'},
 {'third_industry': '运维开发工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100402'},
 {'third_industry': '网络工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100403'},
 {'third_industry': '系统工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100404'},
 {'third_industry': 'IT技术支持',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100405'},
 {'third_industry': '系统管理员',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100406'},
 {'third_industry': '网络安全',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100407'},
 {'third_industry': '系统安全',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100408'},
 {'third_industry': 'DBA',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100409'},
 {'third_industry': '数据',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100599'},
 {'third_industry': 'ETL工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100506'},
 {'third_industry': '数据仓库',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100507'},
 {'third_industry': '数据开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100508'},
 {'third_industry': '数据挖掘',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100509'},
 {'third_industry': '数据分析师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100511'},
 {'third_industry': '数据架构师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100512'},
 {'third_industry': '项目经理/主管',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100601'},
 {'third_industry': '项目助理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100603'},
 {'third_industry': '项目专员',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100604'},
 {'third_industry': '实施顾问',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100605'},
 {'third_industry': '实施工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100606'},
 {'third_industry': '需求分析工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100607'},
 {'third_industry': '硬件项目经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100817'},
 {'third_industry': '光学工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100818'},
 {'third_industry': '硬件工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100801'},
 {'third_industry': '嵌入式',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100802'},
 {'third_industry': '自动化',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100803'},
 {'third_industry': '单片机',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100804'},
 {'third_industry': '电路设计',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100805'},
 {'third_industry': '驱动开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100806'},
 {'third_industry': '系统集成',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100807'},
 {'third_industry': 'FPGA开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100808'},
 {'third_industry': 'DSP开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100809'},
 {'third_industry': 'ARM开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100810'},
 {'third_industry': 'PCB工艺',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100811'},
 {'third_industry': '射频工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100816'},
 {'third_industry': '前端开发工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100901'},
 {'third_industry': 'Flash开发',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100903'},
 {'third_industry': '通信技术工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101001'},
 {'third_industry': '通信研发工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101002'},
 {'third_industry': '数据通信工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101003'},
 {'third_industry': '移动通信工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101004'},
 {'third_industry': '电信网络工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101005'},
 {'third_industry': '电信交换工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101006'},
 {'third_industry': '有线传输工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101007'},
 {'third_industry': '无线/射频通信工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101008'},
 {'third_industry': '通信电源工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101009'},
 {'third_industry': '通信标准化工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101010'},
 {'third_industry': '通信项目专员',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101011'},
 {'third_industry': '通信项目经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101012'},
 {'third_industry': '核心网工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101013'},
 {'third_industry': '通信测试工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101014'},
 {'third_industry': '通信设备工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101015'},
 {'third_industry': '光通信工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101016'},
 {'third_industry': '光传输工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101017'},
 {'third_industry': '光网络工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101018'},
 {'third_industry': '版图设计工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101407'},
 {'third_industry': '电气工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101402'},
 {'third_industry': '电气设计工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101404'},
 {'third_industry': '电子工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101401'},
 {'third_industry': '集成电路IC设计',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101405'},
 {'third_industry': 'FAE',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101403'},
 {'third_industry': 'IC验证工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101406'},
 {'third_industry': '高端技术职位',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100799'},
 {'third_industry': '技术经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100701'},
 {'third_industry': '技术总监',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100702'},
 {'third_industry': '测试经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100703'},
 {'third_industry': '架构师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100704'},
 {'third_industry': 'CTO',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100705'},
 {'third_industry': '运维总监',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100706'},
 {'third_industry': '技术合伙人',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100707'},
 {'third_industry': '人工智能',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101399'},
 {'third_industry': '数据挖掘',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100104'},
 {'third_industry': '搜索算法',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100115'},
 {'third_industry': '自然语言处理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100117'},
 {'third_industry': '推荐算法',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100118'},
 {'third_industry': '算法工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100120'},
 {'third_industry': '智能驾驶系统工程师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101308'},
 {'third_industry': '反欺诈/风控算法',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101309'},
 {'third_industry': '机器学习',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101301'},
 {'third_industry': '深度学习',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101302'},
 {'third_industry': '语音识别',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101305'},
 {'third_industry': '图像识别',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101306'},
 {'third_industry': '算法研究员',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101307'},
 {'third_industry': '销售技术支持',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101299'},
 {'third_industry': '售前技术支持',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101201'},
 {'third_industry': '售后技术支持',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101202'},
 {'third_industry': '其他技术职位',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101101'},
 {'third_industry': 'AI产品经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110110'},
 {'third_industry': '化妆品产品经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110111'},
 {'third_industry': '产品经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110101'},
 {'third_industry': '移动产品经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110103'},
 {'third_industry': '产品助理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110104'},
 {'third_industry': '数据产品经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110105'},
 {'third_industry': '电商产品经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110106'},
 {'third_industry': '游戏策划',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110107'},
 {'third_industry': '产品专员',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110108'},
 {'third_industry': '硬件产品经理',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110109'},
 {'third_industry': '高级产品管理岗',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110302'},
 {'third_industry': '游戏制作人',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110303'},
 {'third_industry': '其他产品职位',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110401'},
 {'third_industry': '视觉设计',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120199'},
 {'third_industry': '视觉设计师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120101'},
 {'third_industry': '网页设计师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120102'},
 {'third_industry': 'Flash设计师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120103'},
 {'third_industry': 'UI设计师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120105'},
 {'third_industry': '平面设计',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120106'},
 {'third_industry': '3D设计师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120107'},
 {'third_industry': '广告设计',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120108'},
 {'third_industry': '多媒体设计师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120109'},
 {'third_industry': '原画师',
  'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120110'},
 {'third_industry': 'CAD设计/制图',

In [102]:
from store.db.db_store import get_redis

redis = get_redis()

In [93]:
di = [(i["third_industry"],i["third_industry_url"]) for i in find]
di

[('Java',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100101'),
 ('C++',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100102'),
 ('PHP',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100103'),
 ('C',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100105'),
 ('C#',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100106'),
 ('.NET',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100107'),
 ('Hadoop',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100108'),
 ('Python',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100109'),
 ('Delphi',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100110'),
 ('VB',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100111'),
 ('Perl',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100112'),
 ('Ruby',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100113'),
 ('Node.js',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100114'),
 ('Golang',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100116'),
 ('Erlang',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100119'),
 ('语音/视频/图形开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100121'),
 ('数据采集',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100122'),
 ('全栈工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100123'),
 ('GIS工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100124'),
 ('后端开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100199'),
 ('技术美术',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100212'),
 ('Android',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100202'),
 ('iOS',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100203'),
 ('Flash开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100206'),
 ('JavaScript',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100208'),
 ('U3D',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100209'),
 ('Cocos',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100210'),
 ('UE4',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100211'),
 ('移动开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100299'),
 ('测试工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100301'),
 ('自动化测试',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100302'),
 ('功能测试',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100303'),
 ('性能测试',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100304'),
 ('测试开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100305'),
 ('移动端测试',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100306'),
 ('游戏测试',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100307'),
 ('硬件测试',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100308'),
 ('软件测试',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100309'),
 ('渗透测试',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100310'),
 ('技术文档工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100410'),
 ('运维工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100401'),
 ('运维开发工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100402'),
 ('网络工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100403'),
 ('系统工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100404'),
 ('IT技术支持',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100405'),
 ('系统管理员',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100406'),
 ('网络安全',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100407'),
 ('系统安全',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100408'),
 ('DBA',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100409'),
 ('数据',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100599'),
 ('ETL工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100506'),
 ('数据仓库',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100507'),
 ('数据开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100508'),
 ('数据挖掘',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100509'),
 ('数据分析师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100511'),
 ('数据架构师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100512'),
 ('项目经理/主管',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100601'),
 ('项目助理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100603'),
 ('项目专员',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100604'),
 ('实施顾问',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100605'),
 ('实施工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100606'),
 ('需求分析工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100607'),
 ('硬件项目经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100817'),
 ('光学工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100818'),
 ('硬件工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100801'),
 ('嵌入式',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100802'),
 ('自动化',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100803'),
 ('单片机',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100804'),
 ('电路设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100805'),
 ('驱动开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100806'),
 ('系统集成',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100807'),
 ('FPGA开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100808'),
 ('DSP开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100809'),
 ('ARM开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100810'),
 ('PCB工艺',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100811'),
 ('射频工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100816'),
 ('前端开发工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100901'),
 ('Flash开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100903'),
 ('通信技术工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101001'),
 ('通信研发工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101002'),
 ('数据通信工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101003'),
 ('移动通信工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101004'),
 ('电信网络工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101005'),
 ('电信交换工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101006'),
 ('有线传输工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101007'),
 ('无线/射频通信工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101008'),
 ('通信电源工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101009'),
 ('通信标准化工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101010'),
 ('通信项目专员',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101011'),
 ('通信项目经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101012'),
 ('核心网工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101013'),
 ('通信测试工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101014'),
 ('通信设备工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101015'),
 ('光通信工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101016'),
 ('光传输工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101017'),
 ('光网络工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101018'),
 ('版图设计工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101407'),
 ('电气工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101402'),
 ('电气设计工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101404'),
 ('电子工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101401'),
 ('集成电路IC设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101405'),
 ('FAE',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101403'),
 ('IC验证工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101406'),
 ('高端技术职位',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100799'),
 ('技术经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100701'),
 ('技术总监',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100702'),
 ('测试经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100703'),
 ('架构师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100704'),
 ('CTO',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100705'),
 ('运维总监',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100706'),
 ('技术合伙人',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100707'),
 ('人工智能',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101399'),
 ('数据挖掘',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100104'),
 ('搜索算法',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100115'),
 ('自然语言处理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100117'),
 ('推荐算法',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100118'),
 ('算法工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100120'),
 ('智能驾驶系统工程师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101308'),
 ('反欺诈/风控算法',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101309'),
 ('机器学习',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101301'),
 ('深度学习',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101302'),
 ('语音识别',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101305'),
 ('图像识别',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101306'),
 ('算法研究员',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101307'),
 ('销售技术支持',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101299'),
 ('售前技术支持',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101201'),
 ('售后技术支持',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101202'),
 ('其他技术职位',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p101101'),
 ('AI产品经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110110'),
 ('化妆品产品经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110111'),
 ('产品经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110101'),
 ('移动产品经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110103'),
 ('产品助理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110104'),
 ('数据产品经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110105'),
 ('电商产品经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110106'),
 ('游戏策划',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110107'),
 ('产品专员',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110108'),
 ('硬件产品经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110109'),
 ('高级产品管理岗',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110302'),
 ('游戏制作人',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110303'),
 ('其他产品职位',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p110401'),
 ('视觉设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120199'),
 ('视觉设计师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120101'),
 ('网页设计师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120102'),
 ('Flash设计师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120103'),
 ('UI设计师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120105'),
 ('平面设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120106'),
 ('3D设计师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120107'),
 ('广告设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120108'),
 ('多媒体设计师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120109'),
 ('原画师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120110'),
 ('CAD设计/制图',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120116'),
 ('美工',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120117'),
 ('包装设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120118'),
 ('设计师助理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120119'),
 ('动画设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120120'),
 ('插画师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120121'),
 ('漫画师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120122'),
 ('人像修图师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120123'),
 ('交互设计师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120201'),
 ('系统策划',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120305'),
 ('游戏主美术',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120306'),
 ('游戏特效',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120111'),
 ('游戏界面设计师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120112'),
 ('游戏场景',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120113'),
 ('游戏角色',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120114'),
 ('游戏动作',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120115'),
 ('游戏数值策划',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120303'),
 ('数据分析师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120301'),
 ('用户研究员',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120302'),
 ('UX设计师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120304'),
 ('用户研究经理',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120407'),
 ('用户研究总监',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120408'),
 ('高端设计职位',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120499'),
 ('设计经理/主管',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120401'),
 ('设计总监',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120402'),
 ('视觉设计总监',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120404'),
 ('非视觉设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120699'),
 ('展览/展示设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120611'),
 ('照明设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120612'),
 ('服装/纺织设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120601'),
 ('工业设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120602'),
 ('橱柜设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120603'),
 ('家具设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120604'),
 ('家居设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120605'),
 ('珠宝设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120606'),
 ('室内设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120607'),
 ('陈列设计',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120608'),
 ('其他设计职位',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p120501'),
 ('淘宝运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130126'),
 ('天猫运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130127'),
 ('京东运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130128'),
 ('拼多多运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130129'),
 ('亚马逊运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130130'),
 ('速卖通运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130131'),
 ('阿里国际站运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130132'),
 ('亚马逊产品开发',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130133'),
 ('运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130199'),
 ('用户运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130101'),
 ('产品运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130102'),
 ('数据/策略运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130103'),
 ('内容运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130104'),
 ('活动运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130105'),
 ('商家运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130106'),
 ('品类运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130107'),
 ('游戏运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130108'),
 ('网站运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130110'),
 ('新媒体运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130111'),
 ('社区运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130112'),
 ('微信运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130113'),
 ('线下拓展运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130116'),
 ('国内电商运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130117'),
 ('运营助理/专员',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130118'),
 ('内容审核',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130120'),
 ('数据标注/AI训练师',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130121'),
 ('直播运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130122'),
 ('车辆运营',
  'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p130123'),
 ('跨境电商运营',

In [82]:
for i in di:
    redis.hset("industry_info",i[0],i[1])

In [103]:
redis.keys()

AuthenticationError: Authentication required.

In [86]:
redis.hgetall("industry_info")

dict_keys(['法律顾问', '其他采购/贸易类职位', '音乐教师', 'VB', '硬件工程师', '影视策划', '少儿编程老师', '核销员', '工业设计', 'Flash开发', '视频运营', 'JAVA培训讲师', '网站运营', '光通信工程师', '证券经纪人', '园林/景观设计', '其他教育培训职位', '模具工程师', '产品认证工程师', '服务员', '其他投融资职位', '麻醉科医生', '高级管理职位', '配/理/拣/发货', '验光师', '产品运营', '地理老师', '瘦身顾问', '花艺师', '失效分析工程师', '家具设计', '汽车电子工程师', '药物分析', '钳工', '样衣工', '车身/造型设计', '体系工程师', 'APP推广', '高级产品管理岗', '网络营销', '核心网工程师', '行政经理/主管', '网吧网管', '区域负责人(辖多个分公司)', '液压工程师', '临床监查员', '速卖通运营', '配送站长', '汽车美容', '3D设计师', '机修工', '商业数据分析', '挖掘机司机', '反欺诈/风控算法', '游戏数值策划', 'Node.js', '仓库经理', '供应链经理', '网络工程师', '电气工程师', '篮球教练', '游戏测试', '作者/撰稿人', '医疗产品技术支持', '资信评估', '其他教育产品研发职位', '保安经理', '货运代理专员', '单证员', '咨询/调研', '培训', '税务', '保洁经理', '信用卡销售', '培训研究', 'C#', '商务总监', '中医', '版图设计工程师', 'PCB工艺', '课程编辑', '清算', 'Web前端培训讲师', '高中教师', 'C++', '互联网金融', '药品注册', '区域总监', '主播', '集装箱管理', '深度学习', '财务咨询顾问', '投资经理', '报关/报检员', '卖场经理', '体系审核员', '政策研究', '消防中控员', '测绘/测量', '咨询项目管理', '机电工程师', '物流总监', '运维工程师', '银行大堂经理', '网络推广', '足疗师', '设计装修与市政建设', '通信项目专员', '机械设计/制造', '防损员', '光网络工程师', '汽车改装工程师', '乒乓球教练', '联合创始人', '厨师', '数据架构师', '综合维修工', '机器学习', '城市经理', '酒店前台', 'C', '团队经理', '日语翻译', '奶茶店店员', '投标专员', '语音/视频/图形开发', '催收员', '口腔咨询师', '信贷专员', '活动策划执行', '地质工程师', '服装导购', '网站编辑', '食品/饮料研发', '移动端测试', '美术教师', '幼教', '注塑工', '采购', '武术教练', '早教老师', '导购', '运营助理/专员', '商家运营', '实验室技术员', '工程预算', '其他外语教师', '阿里国际站运营', '机械工程师', '美容店长', '文科教师', '人力资源总监', '嵌入式', '古筝教师', '艺人助理', '商务渠道', '细胞培养员', '厂长', '企业管理咨询', '橱柜设计', '销售运营', '行政专员/助理', '铲车司机', '代理商销售', '投资助理', '品类运营', '技术合伙人', '展览/展示设计', '电气设计工程师', '视频编辑', 'EHS工程师', '签证专员', '招聘', '采购工程师', '宠物美容', '幕墙工程师', '天猫运营', '商务经理', '网页设计师', '培训策划', '保险顾问', '医药代表', '销售助理', '注塑工程师', '电池工程师', '采购经理/主管', '编辑', '人像修图师', '旅游顾问', '移动产品经理', '留学顾问', '京东运营', '美体师', '执业药师/驻店药师', '课程顾问', '瑜伽老师', '买方分析师', '幼儿园保健医', '照明设计', '通信研发工程师', '其他服务业职位', '信息流优化师', '跨境电商运营', '汽车服务顾问', '喷塑工', 'PHP培训讲师', '其他旅游职位', '咨询总监', '其他设计职位', '班主任/辅导员', '跆拳道教练', '抛光工', '客房经理', '中餐厨师', '厨师长', '驱动开发', '功能测试', '消防工程师', '运营经理/主管', '化妆品产品经理', '汽车配件销售', '打样/制版', '会计', '董事会秘书', '空调工', '量体师', '地产招投标总监', '媒介经理', '音频编辑', '后厨', '表演教师', '面点师', '会务会展', '影视特效', '平面设计', '全科医生', '语文教师', '渗透测试', '集成电路IC设计', '车间主任', 'Java', '系统安全', 'Erlang', '智能驾驶系统工程师', '临床协调员', '物流专员', 'HRBP', '需求分析工程师', '外科医生', '软装设计师', '钢琴教师', '证券交易员', '教师', '舞蹈老师', '木工', '咖啡师', '活动运营', '投后管理', '环评工程师', '客服专员', '电工', '客户经理', 'UE4', '销售经理', 'PHP', '机械维修/保养', '房产评估师', '数据开发', 'Android', '投资银行业务', '水/空/陆运操作', '会籍顾问', '美容师', '数据挖掘', '播音主持教师', '数据', '土木/土建/结构工程师', '法务经理/主管', '其他供应链职位', '游戏动作', '知识产权/专利/商标代理人', '药店店员', '其他运营职位', 'Unity 3D培训讲师', '陈列员', '投融资', '物流运营', '仓库管理员', '项目经理/主管', '农业/林业技术员', '经理助理', '客户代表', '调度员', '家居设计', '珠宝销售', '分公司/代表处负责人', '乐高教师', '营销主管', '儿科医生', '营养师/健康管理师', '服装/纺织设计', '广告文案', '广告', '技术经理', '商务司机', '统计员', '茶艺师', '硬件产品经理', '电镀工', '生产文员', '建筑工程师', '课程设计', 'SEO', '架构师', '保洁', '教务管理', '试剂研发', '机械结构工程师', '美发助理/学徒', '内容运营', '光传输工程师', '游泳教练', '系统集成', '房地产策划', '动力系统工程师', '化工项目经理', '化妆师', '网络销售', '押运员', '育婴师', 'Delphi', 'Cocos', '教育产品研发', '汽车零部件设计', '广告客户执行', '旅游产品经理', '采编', '量化研究员', '高端市场职位', '理科教师', '药品生产', '暖通工程师', '审计', '运维开发工程师', '其他销售职位', '出版发行', '配菜打荷', '西班牙语翻译', '客服总监', '软件测试培训讲师', '保安', '叉车工', '保姆', '生产安全员', '其他市场职位', '建筑设计师', '针灸推拿', '后端开发', '电商产品经理', '教学管理', '临床项目经理', '保险理赔', '财务', '餐饮', '英语教师', '婚恋咨询师', '物业经理', '前厅经理/领班', '置业顾问', '数学教师', '健康整形', 'U3D', '助教', '讲解员', '生产总监', '社工', '媒介总监', '自动化测试', '编剧', '水利工程师', '导医', '弱电工', '化学教师', '商品经理', '直播运营', '餐饮店长', 'SEM', '实施工程师', '4S店店长/维修站长', '投资总监/VP', '高端技术职位', '钟点工', '市场推广', '国内电商运营', '市场顾问', '汽车维修', '射频工程师', '有线传输工程师', '并购', '康复治疗师', '企业文化', '安全评价师', '收银', '餐饮学徒', '驾校教练', '内容审核', '光学工程师', '薪酬绩效', '律师助理', '渠道销售', '小学教师', '氩弧焊工', '员工关系', '技术总监', '原画师', '结算会计', '医学编辑', '亚马逊产品开发', '客户成功', '感统训练教师', '自动化', '旅游策划师', '交互设计师', '手机维修', '培训师', '品牌公关', '柜员', '人力资源专员/助理', '其他咨询顾问', '畜牧兽医', 'DBA', '书法教师', '采耳师', '测试经理', '总裁/总经理/CEO', '物流经理', '会展活动销售', '剧本杀编剧', '算法研究员', '游戏运营', '通信技术工程师', '病理科医生', '律师', '焊接工程师', '文员', '数据/策略运营', '化工工程师', '行政总监', '出纳', '化妆品导购', '材料员', '用户研究员', '洗车工', '酒店经理', '物流跟单', '旅游服务', '硬件测试', '战略咨询', '建筑/工程会计', '资产评估', '传菜员', '英语翻译', 'UI设计师', '心理咨询师', '物业招商管理', '服装/纺织/皮革跟单', '生物信息工程师', '财务经理/主管', '整形医生', '养发师', '饲养员', '质量管理/测试', '涂料研发', '社区运营', '卖方分析师', '单片机', '外贸经理', '印刷排版', '制片人', '吉他教师', '会议活动策划', '切割工', '生物教师', '环境检测员', '店员/营业员', '护士长', 'CNC/数控', '预定票务', '软件测试', '日语教师', '电梯工', 'ARM开发', '督导/巡店', '前台', 'CMO', '健康顾问', '采编/写作/出版', '热设计工程师', '用户研究经理', '游戏特效', '救生员', '测试开发', '剧本杀主持人', '后勤', '发型师', '视觉设计总监', '检验科医师', '医药项目经理', 'CAD设计/制图', '建筑施工项目经理', 'BD经理', '拓展培训', '销售总监', '漫画师', 'IT技术支持', '汽车项目管理', '宠物医生', '影视发行', '禽畜/水产养殖技术员', '汽车设计', '商务专员', '材料工程师', '网络客服', '风电运维工程师', '磨工', '货运司机', '蛋糕/裱花师', '媒介合作', '环保工程师', '经纪人', '美甲师', '金融产品经理', '生产组长/拉长', '招标专员', '足球教练', '广告创意设计', '销售顾问', '电信网络工程师', '送餐员', '其他职能职位', '护工', '全栈工程师', '售前客服', '其他生产制造职位', '游戏场景', '房地产规划开发', '咨询经理', '技术文档工程师', '其他金融职位', 'Android培训讲师', '工程监理', 'IC验证工程师', '理疗师', '人力资源经理/主管', '其他医生职位', '工艺工程师', '通信设备工程师', '会议活动销售', '铸造/锻造工程师', '保险精算师', '数据采集', '导演/编导', '会展活动执行', '水台', '测试工程师', '.NET培训讲师', '移动开发', '销售工程师', '系统工程师', '销售专员', '前端开发工程师', '.NET', '数据仓库', '施工员', '电脑维修', '用户研究总监', '税务外勤会计', '市场调研', '口腔科医生', '销售VP', '合规稽查', '绿化工', '儿童引导师', '活动策划', 'Flash设计师', '月嫂', '客服主管', '包装设计', '药物合成', '代驾司机', '医疗器械销售', '买手', '生物学研究人员', '专利律师', '运输经理/主管', 'UX设计师', '电子工程师', 'ETL工程师', 'Ruby', '其他技术职位', '地产中介', '总装工程师', '医疗器械生产/质量管理', '托管老师', '项目专员', '初中教师', '礼仪/迎宾/接待', '市场总监', '西餐厨师', '文案编辑', 'JavaScript', '移动通信工程师', '会展活动策划', '录音/音效', '设计师助理', '法语翻译', '导游', '运维总监', '普工/操作工', '插画师', '带货主播', '室内设计', '大客户代表', '仓库文员', '物流', '油漆工', '网约车司机', '生产营运', '给排水工程师', '剪辑师', '其他语种翻译', 'FAE', 'AI产品经理', '公关总监', '家教', '事务所律师', '门店店长', '记者/采编', '游戏推广', '投资者关系/证券事务代表', 'Golang', '校对录入', '可靠度工程师', '面包/烘焙师', '锅炉工', '化妆品研发', '采购专员/助理', '其他传媒职位', '弱电工程师', '美睫师', '医务管理', '公关媒介', '碳排放管理师', '韩语/朝鲜语翻译', '媒介策划', '包装工', '策划经理', '证券/基金/期货', '会议活动执行', '车辆运营', '行业研究', '裁剪工', '法务', '冲压工程师', '机械设备工程师', '洗碗工', '游戏策划', '底盘工程师', '地产招投标', 'GIS工程师', '摄影/摄像', '医疗器械注册', '运营', '理财顾问', '货运代理经理', '组织发展', '用户运营', '售后技术支持', '主持人/DJ', '游戏制作人', '成本会计', '非视觉设计', '放映员', '工业工程师(IE)', '媒介投放', '凉菜厨师', '微信运营', '系统策划', '高端房地产职位', '实施顾问', '电话客服', '系统管理员', '广告设计', '咨询热线/呼叫中心客服', '旅游产品开发/策划', '高端运营职位', '游戏主美术', '医生助理', '物流/仓储项目经理', '知识产权律师', '产品专员', '眼科医生', '自然语言处理', '人工智能', '淘宝运营', '羽毛球教练', '施工安全员', '车工', '人力资源咨询顾问', '数据标注/AI训练师', '高端供应链职位', '外贸业务员', '夹具工程师', '面料辅料开发', '工程造价', '民宿管家', '资料员', '德语翻译', '设计总监', 'DSP开发', '轮滑教练', '主播助理', '医药研发', '地产策划总监', 'FPGA开发', 'UI设计培训讲师', '法务总监', '酒店前厅经理', '创意总监', '房地产销售总监', '设计经理/主管', '汽车销售', '动漫培训讲师', '客房服务员', '进出口贸易', 'IT咨询顾问', '数据分析师', '市场策划', '学徒工', '演员/配音/模特', '其他医疗健康职位', '网络安全', '水电工', '机器人教师', '广告/会展项目经理', '校长/副校长', '财会培训讲师', '电信交换工程师', '贸易跟单', '供应商质量工程师', '交通/运输', '游戏界面设计师', '视觉设计', '游戏角色', '房地产销售/招商', '拼多多运营', '教育行政', '媒介专员', '动画设计', '园长/副园长', '临床医学总监', '售前技术支持', '产品助理', '物理教师', '焊工', '婚礼策划', '临床医学经理/专员', '生产计划/物料管理(PMC)', '物业管理员', '按摩师', '建筑机电工程师', '新媒体运营', '医美咨询', '算法工程师', '电路设计', '放射科医生', '美工', '皮肤科医生', '化妆/造型/服装', '广告销售', '架子鼓老师', '配送员', '政府关系', '机械制图员', '珠宝设计', '融资', '图像识别', '广告制作', '运营总监', '供应链专员', '搜索算法', '法务专员/助理', '内外饰设计工程师', '安检员', '纹绣师', '售后客服', '多媒体设计师', '灯光师', '烧烤师傅', '地产项目总监', 'C++培训讲师', '精神心理科医生', '其他房地产职位', 'iOS培训讲师', '医疗销售', '就业老师', 'CTO', '模具工', '供应链总监', '其他产品职位', '快递员', 'BIM工程师', '电话销售', '汽车质量工程师', '银行', '产品经理', '美术指导', '护士', '餐饮储备店长/干部', '装修项目经理', '线束设计', '财务顾问', '财务分析/财务BP', '企业党建', '生产设备管理员', '影视媒体', '家电维修', '体育教师/体育教练', '行政总厨', '硬件项目经理', '医疗器械研发', '充电桩设计', '临床数据分析', '通信项目经理', '语音识别', '总账会计', '总助/CEO助理/董事长助理', 'CFO', '理货员', '光伏系统工程师', 'Python', '无人机飞手', '二手车评估师', '教练', '促销员', '视觉设计师', 'iOS', '地产项目管理', '搬运工/装卸工', '缝纫工', '美容顾问', '内科医生', '铆工', '市场营销', '海外市场', '折弯工', '选址开发', '主编/副主编', '电机工程师', '风控', '健身', '猎头顾问', 'COO', 'Hadoop', '俄语翻译', '数据通信工程师', '招生顾问', '通信电源工程师', '后期制作', '妇产科医生', '性能测试', '超声科医生', '城市规划设计', '调酒师', '健身教练', '线下拓展运营', 'IT培训', '药店店长', '药剂师', '采购总监', '厂务', 'Perl', '客服经理', '陈列设计', '耳鼻喉科医生', '其他咨询/翻译类职位', '无线/射频通信工程师', '仓储', '亚马逊运营', '高端设计职位', '质检员', '广告审核', '副总裁/副总经理/VP', '铣工', '钣金工', '销售技术支持', '组装工', '技术美术', '钻工', '通信标准化工程师', '加油员', '日料厨师', '通信测试工程师', '推荐算法', '项目助理', '计量工程师', '产后康复师', '财务总监/VP', '数据产品经理', '基金经理', '汽车查勘定损', '计调'])

In [89]:
print(redis.hget("industry_info", "Java"))

https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100101

In [ ]:
redis.h

In [68]:
import ujson

ll = redis.rpush("industry_info_queue", *[ujson.dumps(i) for i in find])
# redis.expire("industry_info_queue",-1)
# redis.expire("")
ll

945

In [53]:
import ujson
# 序列化
st = ujson.dumps({'third_industry': 'C#',
                  'third_industry_url': 'https://www.zhipin.com/c101270100-p100106/'})
print(st)

{"third_industry":"C#","third_industry_url":"https:\/\/www.zhipin.com\/c101270100-p100106\/"}

In [15]:
# 反序列化
dt = dict(ujson.loads(st))
print(type(dt))

<class 'dict'>

In [76]:
lp = redis.lpop("industry_info_queue")
lpl = ujson.loads(lp)
print(type(lpl),lpl)

<class 'dict'> {'third_industry': 'Python', 'third_industry_url': 'https://www.zhipin.com/web/geek/job?query=&city=100010000&position=p100109'}