# Boss行业数据

In [12]:
import pandas as pd

## xpath爬取行业数据

In [28]:
from spider.crawl_home_page import IndustryInfo

info = IndustryInfo()
industry_infos = pd.DataFrame(info.parse_to_dict())
industry_infos

    first_industry second_industry third_industry    third_industry_url
0               技术            后端开发           Java  /c101270100-p100101/
1               技术            后端开发            C++  /c101270100-p100102/
2               技术            后端开发            PHP  /c101270100-p100103/
3               技术            后端开发              C  /c101270100-p100105/
4               技术            后端开发             C#  /c101270100-p100106/
..             ...             ...            ...                   ...
940           生产制造           技工/普工        搬运工/装卸工  /c101270100-p300630/
941           生产制造           技工/普工            切割工  /c101270100-p300631/
942           生产制造           技工/普工            样衣工  /c101270100-p300632/
943           生产制造           技工/普工            模具工  /c101270100-p300633/
944           生产制造        其他生产制造职位       其他生产制造职位  /c101270100-p300701/

[945 rows x 4 columns]

In [3]:
# industry_infos.to_excel("files/BOSS行业信息.xlsx", encoding="utf-8", index=False)

In [2]:
# industry_infos.to_dict()

NameError: name 'industry_infos' is not defined

In [6]:
iis = pd.read_excel("files/BOSS行业信息.xlsx")

    first_industry second_industry third_industry    third_industry_url
0               技术            后端开发           Java  /c101270100-p100101/
1               技术            后端开发            C++  /c101270100-p100102/
2               技术            后端开发            PHP  /c101270100-p100103/
3               技术            后端开发              C  /c101270100-p100105/
4               技术            后端开发             C#  /c101270100-p100106/
..             ...             ...            ...                   ...
940           生产制造           技工/普工        搬运工/装卸工  /c101270100-p300630/
941           生产制造           技工/普工            切割工  /c101270100-p300631/
942           生产制造           技工/普工            样衣工  /c101270100-p300632/
943           生产制造           技工/普工            模具工  /c101270100-p300633/
944           生产制造        其他生产制造职位       其他生产制造职位  /c101270100-p300701/

[945 rows x 4 columns]

In [7]:
type(iis)

pandas.core.frame.DataFrame

## 将数据存入mongo

In [5]:
from db.mongodb import Mongo

mongo = Mongo()
print(mongo)
print(mongo.db)
# mongo.insert("industry_info", iis.to_dict())

<db.mongodb.Mongo object at 0x7f7d5041fd50>
Database(MongoClient(host=['1.116.250.241:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', authmechanism='SCRAM-SHA-1'), 'rdvs')

In [16]:
industry_list = mongo.db.industry_info.find({"first_industry": "技术", "second_industry": "后端开发"})
industry_list

## mongo多条件过滤成二维表

In [32]:
pd.DataFrame(list(mongo.db.industry_info.find({"first_industry": "技术", "second_industry": "后端开发"}, {"_id": 0})))

,first_industry,second_industry,third_industry,third_industry_url
0,技术,后端开发,Java,https://www.zhipin.com/c101270100-p100101/
1,技术,后端开发,C++,https://www.zhipin.com/c101270100-p100102/
2,技术,后端开发,PHP,https://www.zhipin.com/c101270100-p100103/
3,技术,后端开发,C,https://www.zhipin.com/c101270100-p100105/
4,技术,后端开发,C#,https://www.zhipin.com/c101270100-p100106/
5,技术,后端开发,.NET,https://www.zhipin.com/c101270100-p100107/
6,技术,后端开发,Hadoop,https://www.zhipin.com/c101270100-p100108/
7,技术,后端开发,Python,https://www.zhipin.com/c101270100-p100109/
8,技术,后端开发,Delphi,https://www.zhipin.com/c101270100-p100110/
9,技术,后端开发,VB,https://www.zhipin.com/c101270100-p100111/
10,技术,后端开发,Perl,https://www.zhipin.com/c101270100-p100112/
11,技术,后端开发,Ruby,https://www.zhipin.com/c101270100-p100113/
12,技术,后端开发,Node.js,https://www.zhipin.com/c101270100-p100114/
13,技术,后端开发,Golang,https://www.zhipin.com/c101270100-p100116/
14,技术,后端开发,Erlang,https://www.zhipin.com/c101270100-p100119/
15,技术,后端开发,语音/视频/图形开发,https://www.zhipin.com/c101270100-p100121/
16,技术,后端开发,数据采集,https://www.zhipin.com/c101270100-p100122/
17,技术,后端开发,全栈工程师,https://www.zhipin.com/c101270100-p100123/
18,技术,后端开发,GIS工程师,https://www.zhipin.com/c101270100-p100124/
19,技术,后端开发,后端开发,https://www.zhipin.com/c101270100-p100199/

In [36]:
df  = pd.DataFrame(list(mongo.db.industry_info.find({}, {"_id": 0})))
df

,first_industry,second_industry,third_industry,third_industry_url
0,技术,后端开发,Java,https://www.zhipin.com/c101270100-p100101/
1,技术,后端开发,C++,https://www.zhipin.com/c101270100-p100102/
2,技术,后端开发,PHP,https://www.zhipin.com/c101270100-p100103/
3,技术,后端开发,C,https://www.zhipin.com/c101270100-p100105/
4,技术,后端开发,C#,https://www.zhipin.com/c101270100-p100106/
...,...,...,...,...
940,生产制造,技工/普工,搬运工/装卸工,https://www.zhipin.com/c101270100-p300630/
941,生产制造,技工/普工,切割工,https://www.zhipin.com/c101270100-p300631/
942,生产制造,技工/普工,样衣工,https://www.zhipin.com/c101270100-p300632/
943,生产制造,技工/普工,模具工,https://www.zhipin.com/c101270100-p300633/
944,生产制造,其他生产制造职位,其他生产制造职位,https://www.zhipin.com/c101270100-p300701/

In [39]:
df.groupby(by=["first_industry","second_industry"]).count()

                                third_industry  third_industry_url
first_industry second_industry
产品             产品经理                         10                  10
               其他产品职位                        1                   1
               高端产品职位                        2                   2
人事/财务/行政       人力资源                         10                  10
               其他职能职位                        1                   1
...                                        ...                 ...
销售             金融销售                          4                   4
               销售                           11                  11
               销售管理                          6                   6
               销售行政/商务                       6                   6
高级管理           高级管理职位                        8                   8

[125 rows x 2 columns]

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   first_industry      945 non-null    object
 1   second_industry     945 non-null    object
 2   third_industry      945 non-null    object
 3   third_industry_url  945 non-null    object
dtypes: object(4)
memory usage: 29.7+ KB

In [45]:
df.describe()

,first_industry,second_industry,third_industry,third_industry_url
count,945,945,945,945
unique,20,123,912,945
top,技术,技工/普工,广告设计,https://www.zhipin.com/c101270100-p100101/
freq,128,36,3,1